// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.matchmaking.mq.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Dissolved : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Dissolved GetRootAsDissolved(ByteBuffer _bb) { return GetRootAsDissolved(_bb, new Dissolved()); }
  public static Dissolved GetRootAsDissolved(ByteBuffer _bb, Dissolved obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyDissolved(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, DissolvedVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Dissolved __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string MatchId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMatchIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMatchIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMatchIdArray() { return __p.__vector_as_array<byte>(4); }
  public uint MatchType { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Reason { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public fb.protocol.matchmaking.raw.RegistryOutcomeEntry? RegistryOutcomes(int j) { int o = __p.__offset(10); return o != 0 ? (fb.protocol.matchmaking.raw.RegistryOutcomeEntry?)(new fb.protocol.matchmaking.raw.RegistryOutcomeEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RegistryOutcomesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fb.protocol.matchmaking.mq.raw.Dissolved> CreateDissolved(FlatBufferBuilder builder,
      StringOffset match_idOffset = default(StringOffset),
      uint match_type = 0,
      byte reason = 0,
      VectorOffset registry_outcomesOffset = default(VectorOffset)) {
    builder.StartTable(4);
    Dissolved.AddRegistryOutcomes(builder, registry_outcomesOffset);
    Dissolved.AddMatchType(builder, match_type);
    Dissolved.AddMatchId(builder, match_idOffset);
    Dissolved.AddReason(builder, reason);
    return Dissolved.EndDissolved(builder);
  }

  public static void StartDissolved(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddMatchId(FlatBufferBuilder builder, StringOffset matchIdOffset) { builder.AddOffset(0, matchIdOffset.Value, 0); }
  public static void AddMatchType(FlatBufferBuilder builder, uint matchType) { builder.AddUint(1, matchType, 0); }
  public static void AddReason(FlatBufferBuilder builder, byte reason) { builder.AddByte(2, reason, 0); }
  public static void AddRegistryOutcomes(FlatBufferBuilder builder, VectorOffset registryOutcomesOffset) { builder.AddOffset(3, registryOutcomesOffset.Value, 0); }
  public static VectorOffset CreateRegistryOutcomesVector(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.RegistryOutcomeEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRegistryOutcomesVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.RegistryOutcomeEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRegistryOutcomesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol.matchmaking.raw.RegistryOutcomeEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRegistryOutcomesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol.matchmaking.raw.RegistryOutcomeEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRegistryOutcomesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fb.protocol.matchmaking.mq.raw.Dissolved> EndDissolved(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.matchmaking.mq.raw.Dissolved>(o);
  }
  public static void FinishDissolvedBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.mq.raw.Dissolved> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDissolvedBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.mq.raw.Dissolved> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class DissolvedVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*MatchId*/, false)
      && verifier.VerifyField(tablePos, 6 /*MatchType*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Reason*/, 1 /*byte*/, 1, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*RegistryOutcomes*/, fb.protocol.matchmaking.raw.RegistryOutcomeEntryVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
