// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.matchmaking.mq.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Ready : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Ready GetRootAsReady(ByteBuffer _bb) { return GetRootAsReady(_bb, new Ready()); }
  public static Ready GetRootAsReady(ByteBuffer _bb, Ready obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyReady(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ReadyVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Ready __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string MatchId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMatchIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetMatchIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetMatchIdArray() { return __p.__vector_as_array<byte>(4); }
  public uint MatchType { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public fb.protocol.matchmaking.raw.MatchTeam? Teams(int j) { int o = __p.__offset(8); return o != 0 ? (fb.protocol.matchmaking.raw.MatchTeam?)(new fb.protocol.matchmaking.raw.MatchTeam()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TeamsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fb.protocol.matchmaking.mq.raw.Ready> CreateReady(FlatBufferBuilder builder,
      StringOffset match_idOffset = default(StringOffset),
      uint match_type = 0,
      VectorOffset teamsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    Ready.AddTeams(builder, teamsOffset);
    Ready.AddMatchType(builder, match_type);
    Ready.AddMatchId(builder, match_idOffset);
    return Ready.EndReady(builder);
  }

  public static void StartReady(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddMatchId(FlatBufferBuilder builder, StringOffset matchIdOffset) { builder.AddOffset(0, matchIdOffset.Value, 0); }
  public static void AddMatchType(FlatBufferBuilder builder, uint matchType) { builder.AddUint(1, matchType, 0); }
  public static void AddTeams(FlatBufferBuilder builder, VectorOffset teamsOffset) { builder.AddOffset(2, teamsOffset.Value, 0); }
  public static VectorOffset CreateTeamsVector(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.MatchTeam>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTeamsVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.MatchTeam>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTeamsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol.matchmaking.raw.MatchTeam>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTeamsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol.matchmaking.raw.MatchTeam>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTeamsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fb.protocol.matchmaking.mq.raw.Ready> EndReady(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.matchmaking.mq.raw.Ready>(o);
  }
  public static void FinishReadyBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.mq.raw.Ready> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedReadyBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.mq.raw.Ready> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ReadyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*MatchId*/, false)
      && verifier.VerifyField(tablePos, 6 /*MatchType*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Teams*/, fb.protocol.matchmaking.raw.MatchTeamVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
