// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct DestroyClan;
struct DestroyClanBuilder;

struct DestroyClan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DestroyClanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ERROR = 4
  };
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct DestroyClanBuilder {
  typedef DestroyClan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(DestroyClan::VT_ERROR, error, 0);
  }
  explicit DestroyClanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DestroyClan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DestroyClan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DestroyClan> CreateDestroyClan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t error = 0) {
  DestroyClanBuilder builder_(_fbb);
  builder_.add_error(error);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::DestroyClan *GetDestroyClan(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::DestroyClan>(buf);
}

inline const fb::protocol::internal::response::raw::DestroyClan *GetSizePrefixedDestroyClan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::DestroyClan>(buf);
}

inline bool VerifyDestroyClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::DestroyClan>(nullptr);
}

inline bool VerifySizePrefixedDestroyClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::DestroyClan>(nullptr);
}

inline void FinishDestroyClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::DestroyClan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDestroyClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::DestroyClan> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
