###
POST {{host}}/ping
Content-Type: application/json

{}


###
POST {{host}}/transfer
Content-Type: application/json

{
    "name": "채승현",
    "from": "Login",
    "to": "Game",
    "map": 123,
    "x": 65535,
    "y": 65535,
    "fd": 32
}


###
POST {{host}}/access/login
Content-Type: application/json

{
    "uid": 4
}

###
POST {{host}}/rabbitmq
Content-Type: application/json

{
    "ExchangeName": "amq.topic",
    "RouteKey": "fb.global",
    "Message": "cshyeon"
}