<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageId>Runner</PackageId>
    <RootNamespace>Runner</RootNamespace>
    <ApplicationIcon>icon_caption.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image\icon_header.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Control\" />
    <Folder Include="Style\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expression.Interaction" Version="3.0.40218" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Image\*.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon_caption.ico" />
  </ItemGroup>

</Project>
