// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Ban : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Ban GetRootAsBan(ByteBuffer _bb) { return GetRootAsBan(_bb, new Ban()); }
  public static Ban GetRootAsBan(ByteBuffer _bb, Ban obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyBan(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, BanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Ban __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Reason { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReasonBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetReasonBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetReasonArray() { return __p.__vector_as_array<byte>(8); }
  public nullable.nullable_uint? Days { get { int o = __p.__offset(10); return o != 0 ? (nullable.nullable_uint?)(new nullable.nullable_uint()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<fb.protocol._internal.request.raw.Ban> CreateBan(FlatBufferBuilder builder,
      uint world = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset reasonOffset = default(StringOffset),
      Offset<nullable.nullable_uint> daysOffset = default(Offset<nullable.nullable_uint>)) {
    builder.StartTable(4);
    Ban.AddDays(builder, daysOffset);
    Ban.AddReason(builder, reasonOffset);
    Ban.AddName(builder, nameOffset);
    Ban.AddWorld(builder, world);
    return Ban.EndBan(builder);
  }

  public static void StartBan(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddReason(FlatBufferBuilder builder, StringOffset reasonOffset) { builder.AddOffset(2, reasonOffset.Value, 0); }
  public static void AddDays(FlatBufferBuilder builder, Offset<nullable.nullable_uint> daysOffset) { builder.AddOffset(3, daysOffset.Value, 0); }
  public static Offset<fb.protocol._internal.request.raw.Ban> EndBan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.Ban>(o);
  }
  public static void FinishBanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.Ban> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedBanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.Ban> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class BanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Reason*/, false)
      && verifier.VerifyTable(tablePos, 10 /*Days*/, nullable.nullable_uintVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
