// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ChangePw : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ChangePw GetRootAsChangePw(ByteBuffer _bb) { return GetRootAsChangePw(_bb, new ChangePw()); }
  public static ChangePw GetRootAsChangePw(ByteBuffer _bb, ChangePw obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyChangePw(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ChangePwVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ChangePw __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Section { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSectionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSectionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSectionArray() { return __p.__vector_as_array<byte>(4); }
  public uint Uid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Before { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBeforeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetBeforeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetBeforeArray() { return __p.__vector_as_array<byte>(8); }
  public string After { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAfterBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetAfterBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetAfterArray() { return __p.__vector_as_array<byte>(10); }
  public uint Birthday { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.request.raw.ChangePw> CreateChangePw(FlatBufferBuilder builder,
      StringOffset sectionOffset = default(StringOffset),
      uint uid = 0,
      StringOffset beforeOffset = default(StringOffset),
      StringOffset afterOffset = default(StringOffset),
      uint birthday = 0) {
    builder.StartTable(5);
    ChangePw.AddBirthday(builder, birthday);
    ChangePw.AddAfter(builder, afterOffset);
    ChangePw.AddBefore(builder, beforeOffset);
    ChangePw.AddUid(builder, uid);
    ChangePw.AddSection(builder, sectionOffset);
    return ChangePw.EndChangePw(builder);
  }

  public static void StartChangePw(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddSection(FlatBufferBuilder builder, StringOffset sectionOffset) { builder.AddOffset(0, sectionOffset.Value, 0); }
  public static void AddUid(FlatBufferBuilder builder, uint uid) { builder.AddUint(1, uid, 0); }
  public static void AddBefore(FlatBufferBuilder builder, StringOffset beforeOffset) { builder.AddOffset(2, beforeOffset.Value, 0); }
  public static void AddAfter(FlatBufferBuilder builder, StringOffset afterOffset) { builder.AddOffset(3, afterOffset.Value, 0); }
  public static void AddBirthday(FlatBufferBuilder builder, uint birthday) { builder.AddUint(4, birthday, 0); }
  public static Offset<fb.protocol._internal.request.raw.ChangePw> EndChangePw(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.ChangePw>(o);
  }
  public static void FinishChangePwBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.ChangePw> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedChangePwBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.ChangePw> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ChangePwVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Section*/, false)
      && verifier.VerifyField(tablePos, 6 /*Uid*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Before*/, false)
      && verifier.VerifyString(tablePos, 10 /*After*/, false)
      && verifier.VerifyField(tablePos, 12 /*Birthday*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
