// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DeliverSystemMail : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DeliverSystemMail GetRootAsDeliverSystemMail(ByteBuffer _bb) { return GetRootAsDeliverSystemMail(_bb, new DeliverSystemMail()); }
  public static DeliverSystemMail GetRootAsDeliverSystemMail(ByteBuffer _bb, DeliverSystemMail obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyDeliverSystemMail(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, DeliverSystemMailVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DeliverSystemMail __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SystemMailId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Sender { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Users(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int UsersLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetUsersBytes() { return __p.__vector_as_span<uint>(10, 4); }
#else
  public ArraySegment<byte>? GetUsersBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public uint[] GetUsersArray() { return __p.__vector_as_array<uint>(10); }
  public string Title { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(12); }
  public string Contents { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetContentsBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetContentsBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetContentsArray() { return __p.__vector_as_array<byte>(14); }
  public uint Host { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.request.raw.DeliverSystemMail> CreateDeliverSystemMail(FlatBufferBuilder builder,
      uint world = 0,
      uint system_mail_id = 0,
      uint sender = 0,
      VectorOffset usersOffset = default(VectorOffset),
      StringOffset titleOffset = default(StringOffset),
      StringOffset contentsOffset = default(StringOffset),
      uint host = 0) {
    builder.StartTable(7);
    DeliverSystemMail.AddHost(builder, host);
    DeliverSystemMail.AddContents(builder, contentsOffset);
    DeliverSystemMail.AddTitle(builder, titleOffset);
    DeliverSystemMail.AddUsers(builder, usersOffset);
    DeliverSystemMail.AddSender(builder, sender);
    DeliverSystemMail.AddSystemMailId(builder, system_mail_id);
    DeliverSystemMail.AddWorld(builder, world);
    return DeliverSystemMail.EndDeliverSystemMail(builder);
  }

  public static void StartDeliverSystemMail(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddSystemMailId(FlatBufferBuilder builder, uint systemMailId) { builder.AddUint(1, systemMailId, 0); }
  public static void AddSender(FlatBufferBuilder builder, uint sender) { builder.AddUint(2, sender, 0); }
  public static void AddUsers(FlatBufferBuilder builder, VectorOffset usersOffset) { builder.AddOffset(3, usersOffset.Value, 0); }
  public static VectorOffset CreateUsersVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateUsersVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUsersVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateUsersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartUsersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(4, titleOffset.Value, 0); }
  public static void AddContents(FlatBufferBuilder builder, StringOffset contentsOffset) { builder.AddOffset(5, contentsOffset.Value, 0); }
  public static void AddHost(FlatBufferBuilder builder, uint host) { builder.AddUint(6, host, 0); }
  public static Offset<fb.protocol._internal.request.raw.DeliverSystemMail> EndDeliverSystemMail(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.DeliverSystemMail>(o);
  }
  public static void FinishDeliverSystemMailBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.DeliverSystemMail> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDeliverSystemMailBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.DeliverSystemMail> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class DeliverSystemMailVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*SystemMailId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Sender*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Users*/, 4 /*uint*/, false)
      && verifier.VerifyString(tablePos, 12 /*Title*/, false)
      && verifier.VerifyString(tablePos, 14 /*Contents*/, false)
      && verifier.VerifyField(tablePos, 16 /*Host*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
