// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetUnreceivedSystemMails : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GetUnreceivedSystemMails GetRootAsGetUnreceivedSystemMails(ByteBuffer _bb) { return GetRootAsGetUnreceivedSystemMails(_bb, new GetUnreceivedSystemMails()); }
  public static GetUnreceivedSystemMails GetRootAsGetUnreceivedSystemMails(ByteBuffer _bb, GetUnreceivedSystemMails obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetUnreceivedSystemMails(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetUnreceivedSystemMailsVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetUnreceivedSystemMails __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint User { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.request.raw.GetUnreceivedSystemMails> CreateGetUnreceivedSystemMails(FlatBufferBuilder builder,
      uint user = 0) {
    builder.StartTable(1);
    GetUnreceivedSystemMails.AddUser(builder, user);
    return GetUnreceivedSystemMails.EndGetUnreceivedSystemMails(builder);
  }

  public static void StartGetUnreceivedSystemMails(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddUser(FlatBufferBuilder builder, uint user) { builder.AddUint(0, user, 0); }
  public static Offset<fb.protocol._internal.request.raw.GetUnreceivedSystemMails> EndGetUnreceivedSystemMails(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.GetUnreceivedSystemMails>(o);
  }
  public static void FinishGetUnreceivedSystemMailsBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.GetUnreceivedSystemMails> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetUnreceivedSystemMailsBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.GetUnreceivedSystemMails> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetUnreceivedSystemMailsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*User*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
