// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinClan : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static JoinClan GetRootAsJoinClan(ByteBuffer _bb) { return GetRootAsJoinClan(_bb, new JoinClan()); }
  public static JoinClan GetRootAsJoinClan(ByteBuffer _bb, JoinClan obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyJoinClan(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, JoinClanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinClan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Host { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint InviterUid { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string InviteeName { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetInviteeNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetInviteeNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetInviteeNameArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<fb.protocol._internal.request.raw.JoinClan> CreateJoinClan(FlatBufferBuilder builder,
      uint world = 0,
      uint host = 0,
      uint inviter_uid = 0,
      StringOffset invitee_nameOffset = default(StringOffset)) {
    builder.StartTable(4);
    JoinClan.AddInviteeName(builder, invitee_nameOffset);
    JoinClan.AddInviterUid(builder, inviter_uid);
    JoinClan.AddHost(builder, host);
    JoinClan.AddWorld(builder, world);
    return JoinClan.EndJoinClan(builder);
  }

  public static void StartJoinClan(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddHost(FlatBufferBuilder builder, uint host) { builder.AddUint(1, host, 0); }
  public static void AddInviterUid(FlatBufferBuilder builder, uint inviterUid) { builder.AddUint(2, inviterUid, 0); }
  public static void AddInviteeName(FlatBufferBuilder builder, StringOffset inviteeNameOffset) { builder.AddOffset(3, inviteeNameOffset.Value, 0); }
  public static Offset<fb.protocol._internal.request.raw.JoinClan> EndJoinClan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.JoinClan>(o);
  }
  public static void FinishJoinClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.JoinClan> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedJoinClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.JoinClan> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class JoinClanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Host*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*InviterUid*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 10 /*InviteeName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
