// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ReloadTables : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ReloadTables GetRootAsReloadTables(ByteBuffer _bb) { return GetRootAsReloadTables(_bb, new ReloadTables()); }
  public static ReloadTables GetRootAsReloadTables(ByteBuffer _bb, ReloadTables obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyReloadTables(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ReloadTablesVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReloadTables __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Url { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUrlBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUrlBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUrlArray() { return __p.__vector_as_array<byte>(6); }
  public string TableNames(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int TableNamesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fb.protocol._internal.request.raw.ReloadTables> CreateReloadTables(FlatBufferBuilder builder,
      uint world = 0,
      StringOffset urlOffset = default(StringOffset),
      VectorOffset table_namesOffset = default(VectorOffset)) {
    builder.StartTable(3);
    ReloadTables.AddTableNames(builder, table_namesOffset);
    ReloadTables.AddUrl(builder, urlOffset);
    ReloadTables.AddWorld(builder, world);
    return ReloadTables.EndReloadTables(builder);
  }

  public static void StartReloadTables(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddUrl(FlatBufferBuilder builder, StringOffset urlOffset) { builder.AddOffset(1, urlOffset.Value, 0); }
  public static void AddTableNames(FlatBufferBuilder builder, VectorOffset tableNamesOffset) { builder.AddOffset(2, tableNamesOffset.Value, 0); }
  public static VectorOffset CreateTableNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTableNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTableNamesVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTableNamesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTableNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fb.protocol._internal.request.raw.ReloadTables> EndReloadTables(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.ReloadTables>(o);
  }
  public static void FinishReloadTablesBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.ReloadTables> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedReloadTablesBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.ReloadTables> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ReloadTablesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Url*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 8 /*TableNames*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
