// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetCastleOwner : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetCastleOwner GetRootAsSetCastleOwner(ByteBuffer _bb) { return GetRootAsSetCastleOwner(_bb, new SetCastleOwner()); }
  public static SetCastleOwner GetRootAsSetCastleOwner(ByteBuffer _bb, SetCastleOwner obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetCastleOwner(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetCastleOwnerVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetCastleOwner __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Host { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte DivineBeast { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public nullable.nullable_uint? OwnerClanId { get { int o = __p.__offset(10); return o != 0 ? (nullable.nullable_uint?)(new nullable.nullable_uint()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<fb.protocol._internal.request.raw.SetCastleOwner> CreateSetCastleOwner(FlatBufferBuilder builder,
      uint world = 0,
      uint host = 0,
      byte divine_beast = 0,
      Offset<nullable.nullable_uint> owner_clan_idOffset = default(Offset<nullable.nullable_uint>)) {
    builder.StartTable(4);
    SetCastleOwner.AddOwnerClanId(builder, owner_clan_idOffset);
    SetCastleOwner.AddHost(builder, host);
    SetCastleOwner.AddWorld(builder, world);
    SetCastleOwner.AddDivineBeast(builder, divine_beast);
    return SetCastleOwner.EndSetCastleOwner(builder);
  }

  public static void StartSetCastleOwner(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddHost(FlatBufferBuilder builder, uint host) { builder.AddUint(1, host, 0); }
  public static void AddDivineBeast(FlatBufferBuilder builder, byte divineBeast) { builder.AddByte(2, divineBeast, 0); }
  public static void AddOwnerClanId(FlatBufferBuilder builder, Offset<nullable.nullable_uint> ownerClanIdOffset) { builder.AddOffset(3, ownerClanIdOffset.Value, 0); }
  public static Offset<fb.protocol._internal.request.raw.SetCastleOwner> EndSetCastleOwner(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.SetCastleOwner>(o);
  }
  public static void FinishSetCastleOwnerBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.SetCastleOwner> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetCastleOwnerBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.SetCastleOwner> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetCastleOwnerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Host*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*DivineBeast*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTable(tablePos, 10 /*OwnerClanId*/, nullable.nullable_uintVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
