// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SetDateTime : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SetDateTime GetRootAsSetDateTime(ByteBuffer _bb) { return GetRootAsSetDateTime(_bb, new SetDateTime()); }
  public static SetDateTime GetRootAsSetDateTime(ByteBuffer _bb, SetDateTime obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySetDateTime(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SetDateTimeVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetDateTime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Datetime { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDatetimeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDatetimeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDatetimeArray() { return __p.__vector_as_array<byte>(6); }
  public bool Reset { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<fb.protocol._internal.request.raw.SetDateTime> CreateSetDateTime(FlatBufferBuilder builder,
      uint world = 0,
      StringOffset datetimeOffset = default(StringOffset),
      bool reset = false) {
    builder.StartTable(3);
    SetDateTime.AddDatetime(builder, datetimeOffset);
    SetDateTime.AddWorld(builder, world);
    SetDateTime.AddReset(builder, reset);
    return SetDateTime.EndSetDateTime(builder);
  }

  public static void StartSetDateTime(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddDatetime(FlatBufferBuilder builder, StringOffset datetimeOffset) { builder.AddOffset(1, datetimeOffset.Value, 0); }
  public static void AddReset(FlatBufferBuilder builder, bool reset) { builder.AddBool(2, reset, false); }
  public static Offset<fb.protocol._internal.request.raw.SetDateTime> EndSetDateTime(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.SetDateTime>(o);
  }
  public static void FinishSetDateTimeBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.SetDateTime> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSetDateTimeBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.SetDateTime> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SetDateTimeVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Datetime*/, false)
      && verifier.VerifyField(tablePos, 8 /*Reset*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
