// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Unban : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Unban GetRootAsUnban(ByteBuffer _bb) { return GetRootAsUnban(_bb, new Unban()); }
  public static Unban GetRootAsUnban(ByteBuffer _bb, Unban obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyUnban(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, UnbanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Unban __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Section { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSectionBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSectionBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSectionArray() { return __p.__vector_as_array<byte>(4); }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<fb.protocol._internal.request.raw.Unban> CreateUnban(FlatBufferBuilder builder,
      StringOffset sectionOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(2);
    Unban.AddName(builder, nameOffset);
    Unban.AddSection(builder, sectionOffset);
    return Unban.EndUnban(builder);
  }

  public static void StartUnban(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSection(FlatBufferBuilder builder, StringOffset sectionOffset) { builder.AddOffset(0, sectionOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<fb.protocol._internal.request.raw.Unban> EndUnban(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.Unban>(o);
  }
  public static void FinishUnbanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.Unban> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedUnbanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.Unban> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class UnbanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Section*/, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
