// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnclaimStorageBox : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static UnclaimStorageBox GetRootAsUnclaimStorageBox(ByteBuffer _bb) { return GetRootAsUnclaimStorageBox(_bb, new UnclaimStorageBox()); }
  public static UnclaimStorageBox GetRootAsUnclaimStorageBox(ByteBuffer _bb, UnclaimStorageBox obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyUnclaimStorageBox(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, UnclaimStorageBoxVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UnclaimStorageBox __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint World { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint User { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Id { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.request.raw.UnclaimStorageBox> CreateUnclaimStorageBox(FlatBufferBuilder builder,
      uint world = 0,
      uint user = 0,
      uint id = 0) {
    builder.StartTable(3);
    UnclaimStorageBox.AddId(builder, id);
    UnclaimStorageBox.AddUser(builder, user);
    UnclaimStorageBox.AddWorld(builder, world);
    return UnclaimStorageBox.EndUnclaimStorageBox(builder);
  }

  public static void StartUnclaimStorageBox(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(0, world, 0); }
  public static void AddUser(FlatBufferBuilder builder, uint user) { builder.AddUint(1, user, 0); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(2, id, 0); }
  public static Offset<fb.protocol._internal.request.raw.UnclaimStorageBox> EndUnclaimStorageBox(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.request.raw.UnclaimStorageBox>(o);
  }
  public static void FinishUnclaimStorageBoxBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.UnclaimStorageBox> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedUnclaimStorageBoxBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.request.raw.UnclaimStorageBox> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class UnclaimStorageBoxVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*User*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
