// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Character : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Character GetRootAsCharacter(ByteBuffer _bb) { return GetRootAsCharacter(_bb, new Character()); }
  public static Character GetRootAsCharacter(ByteBuffer _bb, Character obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCharacter(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CharacterVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Character __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Pw { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPwBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPwBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPwArray() { return __p.__vector_as_array<byte>(8); }
  public nullable.nullable_uint? Birth { get { int o = __p.__offset(10); return o != 0 ? (nullable.nullable_uint?)(new nullable.nullable_uint()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public byte Role { get { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort Look { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort Color { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte Gender { get { int o = __p.__offset(18); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte Nation { get { int o = __p.__offset(20); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte DivineBeast { get { int o = __p.__offset(22); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public uint Map { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public fb.protocol._internal.raw.Position? Position { get { int o = __p.__offset(26); return o != 0 ? (fb.protocol._internal.raw.Position?)(new fb.protocol._internal.raw.Position()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public byte Direction { get { int o = __p.__offset(28); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte State { get { int o = __p.__offset(30); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte ClassType { get { int o = __p.__offset(32); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte Promotion { get { int o = __p.__offset(34); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte Level { get { int o = __p.__offset(36); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ulong Exp { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Money { get { int o = __p.__offset(40); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong DepositedMoney { get { int o = __p.__offset(42); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public fb.protocol._internal.raw.Mimicry? Mimicry { get { int o = __p.__offset(44); return o != 0 ? (fb.protocol._internal.raw.Mimicry?)(new fb.protocol._internal.raw.Mimicry()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ulong Hp { get { int o = __p.__offset(46); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong BaseHp { get { int o = __p.__offset(48); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong AdditionalHp { get { int o = __p.__offset(50); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Mp { get { int o = __p.__offset(52); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong BaseMp { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong AdditionalMp { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public nullable.nullable_ubyte? WeaponColor { get { int o = __p.__offset(58); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? HelmetColor { get { int o = __p.__offset(60); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? ArmorColor { get { int o = __p.__offset(62); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? ShieldColor { get { int o = __p.__offset(64); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? RingLeftColor { get { int o = __p.__offset(66); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? RingRightColor { get { int o = __p.__offset(68); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? AuxTopColor { get { int o = __p.__offset(70); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public nullable.nullable_ubyte? AuxBotColor { get { int o = __p.__offset(72); return o != 0 ? (nullable.nullable_ubyte?)(new nullable.nullable_ubyte()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public fb.protocol._internal.raw.Buff? Buffs(int j) { int o = __p.__offset(74); return o != 0 ? (fb.protocol._internal.raw.Buff?)(new fb.protocol._internal.raw.Buff()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BuffsLength { get { int o = __p.__offset(74); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string Title { get { int o = __p.__offset(76); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(76, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(76); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(76); }
  public string CreatedDate { get { int o = __p.__offset(78); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCreatedDateBytes() { return __p.__vector_as_span<byte>(78, 1); }
#else
  public ArraySegment<byte>? GetCreatedDateBytes() { return __p.__vector_as_arraysegment(78); }
#endif
  public byte[] GetCreatedDateArray() { return __p.__vector_as_array<byte>(78); }
  public string UpdatedDate { get { int o = __p.__offset(80); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUpdatedDateBytes() { return __p.__vector_as_span<byte>(80, 1); }
#else
  public ArraySegment<byte>? GetUpdatedDateBytes() { return __p.__vector_as_arraysegment(80); }
#endif
  public byte[] GetUpdatedDateArray() { return __p.__vector_as_array<byte>(80); }
  public string FirstLoginDate { get { int o = __p.__offset(82); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFirstLoginDateBytes() { return __p.__vector_as_span<byte>(82, 1); }
#else
  public ArraySegment<byte>? GetFirstLoginDateBytes() { return __p.__vector_as_arraysegment(82); }
#endif
  public byte[] GetFirstLoginDateArray() { return __p.__vector_as_array<byte>(82); }
  public bool SuperHide { get { int o = __p.__offset(84); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public byte Speed { get { int o = __p.__offset(86); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<fb.protocol._internal.raw.Character> CreateCharacter(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset pwOffset = default(StringOffset),
      Offset<nullable.nullable_uint> birthOffset = default(Offset<nullable.nullable_uint>),
      byte role = 0,
      ushort look = 0,
      ushort color = 0,
      byte gender = 0,
      byte nation = 0,
      byte divine_beast = 0,
      uint map = 0,
      Offset<fb.protocol._internal.raw.Position> positionOffset = default(Offset<fb.protocol._internal.raw.Position>),
      byte direction = 0,
      byte state = 0,
      byte class_type = 0,
      byte promotion = 0,
      byte level = 0,
      ulong exp = 0,
      ulong money = 0,
      ulong deposited_money = 0,
      Offset<fb.protocol._internal.raw.Mimicry> mimicryOffset = default(Offset<fb.protocol._internal.raw.Mimicry>),
      ulong hp = 0,
      ulong base_hp = 0,
      ulong additional_hp = 0,
      ulong mp = 0,
      ulong base_mp = 0,
      ulong additional_mp = 0,
      Offset<nullable.nullable_ubyte> weapon_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> helmet_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> armor_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> shield_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> ring_left_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> ring_right_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> aux_top_colorOffset = default(Offset<nullable.nullable_ubyte>),
      Offset<nullable.nullable_ubyte> aux_bot_colorOffset = default(Offset<nullable.nullable_ubyte>),
      VectorOffset buffsOffset = default(VectorOffset),
      StringOffset titleOffset = default(StringOffset),
      StringOffset created_dateOffset = default(StringOffset),
      StringOffset updated_dateOffset = default(StringOffset),
      StringOffset first_login_dateOffset = default(StringOffset),
      bool super_hide = false,
      byte speed = 0) {
    builder.StartTable(42);
    Character.AddAdditionalMp(builder, additional_mp);
    Character.AddBaseMp(builder, base_mp);
    Character.AddMp(builder, mp);
    Character.AddAdditionalHp(builder, additional_hp);
    Character.AddBaseHp(builder, base_hp);
    Character.AddHp(builder, hp);
    Character.AddDepositedMoney(builder, deposited_money);
    Character.AddMoney(builder, money);
    Character.AddExp(builder, exp);
    Character.AddFirstLoginDate(builder, first_login_dateOffset);
    Character.AddUpdatedDate(builder, updated_dateOffset);
    Character.AddCreatedDate(builder, created_dateOffset);
    Character.AddTitle(builder, titleOffset);
    Character.AddBuffs(builder, buffsOffset);
    Character.AddAuxBotColor(builder, aux_bot_colorOffset);
    Character.AddAuxTopColor(builder, aux_top_colorOffset);
    Character.AddRingRightColor(builder, ring_right_colorOffset);
    Character.AddRingLeftColor(builder, ring_left_colorOffset);
    Character.AddShieldColor(builder, shield_colorOffset);
    Character.AddArmorColor(builder, armor_colorOffset);
    Character.AddHelmetColor(builder, helmet_colorOffset);
    Character.AddWeaponColor(builder, weapon_colorOffset);
    Character.AddMimicry(builder, mimicryOffset);
    Character.AddPosition(builder, positionOffset);
    Character.AddMap(builder, map);
    Character.AddBirth(builder, birthOffset);
    Character.AddPw(builder, pwOffset);
    Character.AddName(builder, nameOffset);
    Character.AddId(builder, id);
    Character.AddColor(builder, color);
    Character.AddLook(builder, look);
    Character.AddSpeed(builder, speed);
    Character.AddSuperHide(builder, super_hide);
    Character.AddLevel(builder, level);
    Character.AddPromotion(builder, promotion);
    Character.AddClassType(builder, class_type);
    Character.AddState(builder, state);
    Character.AddDirection(builder, direction);
    Character.AddDivineBeast(builder, divine_beast);
    Character.AddNation(builder, nation);
    Character.AddGender(builder, gender);
    Character.AddRole(builder, role);
    return Character.EndCharacter(builder);
  }

  public static void StartCharacter(FlatBufferBuilder builder) { builder.StartTable(42); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddPw(FlatBufferBuilder builder, StringOffset pwOffset) { builder.AddOffset(2, pwOffset.Value, 0); }
  public static void AddBirth(FlatBufferBuilder builder, Offset<nullable.nullable_uint> birthOffset) { builder.AddOffset(3, birthOffset.Value, 0); }
  public static void AddRole(FlatBufferBuilder builder, byte role) { builder.AddByte(4, role, 0); }
  public static void AddLook(FlatBufferBuilder builder, ushort look) { builder.AddUshort(5, look, 0); }
  public static void AddColor(FlatBufferBuilder builder, ushort color) { builder.AddUshort(6, color, 0); }
  public static void AddGender(FlatBufferBuilder builder, byte gender) { builder.AddByte(7, gender, 0); }
  public static void AddNation(FlatBufferBuilder builder, byte nation) { builder.AddByte(8, nation, 0); }
  public static void AddDivineBeast(FlatBufferBuilder builder, byte divineBeast) { builder.AddByte(9, divineBeast, 0); }
  public static void AddMap(FlatBufferBuilder builder, uint map) { builder.AddUint(10, map, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Position> positionOffset) { builder.AddOffset(11, positionOffset.Value, 0); }
  public static void AddDirection(FlatBufferBuilder builder, byte direction) { builder.AddByte(12, direction, 0); }
  public static void AddState(FlatBufferBuilder builder, byte state) { builder.AddByte(13, state, 0); }
  public static void AddClassType(FlatBufferBuilder builder, byte classType) { builder.AddByte(14, classType, 0); }
  public static void AddPromotion(FlatBufferBuilder builder, byte promotion) { builder.AddByte(15, promotion, 0); }
  public static void AddLevel(FlatBufferBuilder builder, byte level) { builder.AddByte(16, level, 0); }
  public static void AddExp(FlatBufferBuilder builder, ulong exp) { builder.AddUlong(17, exp, 0); }
  public static void AddMoney(FlatBufferBuilder builder, ulong money) { builder.AddUlong(18, money, 0); }
  public static void AddDepositedMoney(FlatBufferBuilder builder, ulong depositedMoney) { builder.AddUlong(19, depositedMoney, 0); }
  public static void AddMimicry(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Mimicry> mimicryOffset) { builder.AddOffset(20, mimicryOffset.Value, 0); }
  public static void AddHp(FlatBufferBuilder builder, ulong hp) { builder.AddUlong(21, hp, 0); }
  public static void AddBaseHp(FlatBufferBuilder builder, ulong baseHp) { builder.AddUlong(22, baseHp, 0); }
  public static void AddAdditionalHp(FlatBufferBuilder builder, ulong additionalHp) { builder.AddUlong(23, additionalHp, 0); }
  public static void AddMp(FlatBufferBuilder builder, ulong mp) { builder.AddUlong(24, mp, 0); }
  public static void AddBaseMp(FlatBufferBuilder builder, ulong baseMp) { builder.AddUlong(25, baseMp, 0); }
  public static void AddAdditionalMp(FlatBufferBuilder builder, ulong additionalMp) { builder.AddUlong(26, additionalMp, 0); }
  public static void AddWeaponColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> weaponColorOffset) { builder.AddOffset(27, weaponColorOffset.Value, 0); }
  public static void AddHelmetColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> helmetColorOffset) { builder.AddOffset(28, helmetColorOffset.Value, 0); }
  public static void AddArmorColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> armorColorOffset) { builder.AddOffset(29, armorColorOffset.Value, 0); }
  public static void AddShieldColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> shieldColorOffset) { builder.AddOffset(30, shieldColorOffset.Value, 0); }
  public static void AddRingLeftColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> ringLeftColorOffset) { builder.AddOffset(31, ringLeftColorOffset.Value, 0); }
  public static void AddRingRightColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> ringRightColorOffset) { builder.AddOffset(32, ringRightColorOffset.Value, 0); }
  public static void AddAuxTopColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> auxTopColorOffset) { builder.AddOffset(33, auxTopColorOffset.Value, 0); }
  public static void AddAuxBotColor(FlatBufferBuilder builder, Offset<nullable.nullable_ubyte> auxBotColorOffset) { builder.AddOffset(34, auxBotColorOffset.Value, 0); }
  public static void AddBuffs(FlatBufferBuilder builder, VectorOffset buffsOffset) { builder.AddOffset(35, buffsOffset.Value, 0); }
  public static VectorOffset CreateBuffsVector(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Buff>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Buff>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol._internal.raw.Buff>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBuffsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol._internal.raw.Buff>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBuffsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(36, titleOffset.Value, 0); }
  public static void AddCreatedDate(FlatBufferBuilder builder, StringOffset createdDateOffset) { builder.AddOffset(37, createdDateOffset.Value, 0); }
  public static void AddUpdatedDate(FlatBufferBuilder builder, StringOffset updatedDateOffset) { builder.AddOffset(38, updatedDateOffset.Value, 0); }
  public static void AddFirstLoginDate(FlatBufferBuilder builder, StringOffset firstLoginDateOffset) { builder.AddOffset(39, firstLoginDateOffset.Value, 0); }
  public static void AddSuperHide(FlatBufferBuilder builder, bool superHide) { builder.AddBool(40, superHide, false); }
  public static void AddSpeed(FlatBufferBuilder builder, byte speed) { builder.AddByte(41, speed, 0); }
  public static Offset<fb.protocol._internal.raw.Character> EndCharacter(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.raw.Character>(o);
  }
  public static void FinishCharacterBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Character> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCharacterBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Character> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CharacterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Pw*/, false)
      && verifier.VerifyTable(tablePos, 10 /*Birth*/, nullable.nullable_uintVerify.Verify, false)
      && verifier.VerifyField(tablePos, 12 /*Role*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 14 /*Look*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 16 /*Color*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 18 /*Gender*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 20 /*Nation*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 22 /*DivineBeast*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 24 /*Map*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 26 /*Position*/, fb.protocol._internal.raw.PositionVerify.Verify, false)
      && verifier.VerifyField(tablePos, 28 /*Direction*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 30 /*State*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 32 /*ClassType*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 34 /*Promotion*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 36 /*Level*/, 1 /*byte*/, 1, false)
      && verifier.VerifyField(tablePos, 38 /*Exp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 40 /*Money*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 42 /*DepositedMoney*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTable(tablePos, 44 /*Mimicry*/, fb.protocol._internal.raw.MimicryVerify.Verify, false)
      && verifier.VerifyField(tablePos, 46 /*Hp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 48 /*BaseHp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 50 /*AdditionalHp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 52 /*Mp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 54 /*BaseMp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 56 /*AdditionalMp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTable(tablePos, 58 /*WeaponColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 60 /*HelmetColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 62 /*ArmorColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 64 /*ShieldColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 66 /*RingLeftColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 68 /*RingRightColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 70 /*AuxTopColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 72 /*AuxBotColor*/, nullable.nullable_ubyteVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 74 /*Buffs*/, fb.protocol._internal.raw.BuffVerify.Verify, false)
      && verifier.VerifyString(tablePos, 76 /*Title*/, false)
      && verifier.VerifyString(tablePos, 78 /*CreatedDate*/, false)
      && verifier.VerifyString(tablePos, 80 /*UpdatedDate*/, false)
      && verifier.VerifyString(tablePos, 82 /*FirstLoginDate*/, false)
      && verifier.VerifyField(tablePos, 84 /*SuperHide*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 86 /*Speed*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
