// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.raw
{

public enum ClanActionType : sbyte
{
  Join = 0,
  Leave = 1,
  Kick = 2,
  ChangeRole = 3,
  SetTitle = 4,
};


}
