// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Clan : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Clan GetRootAsClan(ByteBuffer _bb) { return GetRootAsClan(_bb, new Clan()); }
  public static Clan GetRootAsClan(ByteBuffer _bb, Clan obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyClan(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ClanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Clan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public string Title { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTitleBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTitleBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTitleArray() { return __p.__vector_as_array<byte>(8); }
  public nullable.nullable_uint? AlliedClanId { get { int o = __p.__offset(10); return o != 0 ? (nullable.nullable_uint?)(new nullable.nullable_uint()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint EnemyClanIds(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int EnemyClanIdsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetEnemyClanIdsBytes() { return __p.__vector_as_span<uint>(12, 4); }
#else
  public ArraySegment<byte>? GetEnemyClanIdsBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public uint[] GetEnemyClanIdsArray() { return __p.__vector_as_array<uint>(12); }
  public ulong Money { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<fb.protocol._internal.raw.Clan> CreateClan(FlatBufferBuilder builder,
      uint id = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset titleOffset = default(StringOffset),
      Offset<nullable.nullable_uint> allied_clan_idOffset = default(Offset<nullable.nullable_uint>),
      VectorOffset enemy_clan_idsOffset = default(VectorOffset),
      ulong money = 0) {
    builder.StartTable(6);
    Clan.AddMoney(builder, money);
    Clan.AddEnemyClanIds(builder, enemy_clan_idsOffset);
    Clan.AddAlliedClanId(builder, allied_clan_idOffset);
    Clan.AddTitle(builder, titleOffset);
    Clan.AddName(builder, nameOffset);
    Clan.AddId(builder, id);
    return Clan.EndClan(builder);
  }

  public static void StartClan(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddTitle(FlatBufferBuilder builder, StringOffset titleOffset) { builder.AddOffset(2, titleOffset.Value, 0); }
  public static void AddAlliedClanId(FlatBufferBuilder builder, Offset<nullable.nullable_uint> alliedClanIdOffset) { builder.AddOffset(3, alliedClanIdOffset.Value, 0); }
  public static void AddEnemyClanIds(FlatBufferBuilder builder, VectorOffset enemyClanIdsOffset) { builder.AddOffset(4, enemyClanIdsOffset.Value, 0); }
  public static VectorOffset CreateEnemyClanIdsVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEnemyClanIdsVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnemyClanIdsVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEnemyClanIdsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEnemyClanIdsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMoney(FlatBufferBuilder builder, ulong money) { builder.AddUlong(5, money, 0); }
  public static Offset<fb.protocol._internal.raw.Clan> EndClan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.raw.Clan>(o);
  }
  public static void FinishClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Clan> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Clan> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ClanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyString(tablePos, 8 /*Title*/, false)
      && verifier.VerifyTable(tablePos, 10 /*AlliedClanId*/, nullable.nullable_uintVerify.Verify, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*EnemyClanIds*/, 4 /*uint*/, false)
      && verifier.VerifyField(tablePos, 14 /*Money*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
