// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.raw
{

public enum GroupActionType : sbyte
{
  Enter = 0,
  Leave = 1,
  Kick = 2,
};


}
