// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StorageRewardMark : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static StorageRewardMark GetRootAsStorageRewardMark(ByteBuffer _bb) { return GetRootAsStorageRewardMark(_bb, new StorageRewardMark()); }
  public static StorageRewardMark GetRootAsStorageRewardMark(ByteBuffer _bb, StorageRewardMark obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyStorageRewardMark(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, StorageRewardMarkVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StorageRewardMark __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint User { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string PendingId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPendingIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPendingIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPendingIdArray() { return __p.__vector_as_array<byte>(6); }
  public string ExpiredDate { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetExpiredDateBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetExpiredDateBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetExpiredDateArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<fb.protocol._internal.raw.StorageRewardMark> CreateStorageRewardMark(FlatBufferBuilder builder,
      uint user = 0,
      StringOffset pending_idOffset = default(StringOffset),
      StringOffset expired_dateOffset = default(StringOffset)) {
    builder.StartTable(3);
    StorageRewardMark.AddExpiredDate(builder, expired_dateOffset);
    StorageRewardMark.AddPendingId(builder, pending_idOffset);
    StorageRewardMark.AddUser(builder, user);
    return StorageRewardMark.EndStorageRewardMark(builder);
  }

  public static void StartStorageRewardMark(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUser(FlatBufferBuilder builder, uint user) { builder.AddUint(0, user, 0); }
  public static void AddPendingId(FlatBufferBuilder builder, StringOffset pendingIdOffset) { builder.AddOffset(1, pendingIdOffset.Value, 0); }
  public static void AddExpiredDate(FlatBufferBuilder builder, StringOffset expiredDateOffset) { builder.AddOffset(2, expiredDateOffset.Value, 0); }
  public static Offset<fb.protocol._internal.raw.StorageRewardMark> EndStorageRewardMark(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.raw.StorageRewardMark>(o);
  }
  public static void FinishStorageRewardMarkBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.StorageRewardMark> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedStorageRewardMarkBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.StorageRewardMark> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class StorageRewardMarkVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*User*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*PendingId*/, false)
      && verifier.VerifyString(tablePos, 8 /*ExpiredDate*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
