// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CastleList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CastleList GetRootAsCastleList(ByteBuffer _bb) { return GetRootAsCastleList(_bb, new CastleList()); }
  public static CastleList GetRootAsCastleList(ByteBuffer _bb, CastleList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCastleList(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CastleListVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CastleList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Host { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public fb.protocol._internal.raw.Castle? Castles(int j) { int o = __p.__offset(6); return o != 0 ? (fb.protocol._internal.raw.Castle?)(new fb.protocol._internal.raw.Castle()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CastlesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public uint Error { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.response.raw.CastleList> CreateCastleList(FlatBufferBuilder builder,
      uint host = 0,
      VectorOffset castlesOffset = default(VectorOffset),
      uint error = 0) {
    builder.StartTable(3);
    CastleList.AddError(builder, error);
    CastleList.AddCastles(builder, castlesOffset);
    CastleList.AddHost(builder, host);
    return CastleList.EndCastleList(builder);
  }

  public static void StartCastleList(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddHost(FlatBufferBuilder builder, uint host) { builder.AddUint(0, host, 0); }
  public static void AddCastles(FlatBufferBuilder builder, VectorOffset castlesOffset) { builder.AddOffset(1, castlesOffset.Value, 0); }
  public static VectorOffset CreateCastlesVector(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Castle>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCastlesVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Castle>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCastlesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol._internal.raw.Castle>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCastlesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol._internal.raw.Castle>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCastlesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(2, error, 0); }
  public static Offset<fb.protocol._internal.response.raw.CastleList> EndCastleList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.CastleList>(o);
  }
  public static void FinishCastleListBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.CastleList> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCastleListBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.CastleList> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CastleListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Host*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Castles*/, fb.protocol._internal.raw.CastleVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
