// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WriteSystemMail : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static WriteSystemMail GetRootAsWriteSystemMail(ByteBuffer _bb) { return GetRootAsWriteSystemMail(_bb, new WriteSystemMail()); }
  public static WriteSystemMail GetRootAsWriteSystemMail(ByteBuffer _bb, WriteSystemMail obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyWriteSystemMail(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, WriteSystemMailVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WriteSystemMail __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.protocol._internal.raw.SystemMail? Mail { get { int o = __p.__offset(4); return o != 0 ? (fb.protocol._internal.raw.SystemMail?)(new fb.protocol._internal.raw.SystemMail()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint Error { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.response.raw.WriteSystemMail> CreateWriteSystemMail(FlatBufferBuilder builder,
      Offset<fb.protocol._internal.raw.SystemMail> mailOffset = default(Offset<fb.protocol._internal.raw.SystemMail>),
      uint error = 0) {
    builder.StartTable(2);
    WriteSystemMail.AddError(builder, error);
    WriteSystemMail.AddMail(builder, mailOffset);
    return WriteSystemMail.EndWriteSystemMail(builder);
  }

  public static void StartWriteSystemMail(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMail(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.SystemMail> mailOffset) { builder.AddOffset(0, mailOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(1, error, 0); }
  public static Offset<fb.protocol._internal.response.raw.WriteSystemMail> EndWriteSystemMail(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.WriteSystemMail>(o);
  }
  public static void FinishWriteSystemMailBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.WriteSystemMail> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedWriteSystemMailBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.WriteSystemMail> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class WriteSystemMailVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Mail*/, fb.protocol._internal.raw.SystemMailVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
