// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct WriteSystemStorageBox : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static WriteSystemStorageBox GetRootAsWriteSystemStorageBox(ByteBuffer _bb) { return GetRootAsWriteSystemStorageBox(_bb, new WriteSystemStorageBox()); }
  public static WriteSystemStorageBox GetRootAsWriteSystemStorageBox(ByteBuffer _bb, WriteSystemStorageBox obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyWriteSystemStorageBox(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, WriteSystemStorageBoxVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WriteSystemStorageBox __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.protocol._internal.raw.SystemStorageBox? Box { get { int o = __p.__offset(4); return o != 0 ? (fb.protocol._internal.raw.SystemStorageBox?)(new fb.protocol._internal.raw.SystemStorageBox()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint Error { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.response.raw.WriteSystemStorageBox> CreateWriteSystemStorageBox(FlatBufferBuilder builder,
      Offset<fb.protocol._internal.raw.SystemStorageBox> boxOffset = default(Offset<fb.protocol._internal.raw.SystemStorageBox>),
      uint error = 0) {
    builder.StartTable(2);
    WriteSystemStorageBox.AddError(builder, error);
    WriteSystemStorageBox.AddBox(builder, boxOffset);
    return WriteSystemStorageBox.EndWriteSystemStorageBox(builder);
  }

  public static void StartWriteSystemStorageBox(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddBox(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.SystemStorageBox> boxOffset) { builder.AddOffset(0, boxOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(1, error, 0); }
  public static Offset<fb.protocol._internal.response.raw.WriteSystemStorageBox> EndWriteSystemStorageBox(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.WriteSystemStorageBox>(o);
  }
  public static void FinishWriteSystemStorageBoxBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.WriteSystemStorageBox> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedWriteSystemStorageBoxBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.WriteSystemStorageBox> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class WriteSystemStorageBoxVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Box*/, fb.protocol._internal.raw.SystemStorageBoxVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
