// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.matchmaking.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Dequeue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Dequeue GetRootAsDequeue(ByteBuffer _bb) { return GetRootAsDequeue(_bb, new Dequeue()); }
  public static Dequeue GetRootAsDequeue(ByteBuffer _bb, Dequeue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyDequeue(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, DequeueVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Dequeue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MatchType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ulong TicketId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint World { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint CharacterId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol.matchmaking.request.raw.Dequeue> CreateDequeue(FlatBufferBuilder builder,
      uint match_type = 0,
      ulong ticket_id = 0,
      uint world = 0,
      uint character_id = 0) {
    builder.StartTable(4);
    Dequeue.AddTicketId(builder, ticket_id);
    Dequeue.AddCharacterId(builder, character_id);
    Dequeue.AddWorld(builder, world);
    Dequeue.AddMatchType(builder, match_type);
    return Dequeue.EndDequeue(builder);
  }

  public static void StartDequeue(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddMatchType(FlatBufferBuilder builder, uint matchType) { builder.AddUint(0, matchType, 0); }
  public static void AddTicketId(FlatBufferBuilder builder, ulong ticketId) { builder.AddUlong(1, ticketId, 0); }
  public static void AddWorld(FlatBufferBuilder builder, uint world) { builder.AddUint(2, world, 0); }
  public static void AddCharacterId(FlatBufferBuilder builder, uint characterId) { builder.AddUint(3, characterId, 0); }
  public static Offset<fb.protocol.matchmaking.request.raw.Dequeue> EndDequeue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.matchmaking.request.raw.Dequeue>(o);
  }
  public static void FinishDequeueBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.request.raw.Dequeue> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDequeueBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.request.raw.Dequeue> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class DequeueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MatchType*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*TicketId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*World*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*CharacterId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
