// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.matchmaking.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Register : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Register GetRootAsRegister(ByteBuffer _bb) { return GetRootAsRegister(_bb, new Register()); }
  public static Register GetRootAsRegister(ByteBuffer _bb, Register obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRegister(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RegisterVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Register __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint MatchType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public fb.protocol.matchmaking.raw.RegistryEntry? Entries(int j) { int o = __p.__offset(6); return o != 0 ? (fb.protocol.matchmaking.raw.RegistryEntry?)(new fb.protocol.matchmaking.raw.RegistryEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EntriesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fb.protocol.matchmaking.request.raw.Register> CreateRegister(FlatBufferBuilder builder,
      uint match_type = 0,
      VectorOffset entriesOffset = default(VectorOffset)) {
    builder.StartTable(2);
    Register.AddEntries(builder, entriesOffset);
    Register.AddMatchType(builder, match_type);
    return Register.EndRegister(builder);
  }

  public static void StartRegister(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMatchType(FlatBufferBuilder builder, uint matchType) { builder.AddUint(0, matchType, 0); }
  public static void AddEntries(FlatBufferBuilder builder, VectorOffset entriesOffset) { builder.AddOffset(1, entriesOffset.Value, 0); }
  public static VectorOffset CreateEntriesVector(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.RegistryEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.raw.RegistryEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol.matchmaking.raw.RegistryEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol.matchmaking.raw.RegistryEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEntriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fb.protocol.matchmaking.request.raw.Register> EndRegister(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.matchmaking.request.raw.Register>(o);
  }
  public static void FinishRegisterBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.request.raw.Register> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRegisterBuffer(FlatBufferBuilder builder, Offset<fb.protocol.matchmaking.request.raw.Register> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RegisterVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MatchType*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Entries*/, fb.protocol.matchmaking.raw.RegistryEntryVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
