// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTSENDSYSTEMMAILTOUSER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTSENDSYSTEMMAILTOUSER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct SendSystemMailToUser;
struct SendSystemMailToUserBuilder;

struct SendSystemMailToUser FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SendSystemMailToUserBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER = 4,
    VT_SYSTEM_MAIL_ID = 6,
    VT_HOST = 8
  };
  uint32_t user() const {
    return GetField<uint32_t>(VT_USER, 0);
  }
  uint32_t system_mail_id() const {
    return GetField<uint32_t>(VT_SYSTEM_MAIL_ID, 0);
  }
  uint32_t host() const {
    return GetField<uint32_t>(VT_HOST, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_USER, 4) &&
           VerifyField<uint32_t>(verifier, VT_SYSTEM_MAIL_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_HOST, 4) &&
           verifier.EndTable();
  }
};

struct SendSystemMailToUserBuilder {
  typedef SendSystemMailToUser Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_user(uint32_t user) {
    fbb_.AddElement<uint32_t>(SendSystemMailToUser::VT_USER, user, 0);
  }
  void add_system_mail_id(uint32_t system_mail_id) {
    fbb_.AddElement<uint32_t>(SendSystemMailToUser::VT_SYSTEM_MAIL_ID, system_mail_id, 0);
  }
  void add_host(uint32_t host) {
    fbb_.AddElement<uint32_t>(SendSystemMailToUser::VT_HOST, host, 0);
  }
  explicit SendSystemMailToUserBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SendSystemMailToUser> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SendSystemMailToUser>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SendSystemMailToUser> CreateSendSystemMailToUser(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t user = 0,
    uint32_t system_mail_id = 0,
    uint32_t host = 0) {
  SendSystemMailToUserBuilder builder_(_fbb);
  builder_.add_host(host);
  builder_.add_system_mail_id(system_mail_id);
  builder_.add_user(user);
  return builder_.Finish();
}

inline const fb::protocol::internal::request::raw::SendSystemMailToUser *GetSendSystemMailToUser(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::SendSystemMailToUser>(buf);
}

inline const fb::protocol::internal::request::raw::SendSystemMailToUser *GetSizePrefixedSendSystemMailToUser(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::SendSystemMailToUser>(buf);
}

inline bool VerifySendSystemMailToUserBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::SendSystemMailToUser>(nullptr);
}

inline bool VerifySizePrefixedSendSystemMailToUserBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::SendSystemMailToUser>(nullptr);
}

inline void FinishSendSystemMailToUserBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::SendSystemMailToUser> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSendSystemMailToUserBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::SendSystemMailToUser> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTSENDSYSTEMMAILTOUSER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
