// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTLOGIN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTLOGIN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "nullable_uint_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct Login;
struct LoginBuilder;

struct Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD = 4,
    VT_UID = 6,
    VT_NAME = 8,
    VT_HOST = 10,
    VT_FORCE = 12,
    VT_PROCESS_WORLD = 14
  };
  uint32_t world() const {
    return GetField<uint32_t>(VT_WORLD, 0);
  }
  uint32_t uid() const {
    return GetField<uint32_t>(VT_UID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint8_t host() const {
    return GetField<uint8_t>(VT_HOST, 0);
  }
  bool force() const {
    return GetField<uint8_t>(VT_FORCE, 0) != 0;
  }
  const nullable::nullable_uint *process_world() const {
    return GetPointer<const nullable::nullable_uint *>(VT_PROCESS_WORLD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WORLD, 4) &&
           VerifyField<uint32_t>(verifier, VT_UID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_HOST, 1) &&
           VerifyField<uint8_t>(verifier, VT_FORCE, 1) &&
           VerifyOffset(verifier, VT_PROCESS_WORLD) &&
           verifier.VerifyTable(process_world()) &&
           verifier.EndTable();
  }
};

struct LoginBuilder {
  typedef Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world(uint32_t world) {
    fbb_.AddElement<uint32_t>(Login::VT_WORLD, world, 0);
  }
  void add_uid(uint32_t uid) {
    fbb_.AddElement<uint32_t>(Login::VT_UID, uid, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Login::VT_NAME, name);
  }
  void add_host(uint8_t host) {
    fbb_.AddElement<uint8_t>(Login::VT_HOST, host, 0);
  }
  void add_force(bool force) {
    fbb_.AddElement<uint8_t>(Login::VT_FORCE, static_cast<uint8_t>(force), 0);
  }
  void add_process_world(::flatbuffers::Offset<nullable::nullable_uint> process_world) {
    fbb_.AddOffset(Login::VT_PROCESS_WORLD, process_world);
  }
  explicit LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Login> CreateLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t world = 0,
    uint32_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint8_t host = 0,
    bool force = false,
    ::flatbuffers::Offset<nullable::nullable_uint> process_world = 0) {
  LoginBuilder builder_(_fbb);
  builder_.add_process_world(process_world);
  builder_.add_name(name);
  builder_.add_uid(uid);
  builder_.add_world(world);
  builder_.add_force(force);
  builder_.add_host(host);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Login> CreateLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t world = 0,
    uint32_t uid = 0,
    const char *name = nullptr,
    uint8_t host = 0,
    bool force = false,
    ::flatbuffers::Offset<nullable::nullable_uint> process_world = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return fb::protocol::internal::request::raw::CreateLogin(
      _fbb,
      world,
      uid,
      name__,
      host,
      force,
      process_world);
}

inline const fb::protocol::internal::request::raw::Login *GetLogin(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::Login>(buf);
}

inline const fb::protocol::internal::request::raw::Login *GetSizePrefixedLogin(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::Login>(buf);
}

inline bool VerifyLoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::Login>(nullptr);
}

inline bool VerifySizePrefixedLoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::Login>(nullptr);
}

inline void FinishLoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::Login> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::Login> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTLOGIN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
