// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTCREATECLAN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTCREATECLAN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct CreateClan;
struct CreateClanBuilder;

struct CreateClan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CreateClanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SECTION = 4,
    VT_HOST = 6,
    VT_MASTER = 8,
    VT_NAME = 10
  };
  const ::flatbuffers::String *section() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SECTION);
  }
  uint32_t host() const {
    return GetField<uint32_t>(VT_HOST, 0);
  }
  uint32_t master() const {
    return GetField<uint32_t>(VT_MASTER, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SECTION) &&
           verifier.VerifyString(section()) &&
           VerifyField<uint32_t>(verifier, VT_HOST, 4) &&
           VerifyField<uint32_t>(verifier, VT_MASTER, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct CreateClanBuilder {
  typedef CreateClan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_section(::flatbuffers::Offset<::flatbuffers::String> section) {
    fbb_.AddOffset(CreateClan::VT_SECTION, section);
  }
  void add_host(uint32_t host) {
    fbb_.AddElement<uint32_t>(CreateClan::VT_HOST, host, 0);
  }
  void add_master(uint32_t master) {
    fbb_.AddElement<uint32_t>(CreateClan::VT_MASTER, master, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(CreateClan::VT_NAME, name);
  }
  explicit CreateClanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CreateClan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CreateClan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CreateClan> CreateCreateClan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> section = 0,
    uint32_t host = 0,
    uint32_t master = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  CreateClanBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_master(master);
  builder_.add_host(host);
  builder_.add_section(section);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CreateClan> CreateCreateClanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *section = nullptr,
    uint32_t host = 0,
    uint32_t master = 0,
    const char *name = nullptr) {
  auto section__ = section ? _fbb.CreateString(section) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return fb::protocol::internal::request::raw::CreateCreateClan(
      _fbb,
      section__,
      host,
      master,
      name__);
}

inline const fb::protocol::internal::request::raw::CreateClan *GetCreateClan(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::CreateClan>(buf);
}

inline const fb::protocol::internal::request::raw::CreateClan *GetSizePrefixedCreateClan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::CreateClan>(buf);
}

inline bool VerifyCreateClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::CreateClan>(nullptr);
}

inline bool VerifySizePrefixedCreateClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::CreateClan>(nullptr);
}

inline void FinishCreateClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::CreateClan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCreateClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::CreateClan> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTCREATECLAN_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
