// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESHUTDOWN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESHUTDOWN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct Shutdown;
struct ShutdownBuilder;

struct Shutdown FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ShutdownBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ShutdownBuilder {
  typedef Shutdown Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ShutdownBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Shutdown> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Shutdown>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Shutdown> CreateShutdown(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ShutdownBuilder builder_(_fbb);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::Shutdown *GetShutdown(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::Shutdown>(buf);
}

inline const fb::protocol::internal::response::raw::Shutdown *GetSizePrefixedShutdown(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::Shutdown>(buf);
}

inline bool VerifyShutdownBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::Shutdown>(nullptr);
}

inline bool VerifySizePrefixedShutdownBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::Shutdown>(nullptr);
}

inline void FinishShutdownBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::Shutdown> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedShutdownBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::Shutdown> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESHUTDOWN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
