// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTOPSNOTIFY_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTOPSNOTIFY_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct OpsNotify;
struct OpsNotifyBuilder;

struct OpsNotify FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OpsNotifyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTION = 4,
    VT_SOURCE = 6,
    VT_ACTOR = 8,
    VT_TARGET = 10,
    VT_WORLD = 12,
    VT_DETAIL = 14
  };
  const ::flatbuffers::String *action() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTION);
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  const ::flatbuffers::String *actor() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACTOR);
  }
  const ::flatbuffers::String *target() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET);
  }
  uint32_t world() const {
    return GetField<uint32_t>(VT_WORLD, 0);
  }
  const ::flatbuffers::String *detail() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DETAIL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTION) &&
           verifier.VerifyString(action()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           VerifyOffset(verifier, VT_ACTOR) &&
           verifier.VerifyString(actor()) &&
           VerifyOffset(verifier, VT_TARGET) &&
           verifier.VerifyString(target()) &&
           VerifyField<uint32_t>(verifier, VT_WORLD, 4) &&
           VerifyOffset(verifier, VT_DETAIL) &&
           verifier.VerifyString(detail()) &&
           verifier.EndTable();
  }
};

struct OpsNotifyBuilder {
  typedef OpsNotify Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_action(::flatbuffers::Offset<::flatbuffers::String> action) {
    fbb_.AddOffset(OpsNotify::VT_ACTION, action);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(OpsNotify::VT_SOURCE, source);
  }
  void add_actor(::flatbuffers::Offset<::flatbuffers::String> actor) {
    fbb_.AddOffset(OpsNotify::VT_ACTOR, actor);
  }
  void add_target(::flatbuffers::Offset<::flatbuffers::String> target) {
    fbb_.AddOffset(OpsNotify::VT_TARGET, target);
  }
  void add_world(uint32_t world) {
    fbb_.AddElement<uint32_t>(OpsNotify::VT_WORLD, world, 0);
  }
  void add_detail(::flatbuffers::Offset<::flatbuffers::String> detail) {
    fbb_.AddOffset(OpsNotify::VT_DETAIL, detail);
  }
  explicit OpsNotifyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OpsNotify> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OpsNotify>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OpsNotify> CreateOpsNotify(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> action = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0,
    ::flatbuffers::Offset<::flatbuffers::String> actor = 0,
    ::flatbuffers::Offset<::flatbuffers::String> target = 0,
    uint32_t world = 0,
    ::flatbuffers::Offset<::flatbuffers::String> detail = 0) {
  OpsNotifyBuilder builder_(_fbb);
  builder_.add_detail(detail);
  builder_.add_world(world);
  builder_.add_target(target);
  builder_.add_actor(actor);
  builder_.add_source(source);
  builder_.add_action(action);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<OpsNotify> CreateOpsNotifyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *action = nullptr,
    const char *source = nullptr,
    const char *actor = nullptr,
    const char *target = nullptr,
    uint32_t world = 0,
    const char *detail = nullptr) {
  auto action__ = action ? _fbb.CreateString(action) : 0;
  auto source__ = source ? _fbb.CreateString(source) : 0;
  auto actor__ = actor ? _fbb.CreateString(actor) : 0;
  auto target__ = target ? _fbb.CreateString(target) : 0;
  auto detail__ = detail ? _fbb.CreateString(detail) : 0;
  return fb::protocol::internal::request::raw::CreateOpsNotify(
      _fbb,
      action__,
      source__,
      actor__,
      target__,
      world,
      detail__);
}

inline const fb::protocol::internal::request::raw::OpsNotify *GetOpsNotify(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::OpsNotify>(buf);
}

inline const fb::protocol::internal::request::raw::OpsNotify *GetSizePrefixedOpsNotify(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::OpsNotify>(buf);
}

inline bool VerifyOpsNotifyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::OpsNotify>(nullptr);
}

inline bool VerifySizePrefixedOpsNotifyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::OpsNotify>(nullptr);
}

inline void FinishOpsNotifyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::OpsNotify> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOpsNotifyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::OpsNotify> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTOPSNOTIFY_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
