// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMIMICRY_FB_PROTOCOL_INTERNAL_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMIMICRY_FB_PROTOCOL_INTERNAL_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "nullable_ubyte_generated.h"
#include "nullable_ushort_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace raw {

struct Mimicry;
struct MimicryBuilder;

struct Mimicry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MimicryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GENDER = 4,
    VT_STATE = 6,
    VT_HAIR = 8,
    VT_HAIR_COLOR = 10,
    VT_WEAPON = 12,
    VT_WEAPON_COLOR = 14,
    VT_ARMOR = 16,
    VT_ARMOR_COLOR = 18,
    VT_SHIELD = 20,
    VT_SHIELD_COLOR = 22,
    VT_DISGUISE = 24
  };
  uint8_t gender() const {
    return GetField<uint8_t>(VT_GENDER, 0);
  }
  const nullable::nullable_ubyte *state() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_STATE);
  }
  uint16_t hair() const {
    return GetField<uint16_t>(VT_HAIR, 0);
  }
  const nullable::nullable_ubyte *hair_color() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_HAIR_COLOR);
  }
  const nullable::nullable_ushort *weapon() const {
    return GetPointer<const nullable::nullable_ushort *>(VT_WEAPON);
  }
  const nullable::nullable_ubyte *weapon_color() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_WEAPON_COLOR);
  }
  const nullable::nullable_ubyte *armor() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_ARMOR);
  }
  const nullable::nullable_ubyte *armor_color() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_ARMOR_COLOR);
  }
  const nullable::nullable_ubyte *shield() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_SHIELD);
  }
  const nullable::nullable_ubyte *shield_color() const {
    return GetPointer<const nullable::nullable_ubyte *>(VT_SHIELD_COLOR);
  }
  const nullable::nullable_ushort *disguise() const {
    return GetPointer<const nullable::nullable_ushort *>(VT_DISGUISE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GENDER, 1) &&
           VerifyOffset(verifier, VT_STATE) &&
           verifier.VerifyTable(state()) &&
           VerifyField<uint16_t>(verifier, VT_HAIR, 2) &&
           VerifyOffset(verifier, VT_HAIR_COLOR) &&
           verifier.VerifyTable(hair_color()) &&
           VerifyOffset(verifier, VT_WEAPON) &&
           verifier.VerifyTable(weapon()) &&
           VerifyOffset(verifier, VT_WEAPON_COLOR) &&
           verifier.VerifyTable(weapon_color()) &&
           VerifyOffset(verifier, VT_ARMOR) &&
           verifier.VerifyTable(armor()) &&
           VerifyOffset(verifier, VT_ARMOR_COLOR) &&
           verifier.VerifyTable(armor_color()) &&
           VerifyOffset(verifier, VT_SHIELD) &&
           verifier.VerifyTable(shield()) &&
           VerifyOffset(verifier, VT_SHIELD_COLOR) &&
           verifier.VerifyTable(shield_color()) &&
           VerifyOffset(verifier, VT_DISGUISE) &&
           verifier.VerifyTable(disguise()) &&
           verifier.EndTable();
  }
};

struct MimicryBuilder {
  typedef Mimicry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gender(uint8_t gender) {
    fbb_.AddElement<uint8_t>(Mimicry::VT_GENDER, gender, 0);
  }
  void add_state(::flatbuffers::Offset<nullable::nullable_ubyte> state) {
    fbb_.AddOffset(Mimicry::VT_STATE, state);
  }
  void add_hair(uint16_t hair) {
    fbb_.AddElement<uint16_t>(Mimicry::VT_HAIR, hair, 0);
  }
  void add_hair_color(::flatbuffers::Offset<nullable::nullable_ubyte> hair_color) {
    fbb_.AddOffset(Mimicry::VT_HAIR_COLOR, hair_color);
  }
  void add_weapon(::flatbuffers::Offset<nullable::nullable_ushort> weapon) {
    fbb_.AddOffset(Mimicry::VT_WEAPON, weapon);
  }
  void add_weapon_color(::flatbuffers::Offset<nullable::nullable_ubyte> weapon_color) {
    fbb_.AddOffset(Mimicry::VT_WEAPON_COLOR, weapon_color);
  }
  void add_armor(::flatbuffers::Offset<nullable::nullable_ubyte> armor) {
    fbb_.AddOffset(Mimicry::VT_ARMOR, armor);
  }
  void add_armor_color(::flatbuffers::Offset<nullable::nullable_ubyte> armor_color) {
    fbb_.AddOffset(Mimicry::VT_ARMOR_COLOR, armor_color);
  }
  void add_shield(::flatbuffers::Offset<nullable::nullable_ubyte> shield) {
    fbb_.AddOffset(Mimicry::VT_SHIELD, shield);
  }
  void add_shield_color(::flatbuffers::Offset<nullable::nullable_ubyte> shield_color) {
    fbb_.AddOffset(Mimicry::VT_SHIELD_COLOR, shield_color);
  }
  void add_disguise(::flatbuffers::Offset<nullable::nullable_ushort> disguise) {
    fbb_.AddOffset(Mimicry::VT_DISGUISE, disguise);
  }
  explicit MimicryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mimicry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mimicry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mimicry> CreateMimicry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t gender = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> state = 0,
    uint16_t hair = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> hair_color = 0,
    ::flatbuffers::Offset<nullable::nullable_ushort> weapon = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> weapon_color = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> armor = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> armor_color = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> shield = 0,
    ::flatbuffers::Offset<nullable::nullable_ubyte> shield_color = 0,
    ::flatbuffers::Offset<nullable::nullable_ushort> disguise = 0) {
  MimicryBuilder builder_(_fbb);
  builder_.add_disguise(disguise);
  builder_.add_shield_color(shield_color);
  builder_.add_shield(shield);
  builder_.add_armor_color(armor_color);
  builder_.add_armor(armor);
  builder_.add_weapon_color(weapon_color);
  builder_.add_weapon(weapon);
  builder_.add_hair_color(hair_color);
  builder_.add_state(state);
  builder_.add_hair(hair);
  builder_.add_gender(gender);
  return builder_.Finish();
}

inline const fb::protocol::internal::raw::Mimicry *GetMimicry(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::raw::Mimicry>(buf);
}

inline const fb::protocol::internal::raw::Mimicry *GetSizePrefixedMimicry(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::raw::Mimicry>(buf);
}

inline bool VerifyMimicryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::raw::Mimicry>(nullptr);
}

inline bool VerifySizePrefixedMimicryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::raw::Mimicry>(nullptr);
}

inline void FinishMimicryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::Mimicry> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMimicryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::Mimicry> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMIMICRY_FB_PROTOCOL_INTERNAL_RAW_H_
