// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESTARTMAINTENANCE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESTARTMAINTENANCE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct StartMaintenance;
struct StartMaintenanceBuilder;

struct StartMaintenance FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartMaintenanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE = 4,
    VT_END_TIME = 6
  };
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  const ::flatbuffers::String *end_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT_END_TIME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_END_TIME) &&
           verifier.VerifyString(end_time()) &&
           verifier.EndTable();
  }
};

struct StartMaintenanceBuilder {
  typedef StartMaintenance Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(StartMaintenance::VT_MESSAGE, message);
  }
  void add_end_time(::flatbuffers::Offset<::flatbuffers::String> end_time) {
    fbb_.AddOffset(StartMaintenance::VT_END_TIME, end_time);
  }
  explicit StartMaintenanceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartMaintenance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartMaintenance>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartMaintenance> CreateStartMaintenance(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0,
    ::flatbuffers::Offset<::flatbuffers::String> end_time = 0) {
  StartMaintenanceBuilder builder_(_fbb);
  builder_.add_end_time(end_time);
  builder_.add_message(message);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StartMaintenance> CreateStartMaintenanceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *message = nullptr,
    const char *end_time = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto end_time__ = end_time ? _fbb.CreateString(end_time) : 0;
  return fb::protocol::internal::response::raw::CreateStartMaintenance(
      _fbb,
      message__,
      end_time__);
}

inline const fb::protocol::internal::response::raw::StartMaintenance *GetStartMaintenance(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::StartMaintenance>(buf);
}

inline const fb::protocol::internal::response::raw::StartMaintenance *GetSizePrefixedStartMaintenance(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::StartMaintenance>(buf);
}

inline bool VerifyStartMaintenanceBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::StartMaintenance>(nullptr);
}

inline bool VerifySizePrefixedStartMaintenanceBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::StartMaintenance>(nullptr);
}

inline void FinishStartMaintenanceBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::StartMaintenance> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStartMaintenanceBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::StartMaintenance> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESTARTMAINTENANCE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
