// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSEDECLINE_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSEDECLINE_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace matchmaking {
namespace response {
namespace raw {

struct Decline;
struct DeclineBuilder;

struct Decline FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeclineBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ERROR = 4
  };
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct DeclineBuilder {
  typedef Decline Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(Decline::VT_ERROR, error, 0);
  }
  explicit DeclineBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Decline> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Decline>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Decline> CreateDecline(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t error = 0) {
  DeclineBuilder builder_(_fbb);
  builder_.add_error(error);
  return builder_.Finish();
}

inline const fb::protocol::matchmaking::response::raw::Decline *GetDecline(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::matchmaking::response::raw::Decline>(buf);
}

inline const fb::protocol::matchmaking::response::raw::Decline *GetSizePrefixedDecline(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::matchmaking::response::raw::Decline>(buf);
}

inline bool VerifyDeclineBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::matchmaking::response::raw::Decline>(nullptr);
}

inline bool VerifySizePrefixedDeclineBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::matchmaking::response::raw::Decline>(nullptr);
}

inline void FinishDeclineBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::response::raw::Decline> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDeclineBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::response::raw::Decline> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace matchmaking
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSEDECLINE_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_
