// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEPENDINGTRANSACTION_FB_PROTOCOL_MARKETPLACE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEPENDINGTRANSACTION_FB_PROTOCOL_MARKETPLACE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace marketplace {
namespace raw {

struct PendingTransaction;
struct PendingTransactionBuilder;

struct PendingTransaction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PendingTransactionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_LISTING_ID = 6,
    VT_BUYER_ID = 8,
    VT_SELLER_ID = 10,
    VT_ITEM_MODEL = 12,
    VT_ITEM_COUNT = 14,
    VT_PRICE = 16,
    VT_SELLER_REVENUE = 18,
    VT_CREATED_DATE = 20
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  uint64_t listing_id() const {
    return GetField<uint64_t>(VT_LISTING_ID, 0);
  }
  uint32_t buyer_id() const {
    return GetField<uint32_t>(VT_BUYER_ID, 0);
  }
  uint32_t seller_id() const {
    return GetField<uint32_t>(VT_SELLER_ID, 0);
  }
  uint32_t item_model() const {
    return GetField<uint32_t>(VT_ITEM_MODEL, 0);
  }
  uint16_t item_count() const {
    return GetField<uint16_t>(VT_ITEM_COUNT, 0);
  }
  uint32_t price() const {
    return GetField<uint32_t>(VT_PRICE, 0);
  }
  uint32_t seller_revenue() const {
    return GetField<uint32_t>(VT_SELLER_REVENUE, 0);
  }
  const ::flatbuffers::String *created_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_DATE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_LISTING_ID, 8) &&
           VerifyField<uint32_t>(verifier, VT_BUYER_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SELLER_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ITEM_MODEL, 4) &&
           VerifyField<uint16_t>(verifier, VT_ITEM_COUNT, 2) &&
           VerifyField<uint32_t>(verifier, VT_PRICE, 4) &&
           VerifyField<uint32_t>(verifier, VT_SELLER_REVENUE, 4) &&
           VerifyOffset(verifier, VT_CREATED_DATE) &&
           verifier.VerifyString(created_date()) &&
           verifier.EndTable();
  }
};

struct PendingTransactionBuilder {
  typedef PendingTransaction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(PendingTransaction::VT_ID, id, 0);
  }
  void add_listing_id(uint64_t listing_id) {
    fbb_.AddElement<uint64_t>(PendingTransaction::VT_LISTING_ID, listing_id, 0);
  }
  void add_buyer_id(uint32_t buyer_id) {
    fbb_.AddElement<uint32_t>(PendingTransaction::VT_BUYER_ID, buyer_id, 0);
  }
  void add_seller_id(uint32_t seller_id) {
    fbb_.AddElement<uint32_t>(PendingTransaction::VT_SELLER_ID, seller_id, 0);
  }
  void add_item_model(uint32_t item_model) {
    fbb_.AddElement<uint32_t>(PendingTransaction::VT_ITEM_MODEL, item_model, 0);
  }
  void add_item_count(uint16_t item_count) {
    fbb_.AddElement<uint16_t>(PendingTransaction::VT_ITEM_COUNT, item_count, 0);
  }
  void add_price(uint32_t price) {
    fbb_.AddElement<uint32_t>(PendingTransaction::VT_PRICE, price, 0);
  }
  void add_seller_revenue(uint32_t seller_revenue) {
    fbb_.AddElement<uint32_t>(PendingTransaction::VT_SELLER_REVENUE, seller_revenue, 0);
  }
  void add_created_date(::flatbuffers::Offset<::flatbuffers::String> created_date) {
    fbb_.AddOffset(PendingTransaction::VT_CREATED_DATE, created_date);
  }
  explicit PendingTransactionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PendingTransaction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PendingTransaction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PendingTransaction> CreatePendingTransaction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t listing_id = 0,
    uint32_t buyer_id = 0,
    uint32_t seller_id = 0,
    uint32_t item_model = 0,
    uint16_t item_count = 0,
    uint32_t price = 0,
    uint32_t seller_revenue = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_date = 0) {
  PendingTransactionBuilder builder_(_fbb);
  builder_.add_listing_id(listing_id);
  builder_.add_id(id);
  builder_.add_created_date(created_date);
  builder_.add_seller_revenue(seller_revenue);
  builder_.add_price(price);
  builder_.add_item_model(item_model);
  builder_.add_seller_id(seller_id);
  builder_.add_buyer_id(buyer_id);
  builder_.add_item_count(item_count);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PendingTransaction> CreatePendingTransactionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    uint64_t listing_id = 0,
    uint32_t buyer_id = 0,
    uint32_t seller_id = 0,
    uint32_t item_model = 0,
    uint16_t item_count = 0,
    uint32_t price = 0,
    uint32_t seller_revenue = 0,
    const char *created_date = nullptr) {
  auto created_date__ = created_date ? _fbb.CreateString(created_date) : 0;
  return fb::protocol::marketplace::raw::CreatePendingTransaction(
      _fbb,
      id,
      listing_id,
      buyer_id,
      seller_id,
      item_model,
      item_count,
      price,
      seller_revenue,
      created_date__);
}

inline const fb::protocol::marketplace::raw::PendingTransaction *GetPendingTransaction(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::marketplace::raw::PendingTransaction>(buf);
}

inline const fb::protocol::marketplace::raw::PendingTransaction *GetSizePrefixedPendingTransaction(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::marketplace::raw::PendingTransaction>(buf);
}

inline bool VerifyPendingTransactionBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::marketplace::raw::PendingTransaction>(nullptr);
}

inline bool VerifySizePrefixedPendingTransactionBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::marketplace::raw::PendingTransaction>(nullptr);
}

inline void FinishPendingTransactionBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::PendingTransaction> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPendingTransactionBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::PendingTransaction> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace marketplace
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEPENDINGTRANSACTION_FB_PROTOCOL_MARKETPLACE_RAW_H_
