// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.characterref_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct DestroyClan;
struct DestroyClanBuilder;

struct DestroyClan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DestroyClanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HOST = 4,
    VT_CLAN_ID = 6,
    VT_CLAN_NAME = 8,
    VT_ACTOR = 10,
    VT_ERROR = 12
  };
  uint32_t host() const {
    return GetField<uint32_t>(VT_HOST, 0);
  }
  uint32_t clan_id() const {
    return GetField<uint32_t>(VT_CLAN_ID, 0);
  }
  const ::flatbuffers::String *clan_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CLAN_NAME);
  }
  const fb::protocol::internal::raw::CharacterRef *actor() const {
    return GetPointer<const fb::protocol::internal::raw::CharacterRef *>(VT_ACTOR);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_HOST, 4) &&
           VerifyField<uint32_t>(verifier, VT_CLAN_ID, 4) &&
           VerifyOffset(verifier, VT_CLAN_NAME) &&
           verifier.VerifyString(clan_name()) &&
           VerifyOffset(verifier, VT_ACTOR) &&
           verifier.VerifyTable(actor()) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct DestroyClanBuilder {
  typedef DestroyClan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_host(uint32_t host) {
    fbb_.AddElement<uint32_t>(DestroyClan::VT_HOST, host, 0);
  }
  void add_clan_id(uint32_t clan_id) {
    fbb_.AddElement<uint32_t>(DestroyClan::VT_CLAN_ID, clan_id, 0);
  }
  void add_clan_name(::flatbuffers::Offset<::flatbuffers::String> clan_name) {
    fbb_.AddOffset(DestroyClan::VT_CLAN_NAME, clan_name);
  }
  void add_actor(::flatbuffers::Offset<fb::protocol::internal::raw::CharacterRef> actor) {
    fbb_.AddOffset(DestroyClan::VT_ACTOR, actor);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(DestroyClan::VT_ERROR, error, 0);
  }
  explicit DestroyClanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DestroyClan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DestroyClan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DestroyClan> CreateDestroyClan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t host = 0,
    uint32_t clan_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> clan_name = 0,
    ::flatbuffers::Offset<fb::protocol::internal::raw::CharacterRef> actor = 0,
    uint32_t error = 0) {
  DestroyClanBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_actor(actor);
  builder_.add_clan_name(clan_name);
  builder_.add_clan_id(clan_id);
  builder_.add_host(host);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DestroyClan> CreateDestroyClanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t host = 0,
    uint32_t clan_id = 0,
    const char *clan_name = nullptr,
    ::flatbuffers::Offset<fb::protocol::internal::raw::CharacterRef> actor = 0,
    uint32_t error = 0) {
  auto clan_name__ = clan_name ? _fbb.CreateString(clan_name) : 0;
  return fb::protocol::internal::response::raw::CreateDestroyClan(
      _fbb,
      host,
      clan_id,
      clan_name__,
      actor,
      error);
}

inline const fb::protocol::internal::response::raw::DestroyClan *GetDestroyClan(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::DestroyClan>(buf);
}

inline const fb::protocol::internal::response::raw::DestroyClan *GetSizePrefixedDestroyClan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::DestroyClan>(buf);
}

inline bool VerifyDestroyClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::DestroyClan>(nullptr);
}

inline bool VerifySizePrefixedDestroyClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::DestroyClan>(nullptr);
}

inline void FinishDestroyClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::DestroyClan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDestroyClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::DestroyClan> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEDESTROYCLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
