// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTTRANSFER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTTRANSFER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.service_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct Transfer;
struct TransferBuilder;

struct Transfer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVICE = 4,
    VT_ID = 6,
    VT_NAME = 8,
    VT_FORCE_SHUTDOWN = 10
  };
  fb::protocol::internal::raw::Service service() const {
    return static_cast<fb::protocol::internal::raw::Service>(GetField<int8_t>(VT_SERVICE, 0));
  }
  uint8_t id() const {
    return GetField<uint8_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool force_shutdown() const {
    return GetField<uint8_t>(VT_FORCE_SHUTDOWN, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SERVICE, 1) &&
           VerifyField<uint8_t>(verifier, VT_ID, 1) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint8_t>(verifier, VT_FORCE_SHUTDOWN, 1) &&
           verifier.EndTable();
  }
};

struct TransferBuilder {
  typedef Transfer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_service(fb::protocol::internal::raw::Service service) {
    fbb_.AddElement<int8_t>(Transfer::VT_SERVICE, static_cast<int8_t>(service), 0);
  }
  void add_id(uint8_t id) {
    fbb_.AddElement<uint8_t>(Transfer::VT_ID, id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Transfer::VT_NAME, name);
  }
  void add_force_shutdown(bool force_shutdown) {
    fbb_.AddElement<uint8_t>(Transfer::VT_FORCE_SHUTDOWN, static_cast<uint8_t>(force_shutdown), 0);
  }
  explicit TransferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transfer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transfer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Transfer> CreateTransfer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    fb::protocol::internal::raw::Service service = fb::protocol::internal::raw::Service_Gateway,
    uint8_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    bool force_shutdown = false) {
  TransferBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_force_shutdown(force_shutdown);
  builder_.add_id(id);
  builder_.add_service(service);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Transfer> CreateTransferDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    fb::protocol::internal::raw::Service service = fb::protocol::internal::raw::Service_Gateway,
    uint8_t id = 0,
    const char *name = nullptr,
    bool force_shutdown = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return fb::protocol::internal::request::raw::CreateTransfer(
      _fbb,
      service,
      id,
      name__,
      force_shutdown);
}

inline const fb::protocol::internal::request::raw::Transfer *GetTransfer(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::Transfer>(buf);
}

inline const fb::protocol::internal::request::raw::Transfer *GetSizePrefixedTransfer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::Transfer>(buf);
}

inline bool VerifyTransferBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::Transfer>(nullptr);
}

inline bool VerifySizePrefixedTransferBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::Transfer>(nullptr);
}

inline void FinishTransferBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::Transfer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTransferBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::Transfer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTTRANSFER_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
