// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTCANCEL_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTCANCEL_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace marketplace {
namespace request {
namespace raw {

struct Cancel;
struct CancelBuilder;

struct Cancel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CancelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER_ID = 4,
    VT_LISTING_ID = 6
  };
  uint32_t character_id() const {
    return GetField<uint32_t>(VT_CHARACTER_ID, 0);
  }
  const ::flatbuffers::String *listing_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LISTING_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CHARACTER_ID, 4) &&
           VerifyOffset(verifier, VT_LISTING_ID) &&
           verifier.VerifyString(listing_id()) &&
           verifier.EndTable();
  }
};

struct CancelBuilder {
  typedef Cancel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_character_id(uint32_t character_id) {
    fbb_.AddElement<uint32_t>(Cancel::VT_CHARACTER_ID, character_id, 0);
  }
  void add_listing_id(::flatbuffers::Offset<::flatbuffers::String> listing_id) {
    fbb_.AddOffset(Cancel::VT_LISTING_ID, listing_id);
  }
  explicit CancelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Cancel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Cancel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Cancel> CreateCancel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t character_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> listing_id = 0) {
  CancelBuilder builder_(_fbb);
  builder_.add_listing_id(listing_id);
  builder_.add_character_id(character_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Cancel> CreateCancelDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t character_id = 0,
    const char *listing_id = nullptr) {
  auto listing_id__ = listing_id ? _fbb.CreateString(listing_id) : 0;
  return fb::protocol::marketplace::request::raw::CreateCancel(
      _fbb,
      character_id,
      listing_id__);
}

inline const fb::protocol::marketplace::request::raw::Cancel *GetCancel(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::marketplace::request::raw::Cancel>(buf);
}

inline const fb::protocol::marketplace::request::raw::Cancel *GetSizePrefixedCancel(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::marketplace::request::raw::Cancel>(buf);
}

inline bool VerifyCancelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::marketplace::request::raw::Cancel>(nullptr);
}

inline bool VerifySizePrefixedCancelBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::marketplace::request::raw::Cancel>(nullptr);
}

inline void FinishCancelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::Cancel> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCancelBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::Cancel> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace marketplace
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTCANCEL_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
