// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTRELOADTABLES_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTRELOADTABLES_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct ReloadTables;
struct ReloadTablesBuilder;

struct ReloadTables FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReloadTablesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD = 4,
    VT_URL = 6,
    VT_TABLE_NAMES = 8
  };
  uint32_t world() const {
    return GetField<uint32_t>(VT_WORLD, 0);
  }
  const ::flatbuffers::String *url() const {
    return GetPointer<const ::flatbuffers::String *>(VT_URL);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *table_names() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TABLE_NAMES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WORLD, 4) &&
           VerifyOffset(verifier, VT_URL) &&
           verifier.VerifyString(url()) &&
           VerifyOffset(verifier, VT_TABLE_NAMES) &&
           verifier.VerifyVector(table_names()) &&
           verifier.VerifyVectorOfStrings(table_names()) &&
           verifier.EndTable();
  }
};

struct ReloadTablesBuilder {
  typedef ReloadTables Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world(uint32_t world) {
    fbb_.AddElement<uint32_t>(ReloadTables::VT_WORLD, world, 0);
  }
  void add_url(::flatbuffers::Offset<::flatbuffers::String> url) {
    fbb_.AddOffset(ReloadTables::VT_URL, url);
  }
  void add_table_names(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> table_names) {
    fbb_.AddOffset(ReloadTables::VT_TABLE_NAMES, table_names);
  }
  explicit ReloadTablesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReloadTables> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReloadTables>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReloadTables> CreateReloadTables(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t world = 0,
    ::flatbuffers::Offset<::flatbuffers::String> url = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> table_names = 0) {
  ReloadTablesBuilder builder_(_fbb);
  builder_.add_table_names(table_names);
  builder_.add_url(url);
  builder_.add_world(world);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReloadTables> CreateReloadTablesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t world = 0,
    const char *url = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *table_names = nullptr) {
  auto url__ = url ? _fbb.CreateString(url) : 0;
  auto table_names__ = table_names ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*table_names) : 0;
  return fb::protocol::internal::request::raw::CreateReloadTables(
      _fbb,
      world,
      url__,
      table_names__);
}

inline const fb::protocol::internal::request::raw::ReloadTables *GetReloadTables(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::ReloadTables>(buf);
}

inline const fb::protocol::internal::request::raw::ReloadTables *GetSizePrefixedReloadTables(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::ReloadTables>(buf);
}

inline bool VerifyReloadTablesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::ReloadTables>(nullptr);
}

inline bool VerifySizePrefixedReloadTablesBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::ReloadTables>(nullptr);
}

inline void FinishReloadTablesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::ReloadTables> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedReloadTablesBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::ReloadTables> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTRELOADTABLES_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
