// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETGROUP_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETGROUP_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.group_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct GetGroup;
struct GetGroupBuilder;

struct GetGroup FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUP = 4,
    VT_ERROR = 6
  };
  const fb::protocol::internal::raw::Group *group() const {
    return GetPointer<const fb::protocol::internal::raw::Group *>(VT_GROUP);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GROUP) &&
           verifier.VerifyTable(group()) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct GetGroupBuilder {
  typedef GetGroup Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_group(::flatbuffers::Offset<fb::protocol::internal::raw::Group> group) {
    fbb_.AddOffset(GetGroup::VT_GROUP, group);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(GetGroup::VT_ERROR, error, 0);
  }
  explicit GetGroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetGroup>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetGroup> CreateGetGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::Group> group = 0,
    uint32_t error = 0) {
  GetGroupBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_group(group);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::GetGroup *GetGetGroup(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::GetGroup>(buf);
}

inline const fb::protocol::internal::response::raw::GetGroup *GetSizePrefixedGetGroup(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::GetGroup>(buf);
}

inline bool VerifyGetGroupBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::GetGroup>(nullptr);
}

inline bool VerifySizePrefixedGetGroupBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::GetGroup>(nullptr);
}

inline void FinishGetGroupBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::GetGroup> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGetGroupBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::GetGroup> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETGROUP_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
