// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSECHANGECLANROLE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSECHANGECLANROLE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct ChangeClanRole;
struct ChangeClanRoleBuilder;

struct ChangeClanRole FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChangeClanRoleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HOST = 4,
    VT_CLAN = 6,
    VT_CHANGER_UID = 8,
    VT_CHANGER_NAME = 10,
    VT_TARGET_UID = 12,
    VT_TARGET_NAME = 14,
    VT_OLD_ROLE = 16,
    VT_NEW_ROLE = 18,
    VT_ERROR = 20
  };
  uint32_t host() const {
    return GetField<uint32_t>(VT_HOST, 0);
  }
  uint32_t clan() const {
    return GetField<uint32_t>(VT_CLAN, 0);
  }
  uint32_t changer_uid() const {
    return GetField<uint32_t>(VT_CHANGER_UID, 0);
  }
  const ::flatbuffers::String *changer_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHANGER_NAME);
  }
  uint32_t target_uid() const {
    return GetField<uint32_t>(VT_TARGET_UID, 0);
  }
  const ::flatbuffers::String *target_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET_NAME);
  }
  uint32_t old_role() const {
    return GetField<uint32_t>(VT_OLD_ROLE, 0);
  }
  uint32_t new_role() const {
    return GetField<uint32_t>(VT_NEW_ROLE, 0);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_HOST, 4) &&
           VerifyField<uint32_t>(verifier, VT_CLAN, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHANGER_UID, 4) &&
           VerifyOffset(verifier, VT_CHANGER_NAME) &&
           verifier.VerifyString(changer_name()) &&
           VerifyField<uint32_t>(verifier, VT_TARGET_UID, 4) &&
           VerifyOffset(verifier, VT_TARGET_NAME) &&
           verifier.VerifyString(target_name()) &&
           VerifyField<uint32_t>(verifier, VT_OLD_ROLE, 4) &&
           VerifyField<uint32_t>(verifier, VT_NEW_ROLE, 4) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct ChangeClanRoleBuilder {
  typedef ChangeClanRole Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_host(uint32_t host) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_HOST, host, 0);
  }
  void add_clan(uint32_t clan) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_CLAN, clan, 0);
  }
  void add_changer_uid(uint32_t changer_uid) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_CHANGER_UID, changer_uid, 0);
  }
  void add_changer_name(::flatbuffers::Offset<::flatbuffers::String> changer_name) {
    fbb_.AddOffset(ChangeClanRole::VT_CHANGER_NAME, changer_name);
  }
  void add_target_uid(uint32_t target_uid) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_TARGET_UID, target_uid, 0);
  }
  void add_target_name(::flatbuffers::Offset<::flatbuffers::String> target_name) {
    fbb_.AddOffset(ChangeClanRole::VT_TARGET_NAME, target_name);
  }
  void add_old_role(uint32_t old_role) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_OLD_ROLE, old_role, 0);
  }
  void add_new_role(uint32_t new_role) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_NEW_ROLE, new_role, 0);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(ChangeClanRole::VT_ERROR, error, 0);
  }
  explicit ChangeClanRoleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ChangeClanRole> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ChangeClanRole>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ChangeClanRole> CreateChangeClanRole(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t host = 0,
    uint32_t clan = 0,
    uint32_t changer_uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> changer_name = 0,
    uint32_t target_uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> target_name = 0,
    uint32_t old_role = 0,
    uint32_t new_role = 0,
    uint32_t error = 0) {
  ChangeClanRoleBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_new_role(new_role);
  builder_.add_old_role(old_role);
  builder_.add_target_name(target_name);
  builder_.add_target_uid(target_uid);
  builder_.add_changer_name(changer_name);
  builder_.add_changer_uid(changer_uid);
  builder_.add_clan(clan);
  builder_.add_host(host);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ChangeClanRole> CreateChangeClanRoleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t host = 0,
    uint32_t clan = 0,
    uint32_t changer_uid = 0,
    const char *changer_name = nullptr,
    uint32_t target_uid = 0,
    const char *target_name = nullptr,
    uint32_t old_role = 0,
    uint32_t new_role = 0,
    uint32_t error = 0) {
  auto changer_name__ = changer_name ? _fbb.CreateString(changer_name) : 0;
  auto target_name__ = target_name ? _fbb.CreateString(target_name) : 0;
  return fb::protocol::internal::response::raw::CreateChangeClanRole(
      _fbb,
      host,
      clan,
      changer_uid,
      changer_name__,
      target_uid,
      target_name__,
      old_role,
      new_role,
      error);
}

inline const fb::protocol::internal::response::raw::ChangeClanRole *GetChangeClanRole(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::ChangeClanRole>(buf);
}

inline const fb::protocol::internal::response::raw::ChangeClanRole *GetSizePrefixedChangeClanRole(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::ChangeClanRole>(buf);
}

inline bool VerifyChangeClanRoleBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::ChangeClanRole>(nullptr);
}

inline bool VerifySizePrefixedChangeClanRoleBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::ChangeClanRole>(nullptr);
}

inline void FinishChangeClanRoleBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::ChangeClanRole> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedChangeClanRoleBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::ChangeClanRole> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSECHANGECLANROLE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
