// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLDBREQUESTACCOUNT_FB_PROTOCOL_DB_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLDBREQUESTACCOUNT_FB_PROTOCOL_DB_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace db {
namespace request {
namespace raw {

struct Account;
struct AccountBuilder;

struct Account FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AccountBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4
  };
  uint32_t uid() const {
    return GetField<uint32_t>(VT_UID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_UID, 4) &&
           verifier.EndTable();
  }
};

struct AccountBuilder {
  typedef Account Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(uint32_t uid) {
    fbb_.AddElement<uint32_t>(Account::VT_UID, uid, 0);
  }
  explicit AccountBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Account> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Account>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Account> CreateAccount(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t uid = 0) {
  AccountBuilder builder_(_fbb);
  builder_.add_uid(uid);
  return builder_.Finish();
}

inline const fb::protocol::db::request::raw::Account *GetAccount(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::db::request::raw::Account>(buf);
}

inline const fb::protocol::db::request::raw::Account *GetSizePrefixedAccount(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::db::request::raw::Account>(buf);
}

inline bool VerifyAccountBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::db::request::raw::Account>(nullptr);
}

inline bool VerifySizePrefixedAccountBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::db::request::raw::Account>(nullptr);
}

inline void FinishAccountBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::request::raw::Account> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAccountBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::request::raw::Account> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace db
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLDBREQUESTACCOUNT_FB_PROTOCOL_DB_REQUEST_RAW_H_
