// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACELISTING_FB_PROTOCOL_MARKETPLACE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACELISTING_FB_PROTOCOL_MARKETPLACE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.marketplace.item_generated.h"

namespace fb {
namespace protocol {
namespace marketplace {
namespace raw {

struct Listing;
struct ListingBuilder;

struct Listing FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ListingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_SELLER_ID = 6,
    VT_ITEM = 8,
    VT_PRICE = 10,
    VT_LISTING_FEE = 12,
    VT_TRANSACTION_FEE = 14,
    VT_EXPIRE_DATE = 16,
    VT_CREATED_DATE = 18
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  uint32_t seller_id() const {
    return GetField<uint32_t>(VT_SELLER_ID, 0);
  }
  const fb::protocol::marketplace::raw::Item *item() const {
    return GetPointer<const fb::protocol::marketplace::raw::Item *>(VT_ITEM);
  }
  uint32_t price() const {
    return GetField<uint32_t>(VT_PRICE, 0);
  }
  uint32_t listing_fee() const {
    return GetField<uint32_t>(VT_LISTING_FEE, 0);
  }
  uint32_t transaction_fee() const {
    return GetField<uint32_t>(VT_TRANSACTION_FEE, 0);
  }
  const ::flatbuffers::String *expire_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXPIRE_DATE);
  }
  const ::flatbuffers::String *created_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_DATE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint32_t>(verifier, VT_SELLER_ID, 4) &&
           VerifyOffset(verifier, VT_ITEM) &&
           verifier.VerifyTable(item()) &&
           VerifyField<uint32_t>(verifier, VT_PRICE, 4) &&
           VerifyField<uint32_t>(verifier, VT_LISTING_FEE, 4) &&
           VerifyField<uint32_t>(verifier, VT_TRANSACTION_FEE, 4) &&
           VerifyOffset(verifier, VT_EXPIRE_DATE) &&
           verifier.VerifyString(expire_date()) &&
           VerifyOffset(verifier, VT_CREATED_DATE) &&
           verifier.VerifyString(created_date()) &&
           verifier.EndTable();
  }
};

struct ListingBuilder {
  typedef Listing Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Listing::VT_ID, id);
  }
  void add_seller_id(uint32_t seller_id) {
    fbb_.AddElement<uint32_t>(Listing::VT_SELLER_ID, seller_id, 0);
  }
  void add_item(::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item) {
    fbb_.AddOffset(Listing::VT_ITEM, item);
  }
  void add_price(uint32_t price) {
    fbb_.AddElement<uint32_t>(Listing::VT_PRICE, price, 0);
  }
  void add_listing_fee(uint32_t listing_fee) {
    fbb_.AddElement<uint32_t>(Listing::VT_LISTING_FEE, listing_fee, 0);
  }
  void add_transaction_fee(uint32_t transaction_fee) {
    fbb_.AddElement<uint32_t>(Listing::VT_TRANSACTION_FEE, transaction_fee, 0);
  }
  void add_expire_date(::flatbuffers::Offset<::flatbuffers::String> expire_date) {
    fbb_.AddOffset(Listing::VT_EXPIRE_DATE, expire_date);
  }
  void add_created_date(::flatbuffers::Offset<::flatbuffers::String> created_date) {
    fbb_.AddOffset(Listing::VT_CREATED_DATE, created_date);
  }
  explicit ListingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Listing> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Listing>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Listing> CreateListing(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    uint32_t seller_id = 0,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item = 0,
    uint32_t price = 0,
    uint32_t listing_fee = 0,
    uint32_t transaction_fee = 0,
    ::flatbuffers::Offset<::flatbuffers::String> expire_date = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_date = 0) {
  ListingBuilder builder_(_fbb);
  builder_.add_created_date(created_date);
  builder_.add_expire_date(expire_date);
  builder_.add_transaction_fee(transaction_fee);
  builder_.add_listing_fee(listing_fee);
  builder_.add_price(price);
  builder_.add_item(item);
  builder_.add_seller_id(seller_id);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Listing> CreateListingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    uint32_t seller_id = 0,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item = 0,
    uint32_t price = 0,
    uint32_t listing_fee = 0,
    uint32_t transaction_fee = 0,
    const char *expire_date = nullptr,
    const char *created_date = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto expire_date__ = expire_date ? _fbb.CreateString(expire_date) : 0;
  auto created_date__ = created_date ? _fbb.CreateString(created_date) : 0;
  return fb::protocol::marketplace::raw::CreateListing(
      _fbb,
      id__,
      seller_id,
      item,
      price,
      listing_fee,
      transaction_fee,
      expire_date__,
      created_date__);
}

inline const fb::protocol::marketplace::raw::Listing *GetListing(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::marketplace::raw::Listing>(buf);
}

inline const fb::protocol::marketplace::raw::Listing *GetSizePrefixedListing(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::marketplace::raw::Listing>(buf);
}

inline bool VerifyListingBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::marketplace::raw::Listing>(nullptr);
}

inline bool VerifySizePrefixedListingBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::marketplace::raw::Listing>(nullptr);
}

inline void FinishListingBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Listing> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedListingBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Listing> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace marketplace
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACELISTING_FB_PROTOCOL_MARKETPLACE_RAW_H_
