// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMAILSUMMARY_FB_PROTOCOL_INTERNAL_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMAILSUMMARY_FB_PROTOCOL_INTERNAL_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace raw {

struct MailSummary;
struct MailSummaryBuilder;

struct MailSummary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MailSummaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_USER = 6,
    VT_SENDER = 8,
    VT_SENDER_NAME = 10,
    VT_READ = 12,
    VT_TITLE = 14,
    VT_CREATED_DATE = 16
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint32_t user() const {
    return GetField<uint32_t>(VT_USER, 0);
  }
  uint32_t sender() const {
    return GetField<uint32_t>(VT_SENDER, 0);
  }
  const ::flatbuffers::String *sender_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SENDER_NAME);
  }
  bool read() const {
    return GetField<uint8_t>(VT_READ, 0) != 0;
  }
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *created_date() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_DATE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_USER, 4) &&
           VerifyField<uint32_t>(verifier, VT_SENDER, 4) &&
           VerifyOffset(verifier, VT_SENDER_NAME) &&
           verifier.VerifyString(sender_name()) &&
           VerifyField<uint8_t>(verifier, VT_READ, 1) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_CREATED_DATE) &&
           verifier.VerifyString(created_date()) &&
           verifier.EndTable();
  }
};

struct MailSummaryBuilder {
  typedef MailSummary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(MailSummary::VT_ID, id, 0);
  }
  void add_user(uint32_t user) {
    fbb_.AddElement<uint32_t>(MailSummary::VT_USER, user, 0);
  }
  void add_sender(uint32_t sender) {
    fbb_.AddElement<uint32_t>(MailSummary::VT_SENDER, sender, 0);
  }
  void add_sender_name(::flatbuffers::Offset<::flatbuffers::String> sender_name) {
    fbb_.AddOffset(MailSummary::VT_SENDER_NAME, sender_name);
  }
  void add_read(bool read) {
    fbb_.AddElement<uint8_t>(MailSummary::VT_READ, static_cast<uint8_t>(read), 0);
  }
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(MailSummary::VT_TITLE, title);
  }
  void add_created_date(::flatbuffers::Offset<::flatbuffers::String> created_date) {
    fbb_.AddOffset(MailSummary::VT_CREATED_DATE, created_date);
  }
  explicit MailSummaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MailSummary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MailSummary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MailSummary> CreateMailSummary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t user = 0,
    uint32_t sender = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sender_name = 0,
    bool read = false,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_date = 0) {
  MailSummaryBuilder builder_(_fbb);
  builder_.add_created_date(created_date);
  builder_.add_title(title);
  builder_.add_sender_name(sender_name);
  builder_.add_sender(sender);
  builder_.add_user(user);
  builder_.add_id(id);
  builder_.add_read(read);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MailSummary> CreateMailSummaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t user = 0,
    uint32_t sender = 0,
    const char *sender_name = nullptr,
    bool read = false,
    const char *title = nullptr,
    const char *created_date = nullptr) {
  auto sender_name__ = sender_name ? _fbb.CreateString(sender_name) : 0;
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto created_date__ = created_date ? _fbb.CreateString(created_date) : 0;
  return fb::protocol::internal::raw::CreateMailSummary(
      _fbb,
      id,
      user,
      sender,
      sender_name__,
      read,
      title__,
      created_date__);
}

inline const fb::protocol::internal::raw::MailSummary *GetMailSummary(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::raw::MailSummary>(buf);
}

inline const fb::protocol::internal::raw::MailSummary *GetSizePrefixedMailSummary(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::raw::MailSummary>(buf);
}

inline bool VerifyMailSummaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::raw::MailSummary>(nullptr);
}

inline bool VerifySizePrefixedMailSummaryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::raw::MailSummary>(nullptr);
}

inline void FinishMailSummaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::MailSummary> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMailSummaryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::MailSummary> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALMAILSUMMARY_FB_PROTOCOL_INTERNAL_RAW_H_
