// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALCLANDETAILSACTION_FB_PROTOCOL_INTERNAL_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALCLANDETAILSACTION_FB_PROTOCOL_INTERNAL_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace raw {

enum ClanDetailsAction : int8_t {
  ClanDetailsAction_Query = 0,
  ClanDetailsAction_Create = 1,
  ClanDetailsAction_MIN = ClanDetailsAction_Query,
  ClanDetailsAction_MAX = ClanDetailsAction_Create
};

inline const ClanDetailsAction (&EnumValuesClanDetailsAction())[2] {
  static const ClanDetailsAction values[] = {
    ClanDetailsAction_Query,
    ClanDetailsAction_Create
  };
  return values;
}

inline const char * const *EnumNamesClanDetailsAction() {
  static const char * const names[3] = {
    "Query",
    "Create",
    nullptr
  };
  return names;
}

inline const char *EnumNameClanDetailsAction(ClanDetailsAction e) {
  if (::flatbuffers::IsOutRange(e, ClanDetailsAction_Query, ClanDetailsAction_Create)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesClanDetailsAction()[index];
}

}  // namespace raw
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALCLANDETAILSACTION_FB_PROTOCOL_INTERNAL_RAW_H_
