// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESETDROPRATEMULTIPLIER_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESETDROPRATEMULTIPLIER_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct SetDropRateMultiplier;
struct SetDropRateMultiplierBuilder;

struct SetDropRateMultiplier FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetDropRateMultiplierBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4,
    VT_ERROR = 6
  };
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct SetDropRateMultiplierBuilder {
  typedef SetDropRateMultiplier Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(double value) {
    fbb_.AddElement<double>(SetDropRateMultiplier::VT_VALUE, value, 0.0);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(SetDropRateMultiplier::VT_ERROR, error, 0);
  }
  explicit SetDropRateMultiplierBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetDropRateMultiplier> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetDropRateMultiplier>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetDropRateMultiplier> CreateSetDropRateMultiplier(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double value = 0.0,
    uint32_t error = 0) {
  SetDropRateMultiplierBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_error(error);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::SetDropRateMultiplier *GetSetDropRateMultiplier(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::SetDropRateMultiplier>(buf);
}

inline const fb::protocol::internal::response::raw::SetDropRateMultiplier *GetSizePrefixedSetDropRateMultiplier(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::SetDropRateMultiplier>(buf);
}

inline bool VerifySetDropRateMultiplierBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::SetDropRateMultiplier>(nullptr);
}

inline bool VerifySizePrefixedSetDropRateMultiplierBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::SetDropRateMultiplier>(nullptr);
}

inline void FinishSetDropRateMultiplierBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::SetDropRateMultiplier> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSetDropRateMultiplierBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::SetDropRateMultiplier> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSESETDROPRATEMULTIPLIER_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
