// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTGETLISTINGS_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTGETLISTINGS_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace marketplace {
namespace request {
namespace raw {

struct GetListings;
struct GetListingsBuilder;

struct GetListings FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetListingsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LISTING_IDS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *listing_ids() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_LISTING_IDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_LISTING_IDS) &&
           verifier.VerifyVector(listing_ids()) &&
           verifier.VerifyVectorOfStrings(listing_ids()) &&
           verifier.EndTable();
  }
};

struct GetListingsBuilder {
  typedef GetListings Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_listing_ids(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> listing_ids) {
    fbb_.AddOffset(GetListings::VT_LISTING_IDS, listing_ids);
  }
  explicit GetListingsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetListings> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetListings>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetListings> CreateGetListings(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> listing_ids = 0) {
  GetListingsBuilder builder_(_fbb);
  builder_.add_listing_ids(listing_ids);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetListings> CreateGetListingsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *listing_ids = nullptr) {
  auto listing_ids__ = listing_ids ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*listing_ids) : 0;
  return fb::protocol::marketplace::request::raw::CreateGetListings(
      _fbb,
      listing_ids__);
}

inline const fb::protocol::marketplace::request::raw::GetListings *GetGetListings(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::marketplace::request::raw::GetListings>(buf);
}

inline const fb::protocol::marketplace::request::raw::GetListings *GetSizePrefixedGetListings(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::marketplace::request::raw::GetListings>(buf);
}

inline bool VerifyGetListingsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::marketplace::request::raw::GetListings>(nullptr);
}

inline bool VerifySizePrefixedGetListingsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::marketplace::request::raw::GetListings>(nullptr);
}

inline void FinishGetListingsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::GetListings> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGetListingsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::GetListings> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace marketplace
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTGETLISTINGS_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
