// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTDELETEMAIL_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTDELETEMAIL_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace request {
namespace raw {

struct DeleteMail;
struct DeleteMailBuilder;

struct DeleteMail FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeleteMailBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER = 4,
    VT_ID = 6
  };
  uint32_t user() const {
    return GetField<uint32_t>(VT_USER, 0);
  }
  uint16_t id() const {
    return GetField<uint16_t>(VT_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_USER, 4) &&
           VerifyField<uint16_t>(verifier, VT_ID, 2) &&
           verifier.EndTable();
  }
};

struct DeleteMailBuilder {
  typedef DeleteMail Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_user(uint32_t user) {
    fbb_.AddElement<uint32_t>(DeleteMail::VT_USER, user, 0);
  }
  void add_id(uint16_t id) {
    fbb_.AddElement<uint16_t>(DeleteMail::VT_ID, id, 0);
  }
  explicit DeleteMailBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeleteMail> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeleteMail>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeleteMail> CreateDeleteMail(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t user = 0,
    uint16_t id = 0) {
  DeleteMailBuilder builder_(_fbb);
  builder_.add_user(user);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const fb::protocol::internal::request::raw::DeleteMail *GetDeleteMail(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::request::raw::DeleteMail>(buf);
}

inline const fb::protocol::internal::request::raw::DeleteMail *GetSizePrefixedDeleteMail(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::request::raw::DeleteMail>(buf);
}

inline bool VerifyDeleteMailBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::request::raw::DeleteMail>(nullptr);
}

inline bool VerifySizePrefixedDeleteMailBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::request::raw::DeleteMail>(nullptr);
}

inline void FinishDeleteMailBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::DeleteMail> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDeleteMailBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::request::raw::DeleteMail> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALREQUESTDELETEMAIL_FB_PROTOCOL_INTERNAL_REQUEST_RAW_H_
