// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLDBRESPONSELEAVEGROUP_FB_PROTOCOL_DB_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLDBRESPONSELEAVEGROUP_FB_PROTOCOL_DB_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.db.groupmember_generated.h"

namespace fb {
namespace protocol {
namespace db {
namespace response {
namespace raw {

struct LeaveGroup;
struct LeaveGroupBuilder;

struct LeaveGroup FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LeaveGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_MEMBER = 6,
    VT_HOST = 8,
    VT_ERROR = 10
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const fb::protocol::db::raw::GroupMember *member() const {
    return GetPointer<const fb::protocol::db::raw::GroupMember *>(VT_MEMBER);
  }
  uint8_t host() const {
    return GetField<uint8_t>(VT_HOST, 0);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_MEMBER) &&
           verifier.VerifyTable(member()) &&
           VerifyField<uint8_t>(verifier, VT_HOST, 1) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct LeaveGroupBuilder {
  typedef LeaveGroup Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(LeaveGroup::VT_ID, id);
  }
  void add_member(::flatbuffers::Offset<fb::protocol::db::raw::GroupMember> member) {
    fbb_.AddOffset(LeaveGroup::VT_MEMBER, member);
  }
  void add_host(uint8_t host) {
    fbb_.AddElement<uint8_t>(LeaveGroup::VT_HOST, host, 0);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(LeaveGroup::VT_ERROR, error, 0);
  }
  explicit LeaveGroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LeaveGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LeaveGroup>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LeaveGroup> CreateLeaveGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<fb::protocol::db::raw::GroupMember> member = 0,
    uint8_t host = 0,
    uint32_t error = 0) {
  LeaveGroupBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_member(member);
  builder_.add_id(id);
  builder_.add_host(host);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LeaveGroup> CreateLeaveGroupDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    ::flatbuffers::Offset<fb::protocol::db::raw::GroupMember> member = 0,
    uint8_t host = 0,
    uint32_t error = 0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  return fb::protocol::db::response::raw::CreateLeaveGroup(
      _fbb,
      id__,
      member,
      host,
      error);
}

inline const fb::protocol::db::response::raw::LeaveGroup *GetLeaveGroup(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::db::response::raw::LeaveGroup>(buf);
}

inline const fb::protocol::db::response::raw::LeaveGroup *GetSizePrefixedLeaveGroup(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::db::response::raw::LeaveGroup>(buf);
}

inline bool VerifyLeaveGroupBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::db::response::raw::LeaveGroup>(nullptr);
}

inline bool VerifySizePrefixedLeaveGroupBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::db::response::raw::LeaveGroup>(nullptr);
}

inline void FinishLeaveGroupBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::raw::LeaveGroup> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLeaveGroupBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::raw::LeaveGroup> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace db
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLDBRESPONSELEAVEGROUP_FB_PROTOCOL_DB_RESPONSE_RAW_H_
