// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEOPSNOTIFY_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEOPSNOTIFY_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct OpsNotify;
struct OpsNotifyBuilder;

struct OpsNotify FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OpsNotifyBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct OpsNotifyBuilder {
  typedef OpsNotify Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit OpsNotifyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OpsNotify> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OpsNotify>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OpsNotify> CreateOpsNotify(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  OpsNotifyBuilder builder_(_fbb);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::OpsNotify *GetOpsNotify(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::OpsNotify>(buf);
}

inline const fb::protocol::internal::response::raw::OpsNotify *GetSizePrefixedOpsNotify(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::OpsNotify>(buf);
}

inline bool VerifyOpsNotifyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::OpsNotify>(nullptr);
}

inline bool VerifySizePrefixedOpsNotifyBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::OpsNotify>(nullptr);
}

inline void FinishOpsNotifyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::OpsNotify> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOpsNotifyBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::OpsNotify> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEOPSNOTIFY_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
