// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALSTORAGEWRITEENTRY_FB_PROTOCOL_INTERNAL_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALSTORAGEWRITEENTRY_FB_PROTOCOL_INTERNAL_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.storagebox_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace raw {

struct StorageWriteEntry;
struct StorageWriteEntryBuilder;

struct StorageWriteEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StorageWriteEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER = 4,
    VT_BOX = 6
  };
  uint32_t user() const {
    return GetField<uint32_t>(VT_USER, 0);
  }
  const fb::protocol::internal::raw::StorageBox *box() const {
    return GetPointer<const fb::protocol::internal::raw::StorageBox *>(VT_BOX);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_USER, 4) &&
           VerifyOffset(verifier, VT_BOX) &&
           verifier.VerifyTable(box()) &&
           verifier.EndTable();
  }
};

struct StorageWriteEntryBuilder {
  typedef StorageWriteEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_user(uint32_t user) {
    fbb_.AddElement<uint32_t>(StorageWriteEntry::VT_USER, user, 0);
  }
  void add_box(::flatbuffers::Offset<fb::protocol::internal::raw::StorageBox> box) {
    fbb_.AddOffset(StorageWriteEntry::VT_BOX, box);
  }
  explicit StorageWriteEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StorageWriteEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StorageWriteEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StorageWriteEntry> CreateStorageWriteEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t user = 0,
    ::flatbuffers::Offset<fb::protocol::internal::raw::StorageBox> box = 0) {
  StorageWriteEntryBuilder builder_(_fbb);
  builder_.add_box(box);
  builder_.add_user(user);
  return builder_.Finish();
}

inline const fb::protocol::internal::raw::StorageWriteEntry *GetStorageWriteEntry(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::raw::StorageWriteEntry>(buf);
}

inline const fb::protocol::internal::raw::StorageWriteEntry *GetSizePrefixedStorageWriteEntry(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::raw::StorageWriteEntry>(buf);
}

inline bool VerifyStorageWriteEntryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::raw::StorageWriteEntry>(nullptr);
}

inline bool VerifySizePrefixedStorageWriteEntryBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::raw::StorageWriteEntry>(nullptr);
}

inline void FinishStorageWriteEntryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::StorageWriteEntry> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStorageWriteEntryBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::StorageWriteEntry> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALSTORAGEWRITEENTRY_FB_PROTOCOL_INTERNAL_RAW_H_
