// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSESTATUS_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSESTATUS_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace matchmaking {
namespace response {
namespace raw {

struct Status;
struct StatusBuilder;

struct Status FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_QUEUED = 4,
    VT_MATCH_TYPE = 6,
    VT_TICKET_ID = 8,
    VT_PENDING_MATCH_ID = 10,
    VT_CONFIRM_DEADLINE = 12,
    VT_ERROR = 14
  };
  bool queued() const {
    return GetField<uint8_t>(VT_QUEUED, 0) != 0;
  }
  uint32_t match_type() const {
    return GetField<uint32_t>(VT_MATCH_TYPE, 0);
  }
  uint64_t ticket_id() const {
    return GetField<uint64_t>(VT_TICKET_ID, 0);
  }
  uint64_t pending_match_id() const {
    return GetField<uint64_t>(VT_PENDING_MATCH_ID, 0);
  }
  const ::flatbuffers::String *confirm_deadline() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFIRM_DEADLINE);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_QUEUED, 1) &&
           VerifyField<uint32_t>(verifier, VT_MATCH_TYPE, 4) &&
           VerifyField<uint64_t>(verifier, VT_TICKET_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PENDING_MATCH_ID, 8) &&
           VerifyOffset(verifier, VT_CONFIRM_DEADLINE) &&
           verifier.VerifyString(confirm_deadline()) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct StatusBuilder {
  typedef Status Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_queued(bool queued) {
    fbb_.AddElement<uint8_t>(Status::VT_QUEUED, static_cast<uint8_t>(queued), 0);
  }
  void add_match_type(uint32_t match_type) {
    fbb_.AddElement<uint32_t>(Status::VT_MATCH_TYPE, match_type, 0);
  }
  void add_ticket_id(uint64_t ticket_id) {
    fbb_.AddElement<uint64_t>(Status::VT_TICKET_ID, ticket_id, 0);
  }
  void add_pending_match_id(uint64_t pending_match_id) {
    fbb_.AddElement<uint64_t>(Status::VT_PENDING_MATCH_ID, pending_match_id, 0);
  }
  void add_confirm_deadline(::flatbuffers::Offset<::flatbuffers::String> confirm_deadline) {
    fbb_.AddOffset(Status::VT_CONFIRM_DEADLINE, confirm_deadline);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(Status::VT_ERROR, error, 0);
  }
  explicit StatusBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Status> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Status>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Status> CreateStatus(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool queued = false,
    uint32_t match_type = 0,
    uint64_t ticket_id = 0,
    uint64_t pending_match_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> confirm_deadline = 0,
    uint32_t error = 0) {
  StatusBuilder builder_(_fbb);
  builder_.add_pending_match_id(pending_match_id);
  builder_.add_ticket_id(ticket_id);
  builder_.add_error(error);
  builder_.add_confirm_deadline(confirm_deadline);
  builder_.add_match_type(match_type);
  builder_.add_queued(queued);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Status> CreateStatusDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool queued = false,
    uint32_t match_type = 0,
    uint64_t ticket_id = 0,
    uint64_t pending_match_id = 0,
    const char *confirm_deadline = nullptr,
    uint32_t error = 0) {
  auto confirm_deadline__ = confirm_deadline ? _fbb.CreateString(confirm_deadline) : 0;
  return fb::protocol::matchmaking::response::raw::CreateStatus(
      _fbb,
      queued,
      match_type,
      ticket_id,
      pending_match_id,
      confirm_deadline__,
      error);
}

inline const fb::protocol::matchmaking::response::raw::Status *GetStatus(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::matchmaking::response::raw::Status>(buf);
}

inline const fb::protocol::matchmaking::response::raw::Status *GetSizePrefixedStatus(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::matchmaking::response::raw::Status>(buf);
}

inline bool VerifyStatusBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::matchmaking::response::raw::Status>(nullptr);
}

inline bool VerifySizePrefixedStatusBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::matchmaking::response::raw::Status>(nullptr);
}

inline void FinishStatusBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::response::raw::Status> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedStatusBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::response::raw::Status> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace matchmaking
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGRESPONSESTATUS_FB_PROTOCOL_MATCHMAKING_RESPONSE_RAW_H_
