// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGMATCHTEAM_FB_PROTOCOL_MATCHMAKING_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGMATCHTEAM_FB_PROTOCOL_MATCHMAKING_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.matchmaking.matchregistry_generated.h"

namespace fb {
namespace protocol {
namespace matchmaking {
namespace raw {

struct MatchTeam;
struct MatchTeamBuilder;

struct MatchTeam FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MatchTeamBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REGISTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>> *registries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>> *>(VT_REGISTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REGISTRIES) &&
           verifier.VerifyVector(registries()) &&
           verifier.VerifyVectorOfTables(registries()) &&
           verifier.EndTable();
  }
};

struct MatchTeamBuilder {
  typedef MatchTeam Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_registries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>>> registries) {
    fbb_.AddOffset(MatchTeam::VT_REGISTRIES, registries);
  }
  explicit MatchTeamBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MatchTeam> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MatchTeam>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MatchTeam> CreateMatchTeam(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>>> registries = 0) {
  MatchTeamBuilder builder_(_fbb);
  builder_.add_registries(registries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MatchTeam> CreateMatchTeamDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>> *registries = nullptr) {
  auto registries__ = registries ? _fbb.CreateVector<::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchRegistry>>(*registries) : 0;
  return fb::protocol::matchmaking::raw::CreateMatchTeam(
      _fbb,
      registries__);
}

inline const fb::protocol::matchmaking::raw::MatchTeam *GetMatchTeam(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::matchmaking::raw::MatchTeam>(buf);
}

inline const fb::protocol::matchmaking::raw::MatchTeam *GetSizePrefixedMatchTeam(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::matchmaking::raw::MatchTeam>(buf);
}

inline bool VerifyMatchTeamBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::matchmaking::raw::MatchTeam>(nullptr);
}

inline bool VerifySizePrefixedMatchTeamBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::matchmaking::raw::MatchTeam>(nullptr);
}

inline void FinishMatchTeamBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchTeam> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMatchTeamBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::raw::MatchTeam> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace matchmaking
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGMATCHTEAM_FB_PROTOCOL_MATCHMAKING_RAW_H_
