// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETUNRECEIVEDSYSTEMMAILS_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETUNRECEIVEDSYSTEMMAILS_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct GetUnreceivedSystemMails;
struct GetUnreceivedSystemMailsBuilder;

struct GetUnreceivedSystemMails FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetUnreceivedSystemMailsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SYSTEM_MAIL_IDS = 4,
    VT_ERROR = 6
  };
  const ::flatbuffers::Vector<uint32_t> *system_mail_ids() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_SYSTEM_MAIL_IDS);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SYSTEM_MAIL_IDS) &&
           verifier.VerifyVector(system_mail_ids()) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct GetUnreceivedSystemMailsBuilder {
  typedef GetUnreceivedSystemMails Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_system_mail_ids(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> system_mail_ids) {
    fbb_.AddOffset(GetUnreceivedSystemMails::VT_SYSTEM_MAIL_IDS, system_mail_ids);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(GetUnreceivedSystemMails::VT_ERROR, error, 0);
  }
  explicit GetUnreceivedSystemMailsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetUnreceivedSystemMails> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetUnreceivedSystemMails>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetUnreceivedSystemMails> CreateGetUnreceivedSystemMails(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> system_mail_ids = 0,
    uint32_t error = 0) {
  GetUnreceivedSystemMailsBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_system_mail_ids(system_mail_ids);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetUnreceivedSystemMails> CreateGetUnreceivedSystemMailsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *system_mail_ids = nullptr,
    uint32_t error = 0) {
  auto system_mail_ids__ = system_mail_ids ? _fbb.CreateVector<uint32_t>(*system_mail_ids) : 0;
  return fb::protocol::internal::response::raw::CreateGetUnreceivedSystemMails(
      _fbb,
      system_mail_ids__,
      error);
}

inline const fb::protocol::internal::response::raw::GetUnreceivedSystemMails *GetGetUnreceivedSystemMails(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::GetUnreceivedSystemMails>(buf);
}

inline const fb::protocol::internal::response::raw::GetUnreceivedSystemMails *GetSizePrefixedGetUnreceivedSystemMails(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::GetUnreceivedSystemMails>(buf);
}

inline bool VerifyGetUnreceivedSystemMailsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::GetUnreceivedSystemMails>(nullptr);
}

inline bool VerifySizePrefixedGetUnreceivedSystemMailsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::GetUnreceivedSystemMails>(nullptr);
}

inline void FinishGetUnreceivedSystemMailsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::GetUnreceivedSystemMails> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGetUnreceivedSystemMailsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::GetUnreceivedSystemMails> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEGETUNRECEIVEDSYSTEMMAILS_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
