// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEWRITESTORAGEBOX_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEWRITESTORAGEBOX_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.storagebox_generated.h"

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct WriteStorageBox;
struct WriteStorageBoxBuilder;

struct WriteStorageBox FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WriteStorageBoxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BOX = 4,
    VT_HOST = 6,
    VT_ERROR = 8
  };
  const fb::protocol::internal::raw::StorageBox *box() const {
    return GetPointer<const fb::protocol::internal::raw::StorageBox *>(VT_BOX);
  }
  uint32_t host() const {
    return GetField<uint32_t>(VT_HOST, 0);
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BOX) &&
           verifier.VerifyTable(box()) &&
           VerifyField<uint32_t>(verifier, VT_HOST, 4) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct WriteStorageBoxBuilder {
  typedef WriteStorageBox Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_box(::flatbuffers::Offset<fb::protocol::internal::raw::StorageBox> box) {
    fbb_.AddOffset(WriteStorageBox::VT_BOX, box);
  }
  void add_host(uint32_t host) {
    fbb_.AddElement<uint32_t>(WriteStorageBox::VT_HOST, host, 0);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(WriteStorageBox::VT_ERROR, error, 0);
  }
  explicit WriteStorageBoxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WriteStorageBox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WriteStorageBox>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WriteStorageBox> CreateWriteStorageBox(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::StorageBox> box = 0,
    uint32_t host = 0,
    uint32_t error = 0) {
  WriteStorageBoxBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_host(host);
  builder_.add_box(box);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::WriteStorageBox *GetWriteStorageBox(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::WriteStorageBox>(buf);
}

inline const fb::protocol::internal::response::raw::WriteStorageBox *GetSizePrefixedWriteStorageBox(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::WriteStorageBox>(buf);
}

inline bool VerifyWriteStorageBoxBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::WriteStorageBox>(nullptr);
}

inline bool VerifySizePrefixedWriteStorageBoxBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::WriteStorageBox>(nullptr);
}

inline void FinishWriteStorageBoxBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::WriteStorageBox> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWriteStorageBoxBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::WriteStorageBox> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEWRITESTORAGEBOX_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
