// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSELEAVECLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSELEAVECLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct LeaveClan;
struct LeaveClanBuilder;

struct LeaveClan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LeaveClanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLAN = 4,
    VT_UID = 6,
    VT_UNAME = 8,
    VT_KICK = 10,
    VT_ERROR = 12
  };
  uint32_t clan() const {
    return GetField<uint32_t>(VT_CLAN, 0);
  }
  uint32_t uid() const {
    return GetField<uint32_t>(VT_UID, 0);
  }
  const ::flatbuffers::String *uname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNAME);
  }
  bool kick() const {
    return GetField<uint8_t>(VT_KICK, 0) != 0;
  }
  uint32_t error() const {
    return GetField<uint32_t>(VT_ERROR, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CLAN, 4) &&
           VerifyField<uint32_t>(verifier, VT_UID, 4) &&
           VerifyOffset(verifier, VT_UNAME) &&
           verifier.VerifyString(uname()) &&
           VerifyField<uint8_t>(verifier, VT_KICK, 1) &&
           VerifyField<uint32_t>(verifier, VT_ERROR, 4) &&
           verifier.EndTable();
  }
};

struct LeaveClanBuilder {
  typedef LeaveClan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_clan(uint32_t clan) {
    fbb_.AddElement<uint32_t>(LeaveClan::VT_CLAN, clan, 0);
  }
  void add_uid(uint32_t uid) {
    fbb_.AddElement<uint32_t>(LeaveClan::VT_UID, uid, 0);
  }
  void add_uname(::flatbuffers::Offset<::flatbuffers::String> uname) {
    fbb_.AddOffset(LeaveClan::VT_UNAME, uname);
  }
  void add_kick(bool kick) {
    fbb_.AddElement<uint8_t>(LeaveClan::VT_KICK, static_cast<uint8_t>(kick), 0);
  }
  void add_error(uint32_t error) {
    fbb_.AddElement<uint32_t>(LeaveClan::VT_ERROR, error, 0);
  }
  explicit LeaveClanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LeaveClan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LeaveClan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LeaveClan> CreateLeaveClan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t clan = 0,
    uint32_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> uname = 0,
    bool kick = false,
    uint32_t error = 0) {
  LeaveClanBuilder builder_(_fbb);
  builder_.add_error(error);
  builder_.add_uname(uname);
  builder_.add_uid(uid);
  builder_.add_clan(clan);
  builder_.add_kick(kick);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LeaveClan> CreateLeaveClanDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t clan = 0,
    uint32_t uid = 0,
    const char *uname = nullptr,
    bool kick = false,
    uint32_t error = 0) {
  auto uname__ = uname ? _fbb.CreateString(uname) : 0;
  return fb::protocol::internal::response::raw::CreateLeaveClan(
      _fbb,
      clan,
      uid,
      uname__,
      kick,
      error);
}

inline const fb::protocol::internal::response::raw::LeaveClan *GetLeaveClan(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::LeaveClan>(buf);
}

inline const fb::protocol::internal::response::raw::LeaveClan *GetSizePrefixedLeaveClan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::LeaveClan>(buf);
}

inline bool VerifyLeaveClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::LeaveClan>(nullptr);
}

inline bool VerifySizePrefixedLeaveClanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::LeaveClan>(nullptr);
}

inline void FinishLeaveClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::LeaveClan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLeaveClanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::LeaveClan> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSELEAVECLAN_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
