// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTLIST_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTLIST_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.marketplace.item_generated.h"

namespace fb {
namespace protocol {
namespace marketplace {
namespace request {
namespace raw {

struct List;
struct ListBuilder;

struct List FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER_ID = 4,
    VT_LISTING_ID = 6,
    VT_ITEM = 8,
    VT_PRICE = 10
  };
  uint32_t character_id() const {
    return GetField<uint32_t>(VT_CHARACTER_ID, 0);
  }
  const ::flatbuffers::String *listing_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LISTING_ID);
  }
  const fb::protocol::marketplace::raw::Item *item() const {
    return GetPointer<const fb::protocol::marketplace::raw::Item *>(VT_ITEM);
  }
  uint32_t price() const {
    return GetField<uint32_t>(VT_PRICE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CHARACTER_ID, 4) &&
           VerifyOffset(verifier, VT_LISTING_ID) &&
           verifier.VerifyString(listing_id()) &&
           VerifyOffset(verifier, VT_ITEM) &&
           verifier.VerifyTable(item()) &&
           VerifyField<uint32_t>(verifier, VT_PRICE, 4) &&
           verifier.EndTable();
  }
};

struct ListBuilder {
  typedef List Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_character_id(uint32_t character_id) {
    fbb_.AddElement<uint32_t>(List::VT_CHARACTER_ID, character_id, 0);
  }
  void add_listing_id(::flatbuffers::Offset<::flatbuffers::String> listing_id) {
    fbb_.AddOffset(List::VT_LISTING_ID, listing_id);
  }
  void add_item(::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item) {
    fbb_.AddOffset(List::VT_ITEM, item);
  }
  void add_price(uint32_t price) {
    fbb_.AddElement<uint32_t>(List::VT_PRICE, price, 0);
  }
  explicit ListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<List> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<List>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<List> CreateList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t character_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> listing_id = 0,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item = 0,
    uint32_t price = 0) {
  ListBuilder builder_(_fbb);
  builder_.add_price(price);
  builder_.add_item(item);
  builder_.add_listing_id(listing_id);
  builder_.add_character_id(character_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<List> CreateListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t character_id = 0,
    const char *listing_id = nullptr,
    ::flatbuffers::Offset<fb::protocol::marketplace::raw::Item> item = 0,
    uint32_t price = 0) {
  auto listing_id__ = listing_id ? _fbb.CreateString(listing_id) : 0;
  return fb::protocol::marketplace::request::raw::CreateList(
      _fbb,
      character_id,
      listing_id__,
      item,
      price);
}

inline const fb::protocol::marketplace::request::raw::List *GetList(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::marketplace::request::raw::List>(buf);
}

inline const fb::protocol::marketplace::request::raw::List *GetSizePrefixedList(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::marketplace::request::raw::List>(buf);
}

inline bool VerifyListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::marketplace::request::raw::List>(nullptr);
}

inline bool VerifySizePrefixedListBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::marketplace::request::raw::List>(nullptr);
}

inline void FinishListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::List> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedListBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::marketplace::request::raw::List> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace request
}  // namespace marketplace
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMARKETPLACEREQUESTLIST_FB_PROTOCOL_MARKETPLACE_REQUEST_RAW_H_
