// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEBROADCASTSAVE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEBROADCASTSAVE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace internal {
namespace response {
namespace raw {

struct BroadcastSave;
struct BroadcastSaveBuilder;

struct BroadcastSave FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BroadcastSaveBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct BroadcastSaveBuilder {
  typedef BroadcastSave Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit BroadcastSaveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BroadcastSave> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BroadcastSave>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BroadcastSave> CreateBroadcastSave(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  BroadcastSaveBuilder builder_(_fbb);
  return builder_.Finish();
}

inline const fb::protocol::internal::response::raw::BroadcastSave *GetBroadcastSave(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::internal::response::raw::BroadcastSave>(buf);
}

inline const fb::protocol::internal::response::raw::BroadcastSave *GetSizePrefixedBroadcastSave(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::internal::response::raw::BroadcastSave>(buf);
}

inline bool VerifyBroadcastSaveBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::internal::response::raw::BroadcastSave>(nullptr);
}

inline bool VerifySizePrefixedBroadcastSaveBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::internal::response::raw::BroadcastSave>(nullptr);
}

inline void FinishBroadcastSaveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::BroadcastSave> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBroadcastSaveBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::internal::response::raw::BroadcastSave> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace response
}  // namespace internal
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLINTERNALRESPONSEBROADCASTSAVE_FB_PROTOCOL_INTERNAL_RESPONSE_RAW_H_
