// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGTICKETMEMBER_FB_PROTOCOL_MATCHMAKING_RAW_H_
#define FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGTICKETMEMBER_FB_PROTOCOL_MATCHMAKING_RAW_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace fb {
namespace protocol {
namespace matchmaking {
namespace raw {

struct TicketMember;
struct TicketMemberBuilder;

struct TicketMember FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TicketMemberBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD = 4,
    VT_CHARACTER_ID = 6,
    VT_MU = 8,
    VT_SIGMA = 10
  };
  uint32_t world() const {
    return GetField<uint32_t>(VT_WORLD, 0);
  }
  uint32_t character_id() const {
    return GetField<uint32_t>(VT_CHARACTER_ID, 0);
  }
  double mu() const {
    return GetField<double>(VT_MU, 0.0);
  }
  double sigma() const {
    return GetField<double>(VT_SIGMA, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WORLD, 4) &&
           VerifyField<uint32_t>(verifier, VT_CHARACTER_ID, 4) &&
           VerifyField<double>(verifier, VT_MU, 8) &&
           VerifyField<double>(verifier, VT_SIGMA, 8) &&
           verifier.EndTable();
  }
};

struct TicketMemberBuilder {
  typedef TicketMember Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world(uint32_t world) {
    fbb_.AddElement<uint32_t>(TicketMember::VT_WORLD, world, 0);
  }
  void add_character_id(uint32_t character_id) {
    fbb_.AddElement<uint32_t>(TicketMember::VT_CHARACTER_ID, character_id, 0);
  }
  void add_mu(double mu) {
    fbb_.AddElement<double>(TicketMember::VT_MU, mu, 0.0);
  }
  void add_sigma(double sigma) {
    fbb_.AddElement<double>(TicketMember::VT_SIGMA, sigma, 0.0);
  }
  explicit TicketMemberBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TicketMember> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TicketMember>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TicketMember> CreateTicketMember(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t world = 0,
    uint32_t character_id = 0,
    double mu = 0.0,
    double sigma = 0.0) {
  TicketMemberBuilder builder_(_fbb);
  builder_.add_sigma(sigma);
  builder_.add_mu(mu);
  builder_.add_character_id(character_id);
  builder_.add_world(world);
  return builder_.Finish();
}

inline const fb::protocol::matchmaking::raw::TicketMember *GetTicketMember(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::matchmaking::raw::TicketMember>(buf);
}

inline const fb::protocol::matchmaking::raw::TicketMember *GetSizePrefixedTicketMember(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::matchmaking::raw::TicketMember>(buf);
}

inline bool VerifyTicketMemberBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::matchmaking::raw::TicketMember>(nullptr);
}

inline bool VerifySizePrefixedTicketMemberBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::matchmaking::raw::TicketMember>(nullptr);
}

inline void FinishTicketMemberBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::raw::TicketMember> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTicketMemberBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::matchmaking::raw::TicketMember> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace raw
}  // namespace matchmaking
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_FBPROTOCOLMATCHMAKINGTICKETMEMBER_FB_PROTOCOL_MATCHMAKING_RAW_H_
