// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NULLABLEFBPROTOCOLINTERNALMIMICRY_NULLABLE_H_
#define FLATBUFFERS_GENERATED_NULLABLEFBPROTOCOLINTERNALMIMICRY_NULLABLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fb.protocol.internal.mimicry_generated.h"

namespace nullable {

struct nullable_fb_protocol_internal_mimicry;
struct nullable_fb_protocol_internal_mimicryBuilder;

struct nullable_fb_protocol_internal_mimicry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef nullable_fb_protocol_internal_mimicryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  const fb::protocol::internal::raw::Mimicry *value() const {
    return GetPointer<const fb::protocol::internal::raw::Mimicry *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           verifier.EndTable();
  }
};

struct nullable_fb_protocol_internal_mimicryBuilder {
  typedef nullable_fb_protocol_internal_mimicry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(::flatbuffers::Offset<fb::protocol::internal::raw::Mimicry> value) {
    fbb_.AddOffset(nullable_fb_protocol_internal_mimicry::VT_VALUE, value);
  }
  explicit nullable_fb_protocol_internal_mimicryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<nullable_fb_protocol_internal_mimicry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<nullable_fb_protocol_internal_mimicry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<nullable_fb_protocol_internal_mimicry> Createnullable_fb_protocol_internal_mimicry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::internal::raw::Mimicry> value = 0) {
  nullable_fb_protocol_internal_mimicryBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

}  // namespace nullable

#endif  // FLATBUFFERS_GENERATED_NULLABLEFBPROTOCOLINTERNALMIMICRY_NULLABLE_H_
