// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.marketplace.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Purchase : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Purchase GetRootAsPurchase(ByteBuffer _bb) { return GetRootAsPurchase(_bb, new Purchase()); }
  public static Purchase GetRootAsPurchase(ByteBuffer _bb, Purchase obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPurchase(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PurchaseVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Purchase __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.protocol.marketplace.raw.Item? Item { get { int o = __p.__offset(4); return o != 0 ? (fb.protocol.marketplace.raw.Item?)(new fb.protocol.marketplace.raw.Item()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint Error { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol.marketplace.response.raw.Purchase> CreatePurchase(FlatBufferBuilder builder,
      Offset<fb.protocol.marketplace.raw.Item> itemOffset = default(Offset<fb.protocol.marketplace.raw.Item>),
      uint error = 0) {
    builder.StartTable(2);
    Purchase.AddError(builder, error);
    Purchase.AddItem(builder, itemOffset);
    return Purchase.EndPurchase(builder);
  }

  public static void StartPurchase(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddItem(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.raw.Item> itemOffset) { builder.AddOffset(0, itemOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(1, error, 0); }
  public static Offset<fb.protocol.marketplace.response.raw.Purchase> EndPurchase(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.marketplace.response.raw.Purchase>(o);
  }
  public static void FinishPurchaseBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.response.raw.Purchase> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPurchaseBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.response.raw.Purchase> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PurchaseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Item*/, fb.protocol.marketplace.raw.ItemVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
