// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.marketplace.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MarketplaceListing : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MarketplaceListing GetRootAsMarketplaceListing(ByteBuffer _bb) { return GetRootAsMarketplaceListing(_bb, new MarketplaceListing()); }
  public static MarketplaceListing GetRootAsMarketplaceListing(ByteBuffer _bb, MarketplaceListing obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMarketplaceListing(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MarketplaceListingVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MarketplaceListing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SellerId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public fb.protocol.marketplace.raw.MarketplaceItem? Item { get { int o = __p.__offset(8); return o != 0 ? (fb.protocol.marketplace.raw.MarketplaceItem?)(new fb.protocol.marketplace.raw.MarketplaceItem()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint Price { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ListingFee { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint TransactionFee { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string ExpireDate { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetExpireDateBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetExpireDateBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetExpireDateArray() { return __p.__vector_as_array<byte>(16); }
  public string CreatedDate { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCreatedDateBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetCreatedDateBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetCreatedDateArray() { return __p.__vector_as_array<byte>(18); }

  public static Offset<fb.protocol.marketplace.raw.MarketplaceListing> CreateMarketplaceListing(FlatBufferBuilder builder,
      ulong id = 0,
      uint seller_id = 0,
      Offset<fb.protocol.marketplace.raw.MarketplaceItem> itemOffset = default(Offset<fb.protocol.marketplace.raw.MarketplaceItem>),
      uint price = 0,
      uint listing_fee = 0,
      uint transaction_fee = 0,
      StringOffset expire_dateOffset = default(StringOffset),
      StringOffset created_dateOffset = default(StringOffset)) {
    builder.StartTable(8);
    MarketplaceListing.AddId(builder, id);
    MarketplaceListing.AddCreatedDate(builder, created_dateOffset);
    MarketplaceListing.AddExpireDate(builder, expire_dateOffset);
    MarketplaceListing.AddTransactionFee(builder, transaction_fee);
    MarketplaceListing.AddListingFee(builder, listing_fee);
    MarketplaceListing.AddPrice(builder, price);
    MarketplaceListing.AddItem(builder, itemOffset);
    MarketplaceListing.AddSellerId(builder, seller_id);
    return MarketplaceListing.EndMarketplaceListing(builder);
  }

  public static void StartMarketplaceListing(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddId(FlatBufferBuilder builder, ulong id) { builder.AddUlong(0, id, 0); }
  public static void AddSellerId(FlatBufferBuilder builder, uint sellerId) { builder.AddUint(1, sellerId, 0); }
  public static void AddItem(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.raw.MarketplaceItem> itemOffset) { builder.AddOffset(2, itemOffset.Value, 0); }
  public static void AddPrice(FlatBufferBuilder builder, uint price) { builder.AddUint(3, price, 0); }
  public static void AddListingFee(FlatBufferBuilder builder, uint listingFee) { builder.AddUint(4, listingFee, 0); }
  public static void AddTransactionFee(FlatBufferBuilder builder, uint transactionFee) { builder.AddUint(5, transactionFee, 0); }
  public static void AddExpireDate(FlatBufferBuilder builder, StringOffset expireDateOffset) { builder.AddOffset(6, expireDateOffset.Value, 0); }
  public static void AddCreatedDate(FlatBufferBuilder builder, StringOffset createdDateOffset) { builder.AddOffset(7, createdDateOffset.Value, 0); }
  public static Offset<fb.protocol.marketplace.raw.MarketplaceListing> EndMarketplaceListing(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.marketplace.raw.MarketplaceListing>(o);
  }
  public static void FinishMarketplaceListingBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.raw.MarketplaceListing> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMarketplaceListingBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.raw.MarketplaceListing> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MarketplaceListingVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SellerId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 8 /*Item*/, fb.protocol.marketplace.raw.MarketplaceItemVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Price*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*ListingFee*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*TransactionFee*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 16 /*ExpireDate*/, false)
      && verifier.VerifyString(tablePos, 18 /*CreatedDate*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
