include "internal.fbs";

namespace fb.protocol.internal.response;

table KickOut {
  uid: uint;
  name: string;
}



table Login {
  error: uint;
  logon: bool;
  ip: string;
  port: ushort;
}



table Logout {
  success: bool;
}



table Pong {
  
}



table Transfer {
  error: uint;
  ip: string;
  port: ushort;
}



table Whisper {
  from : string;
  to: string;
  message: string;
  host: uint;
  error: uint;
}

table DeleteArticle {
  result: int;
}


table GetArticle {
  article: fb.protocol.internal.Article;
  next: bool;
  success: bool;
}


table GetArticleList {
  summary_list: [fb.protocol.internal.ArticleSummary];
}


table WriteArticle {
  success: bool;
}


table ChangePw {
  error_code: uint;
}


table GetUid {
  uid: uint;
  success: bool;
}


table InitCharacter {
  success: bool;
}


table Authenticate {
  map: uint;
  error_code: uint;
}


table Init {
  character: fb.protocol.internal.Character;
  group: uint?;
  clan: uint?;
  items: [fb.protocol.internal.Item];
  spells: [fb.protocol.internal.Spell];
  option: fb.protocol.internal.Option;
  traces: [fb.protocol.internal.Trace];
}


table MakeCharacter {
  success: bool;
}


table ReserveName {
  uid: uint;
  success: bool;
}


table Save {
  success: bool;
}

table SetOption {
  success: bool;
}

table GetGroup {
  group: fb.protocol.internal.Group;
  error: uint;
}

table EnterGroup {
  group: fb.protocol.internal.Group;
  member: string;
  action: fb.protocol.internal.GroupAction;
  host: uint;
  error: uint;
}

table LeaveGroup {
  group: fb.protocol.internal.Group;
  member: string;
  action: fb.protocol.internal.GroupAction;
  host: uint;
  error: uint;
}

table GetClan {
  clan: fb.protocol.internal.Clan;
  members: [fb.protocol.internal.ClanMember];
  error: uint;
}

table CreateClan {
  clan: fb.protocol.internal.Clan;
  members: [fb.protocol.internal.ClanMember];
  error: uint;
}

table DestroyClan {
  error: uint;
}

table JoinClan {
  clan: uint;
  member: fb.protocol.internal.ClanMember;
  error: uint;

}
table LeaveClan {
  clan: uint;
  uid: uint;
  uname: string;
  kick: bool;
  error: uint;
}

table SetClanTitle {
  clan: uint;
  title: string?;
  error: uint;
}

table BroadcastClan {
  clan: uint;
  message: string;
  type: ubyte;
  error: uint;
}