include "internal.fbs";

namespace fb.protocol.internal.request;

table Shutdown {
  
}

table Login {
  section: string;
  uid: uint;
  name: string;
  host: ubyte;
  force: bool;
}


table Logout {
  section: string;
  name: string;
}


table Transfer {
  section: string;
  service: fb.protocol.internal.Service;
  id: ubyte;
  name: string?;
  force_shutdown: bool;
}


table Whisper {
  section: string;
  from: string;
  to: string;
  message: string;
}


table KickOut {
  section: string;
  uid: uint;
}

table Account {
  section: string;
  uid: uint;
}


table ChangePw {
  section: string;
  uid: uint;
  before: string;
  after: string;
  birthday: uint;
}


table InitCharacter {
  section: string;
  uid: uint;
  name: string;
  pw: string;
  hp: uint;
  mp: uint;
  map: ushort;
  x: ushort;
  y: ushort;
  role: ubyte;
}

table Authenticate {
  section: string;
  uid: uint;
  pw: string;
}


table Init {
  section: string;
  uid: uint;
}


table MakeCharacter {
  section: string;
  uid: uint;
  hair: ushort;
  gender: ubyte;
  nation: ubyte;
  creature: ubyte;
}


table ReserveName {
  section: string;
  name: string;
}


table Save {
  section: string;
  character: fb.protocol.internal.Character;
  items: [fb.protocol.internal.Item];
  spells: [fb.protocol.internal.Spell];
  achievements: [fb.protocol.internal.Achievement];
  quests: [fb.protocol.internal.Quest];
  received_system_mails: [fb.protocol.internal.SystemMailUser];
  storage_boxes: [fb.protocol.internal.StorageBox];
  storage_reward_marks: [fb.protocol.internal.StorageRewardMark];
}


table WriteArticle {
  section: string;
  article_section: uint;
  user: uint;
  title: string;
  contents: string;
}


table DeleteArticle {
  section: string;
  id: uint;
  article_section: uint;
  user: uint;
}

table WriteMail {
  section: string;
  sender: uint;
  user: string;
  title: string;
  contents: string;
  host: uint;
}

table DeleteMail {
  section: string;
  user: uint;
  id: ushort;
}


table SetOption {
  section: string;
  user: uint;
  type: ubyte;
  enabled: bool;
}

table CreateGroup {
  section: string;
  host: uint;
  master: uint;
  member: string;
}

table EnterGroup {
  section: string;
  host: uint;
  master: uint;
  member: string;
}

table BroadcastGroup {
  section: string;
  host: uint;
  group: uint;
  message: string;
  type: ubyte;
}

table LeaveGroup {
  section: string;
  host: uint;
  member: string;
}

table KickGroup {
  section: string;
  host: uint;
  kicker: string;
  target: string;
}

table DestroyGroup {
  section: string;
  host: uint;
  master: string;
}

table CreateClan {
  section: string;
  host: uint;
  master: uint;
  name: string;
}

table DestroyClan {
  section: string;
  host: uint;
  master: uint;
}

table JoinClan {
  section: string;
  host: uint;
  inviter_uid: uint;
  invitee_name: string;
}

table LeaveClan {
  section: string;
  host: uint;
  clan: uint;
  name: string;
}

table KickClan {
  section: string;
  host: uint;
  clan: uint;
  kicker: string;
  target: string;
}

table SetClanTitle {
  section: string;
  host: uint;
  changer: uint;
  title: string?;
}

table BroadcastClan {
  section: string;
  host: uint;
  clan: uint;
  message: string;
  type: ubyte;
}

table ChangeClanRole {
  section: string;
  host: uint;
  changer_uid: uint;
  target_name: string;
  clan: uint;
  new_role: uint;
}

table Broadcast {
  section: string;
  host: uint;
  message: string;
  type: ubyte;
}

table UpdateFriends {
  section: string;
  user: uint;
  names: [string];
}

table GetStoragePending {
  section: string;
  user: uint;
}

table WriteSystemMail {
  section: string;
  sender: uint;
  title: string;
  contents: string;
  expire_date: string?;
}

table Ban {
  section: string;
  name: string;
  reason: string;
  days: uint?;
}

table Unban {
  section: string;
  name: string;
}

table Heartbeat {
  section: string;
  service: fb.protocol.internal.Service;
  id: ubyte;
  name: string;
  ip: string;
  port: ushort;
}

table SetExpMultiplier {
  section: string;
  value: double;
}

table SetDropRateMultiplier {
  section: string;
  value: double;
}