include "internal.fbs";

namespace fb.protocol.internal.request;

table Shutdown {
  
}

table Login {
  uid: uint;
  name: string;
  host: ubyte;
}


table Logout {
  name: string;
}


table Transfer {
  service: fb.protocol.internal.Service;
  id: ubyte;
  name: string?;
  force_shutdown: bool;
}


table Whisper {
  from: string;
  to: string;
  message: string;
}


table KickOut {
  uid: uint;
}

table Account {
  uid: uint;
}


table ChangePw {
  uid: uint;
  before: string;
  after: string;
  birthday: uint;
}


table InitCharacter {
  uid: uint;
  name: string;
  pw: string;
  hp: uint;
  mp: uint;
  map: ushort;
  x: ushort;
  y: ushort;
  role: ubyte;
}

table Authenticate {
  uid: uint;
  pw: string;
}


table Init {
  uid: uint;
}


table MakeCharacter {
  uid: uint;
  hair: ushort;
  sex: ubyte;
  nation: ubyte;
  creature: ubyte;
}


table ReserveName {
  name: string;
}


table Save {
  character: fb.protocol.internal.Character;
  items: [fb.protocol.internal.Item];
  spells: [fb.protocol.internal.Spell];
  achievements: [fb.protocol.internal.Achievement];
}


table WriteArticle {
  section: uint;
  user: uint;
  title: string;
  contents: string;
}


table DeleteArticle {
  id: uint;
  user: uint;
}

table WriteMail {
  sender: uint;
  user: string;
  title: string;
  contents: string;
  host: uint;
}

table DeleteMail {
  user: uint;
  id: ushort;
}


table SetOption {
  user: uint;
  type: ubyte;
  enabled: bool;
}

table EnterGroup {
  master: uint;
  member: string;
}

table BroadcastGroup {
  host: uint;
  group: uint;
  message: string;
  type: ubyte;
}

table LeaveGroup {
  member: string;
}

table KickGroup {
  kicker: string;
  target: string;
}

table CreateClan {
  master: uint;
  name: string;
}

table DestroyClan {
  master: uint;
}

table JoinClan {
  host: uint;
  inviter_uid: uint;
  invitee_uid: uint;
}

table LeaveClan {
  host: uint;
  clan: uint;
  name: string;
}

table KickClan {
  host: uint;
  clan: uint;
  kicker: string;
  target: string;
}

table SetClanTitle {
  host: uint;
  changer: uint;
  title: string?;
}

table BroadcastClan {
  host: uint;
  clan: uint;
  message: string;
  type: ubyte;
}

table ChangeClanRole {
  host: uint;
  changer_uid: uint;
  target_name: string;
  clan: uint;
  new_role: uint;
}

table Broadcast {
  host: uint;
  message: string;
  type: ubyte;
}