include "internal.fbs";

namespace fb.protocol.internal.response;

table KickOut {
	uid: uint;
}



table Login {
  error: uint;
  logon: bool;
  ip: string;
  port: ushort;
}



table Logout {
  success: bool;
}



table Pong {
  
}



table Transfer {
  error: uint;
  ip: string;
  port: ushort;
}



table Whisper {
	from : string;
	to: string;
	message: string;
  host: uint;
  error: uint;
}

table DeleteArticle {
  result: int;
}


table GetArticle {
  article: fb.protocol.internal.Article;
  next: bool;
  success: bool;
}


table GetArticleList {
  summary_list: [fb.protocol.internal.ArticleSummary];
}


table WriteArticle {
  success: bool;
}


table ChangePw {
  error_code: uint;
}


table GetUid {
  uid: uint;
  success: bool;
}


table InitCharacter {
  success: bool;
}


table Authenticate {
  map: uint;
  error_code: uint;
}


table Init {
  character: fb.protocol.internal.Character;
  items: [fb.protocol.internal.Item];
  spells: [fb.protocol.internal.Spell];
  option: fb.protocol.internal.Option;
  group: fb.protocol.internal.Group;
}


table MakeCharacter {
  success: bool;
}


table ReserveName {
  uid: uint;
  success: bool;
}


table Save {
  success: bool;
}

table SetOption {
  success: bool;
}

table GetGroup {
  group: fb.protocol.internal.Group;
  error: uint;
}

table CreateGroup {
  group: fb.protocol.internal.Group;
  member: string;
  host: uint;
  action: fb.protocol.internal.GroupAction;
  error: uint;
}


table EnterGroup {
  id: uint;
  member: string;
  host: uint;
  error: uint;
}

table LeaveGroup {
  id: uint;
  group: fb.protocol.internal.Group;
  member: string;
  break_up: bool;
  host: uint;
  error: uint;
}