include "internal.fbs";

namespace fb.protocol.internal.response;

table Shutdown {
  
}

table KickOut {
  uid: uint;
  name: string;
}



table Login {
  error: uint;
  logon: bool;
  ip: string;
  port: ushort;
}



table Logout {
  success: bool;
}



table Transfer {
  error: uint;
  ip: string;
  port: ushort;
}



table Whisper {
  from : string;
  to: string;
  message: string;
  host: uint;
  error: uint;
}

table DeleteArticle {
  result: int;
}


table GetArticle {
  article: fb.protocol.internal.Article;
  next: bool;
  success: bool;
}


table GetArticleList {
  summary_list: [fb.protocol.internal.ArticleSummary];
}


table WriteArticle {
  success: bool;
}


table GetMail {
  mail: fb.protocol.internal.Mail;
  unread: ushort;
  error: uint;
}

table GetMailList {
  summary_list: [fb.protocol.internal.MailSummary];
  error: uint;
}

table WriteMail {
  mail: fb.protocol.internal.Mail;
  host: uint;
  unread: ushort;
  error: uint;
}

table DeleteMail {
  unread: uint;
  error: uint;
}


table ChangePw {
  error_code: uint;
}


table GetUid {
  uid: uint;
  success: bool;
}


table InitCharacter {
  success: bool;
}


table Authenticate {
  map: uint;
  error_code: uint;
}


table Init {
  character: fb.protocol.internal.Character;
  group: uint?;
  clan: uint?;
  items: [fb.protocol.internal.Item];
  spells: [fb.protocol.internal.Spell];
  option: fb.protocol.internal.Option;
  achievements: [fb.protocol.internal.Achievement];
  quests: [fb.protocol.internal.Quest];
  received_system_mails: [fb.protocol.internal.SystemMailUser];
  mail: uint;
}


table MakeCharacter {
  success: bool;
}


table ReserveName {
  uid: uint;
  success: bool;
}


table Save {
  success: bool;
}

table SetOption {
  success: bool;
}

table GetGroup {
  group: fb.protocol.internal.Group;
  error: uint;
}

table EnterGroup {
  group: fb.protocol.internal.Group;
  member: string;
  action: fb.protocol.internal.GroupAction;
  host: uint;
  error: uint;
}

table LeaveGroup {
  group: fb.protocol.internal.Group;
  member: string;
  action: fb.protocol.internal.GroupAction;
  host: uint;
  error: uint;
}

table KickGroup {
  group: fb.protocol.internal.Group;
  member: string;
  action: fb.protocol.internal.GroupAction;
  host: uint;
  error: uint;
}

table BroadcastGroup {
  host: uint;
  group: uint;
  message: string;
  type: ubyte;
  error: uint;
}

table GetClan {
  clan: fb.protocol.internal.Clan;
  members: [fb.protocol.internal.ClanMember];
  error: uint;
}

table CreateClan {
  clan: fb.protocol.internal.Clan;
  members: [fb.protocol.internal.ClanMember];
  error: uint;
}

table DestroyClan {
  error: uint;
}

table JoinClan {
  host: uint;
  clan: uint;
  member: fb.protocol.internal.ClanMember;
  error: uint;
}

table LeaveClan {
  host: uint;
  clan: uint;
  uid: uint;
  uname: string;
  error: uint;
}

table KickClan {
  host: uint;
  clan: uint;
  uid: uint;
  uname: string;
  error: uint;
}

table SetClanTitle {
  host: uint;
  clan: uint;
  title: string?;
  error: uint;
}

table BroadcastClan {
  host: uint;
  clan: uint;
  message: string;
  type: ubyte;
  error: uint;
}

table ChangeClanRole {
  host: uint;
  clan: uint;
  changer_uid: uint;
  changer_name: string;
  target_uid: uint;
  target_name: string;
  old_role: uint;
  new_role: uint;
  error: uint;
}

table Broadcast {
  host: uint;
  message: string;
  type: ubyte;
  error: uint;
}

table UpdateFriends
{
  error: uint;
}

table GetSystemMails {
  mails: [fb.protocol.internal.SystemMail];
  error: uint;
}

table WriteSystemMail {
  mail: fb.protocol.internal.SystemMail;
  error: uint;
}