namespace fb.protocol.internal;

enum Service : byte {
    Gateway,
    Login,
    Game
}

enum GroupAction : byte { 
    Create,
    Enter,
    Leave,
    Kick,
    BreakUp
}

table Position {
    x: ushort;
    y: ushort;
}

table Character {
    id: uint;
    name: string;
    pw: string;
    birth: uint?;
    role: ubyte;
    look: ushort;
    color: ushort;
    sex: ushort;
    nation: ushort;
    creature: ushort?;
    map: uint;
    position: Position;
    direction: ubyte;
    state: ubyte;
    class_type: ubyte;
    promotion: ubyte;
    level: ubyte;
    exp: uint;
    money: uint;
    deposited_money: uint;
    disguise: ushort?;
    hp: uint;
    base_hp: uint;
    additional_hp: uint;
    mp: uint;
    base_mp: uint;
    additional_mp: uint;
    weapon_color: ubyte?;
    helmet_color: ubyte?;
    armor_color: ubyte?;
    shield_color: ubyte?;
    ring_left_color: ubyte?;
    ring_right_color: ubyte?;
    aux_top_color: ubyte?;
    aux_bot_color: ubyte?;
    buffs: [Buff];
    title: string;
    updated_date: string;
}

table Item {
    user: uint;
    index: short;
    parts: short;
    stored: short;
    model: uint;
    count: ushort;
    durability: uint?;
    custom_name: string?;
}

table Spell {
    user: uint;
    slot: ubyte;
    model: uint;
    next: string;
}

table Buff
{
    model: uint;
    time: uint;
}

table Option {
    uid: uint;
    whisper: bool;
    group: bool;
    roar: bool;
    roar_worlds: bool;
    magic_effect: bool;
    weather_effect: bool;
    fixed_move: bool;
    trade: bool;
    fast_move: bool;
    effect_sound: bool;
    pk_protect: bool;
}

table ArticleSummary {
    id: uint;
    user: uint;
    user_name: string;
    title: string;
    created_date: string;
}

table Article {
    id: uint;
    user: uint;
    user_name: string;
    title: string;
    contents: string;
    created_date: string;
}

table MailSummary {
    id: ushort;
    user: uint;
    sender: uint;
    sender_name: string;
    read: bool;
    title: string;
    created_date: string;
}

table Mail {
    id: ushort;
    user: uint;
    sender: uint;
    sender_name: string;
    title: string;
    contents: string;
    read: bool;
    created_date: string;
}

table Group {
    id: uint;
    master: string;
    members: [string];
}

table Achievement {
    user: uint;
    model: uint;
    text: string?;
    icon: ubyte?;
    color: ushort?;
}

table Clan {
    id: uint;
    name: string;
    title: string?;
}

table ClanMember {
    uid: uint;
    name: string;
    role: uint;
}

table Quest {
    uid: uint;
    qid: uint;
    step: uint;
    progress: uint;
    param: string;
    completed: bool;
}