namespace fb.protocol.internal;

enum Service : byte { Gateway, Login, Game }

enum GroupAction : byte { Create, Enter, Leave, Kick, BreakUp }

table Position {
    x: ushort;
    y: ushort;
}

table Character {
    id: uint;
    name: string;
    pw: string;
    admin: bool;
    look: ushort;
    color: ushort;
    sex: ushort;
    nation: ushort;
    creature: ushort?;
    map: uint;
    position: Position;
    direction: ubyte;
    state: ubyte;
    class_type: ubyte;
    promotion: ubyte;
    level: ubyte;
    exp: uint;
    money: uint;
    deposited_money: uint;
    disguise: ushort?;
    hp: uint;
    base_hp: uint;
    additional_hp: uint;
    mp: uint;
    base_mp: uint;
    additional_mp: uint;
    weapon_color: ubyte?;
    helmet_color: ubyte?;
    armor_color: ubyte?;
    shield_color: ubyte?;
    ring_left_color: ubyte?;
    ring_right_color: ubyte?;
    aux_top_color: ubyte?;
    aux_bot_color: ubyte?;
    updated_date: string;
}

table Item {
    user: uint;
    index: short;
    parts: short;
    deposited: short;
    model: uint;
    count: ushort;
    durability: uint?;
    custom_name: string?;
}

table Spell {
    user: uint;
    slot: ubyte;
    model: uint;
}

table Option {
    uid: uint;
    whisper: bool;
    group: bool;
    roar: bool;
    roar_worlds: bool;
    magic_effect: bool;
    weather_effect: bool;
    fixed_move: bool;
    trade: bool;
    fast_move: bool;
    effect_sound: bool;
    pk_protect: bool;
}

table ArticleSummary {
    id: uint;
    user: uint;
    user_name: string;
    title: string;
    created_date: string;
}

table Article {
    id: uint;
    user: uint;
    user_name: string;
    title: string;
    contents: string;
    created_date: string;
}

table MailSummary {
    id: ushort;
    user: uint;
    sender: uint;
    sender_name: string;
    read: bool;
    title: string;
    created_date: string;
}

table Mail {
    id: ushort;
    user: uint;
    sender: uint;
    sender_name: string;
    title: string;
    contents: string;
    read: bool;
    created_date: string;
}

table Group {
    id: uint;
    master: string;
    members: [string];
}

table Trace {
    user: uint;
    model: uint;
    text: string?;
}

table Clan {
    id: uint;
    name: string;
    title: string?;
}

table ClanMember {
    uid: uint;
    name: string;
    position: uint;
}