include "marketplace.fbs";

namespace fb.protocol.marketplace.request;

table List {
    world: uint;
    character_id: uint;
    listing_id: string;
    item: fb.protocol.marketplace.Item;
    price: uint;
}

table Cancel {
    world: uint;
    character_id: uint;
    listing_id: string;
}

table Purchase {
    world: uint;
    buyer_id: uint;
    listing_id: string;
    purchase_count: ushort;
    purchase_id: string;
}

table Search {
    item_name: string?;
    min_price: uint?;
    max_price: uint?;
    seller_id: uint?;
    sort_by: string?;
    page: uint;
}

table GetListings {
    listing_ids: [string];
    buyer_id: uint?;
}

table GetPurchases {
    purchase_ids: [string];
}

