include "marketplace.fbs";

namespace fb.protocol.marketplace.request;

table List {
    world: uint;
    character_id: uint;
    listing_id: ulong;
    item: fb.protocol.marketplace.Item;
    price: ulong;
    deadline: long;
}

table AbortList {
    world: uint;
    character_id: uint;
    listing_id: ulong;
    item: fb.protocol.marketplace.Item;
    price: ulong;
}

table Cancel {
    world: uint;
    character_id: uint;
    listing_id: ulong;
}

table Purchase {
    world: uint;
    buyer_id: uint;
    listing_id: ulong;
    purchase_count: ushort;
    purchase_id: ulong;
    deadline: long;
}

table AbortPurchase {
    world: uint;
    buyer_id: uint;
    listing_id: ulong;
    purchase_id: ulong;
}

table Search {
    item_name: string?;
    min_price: ulong?;
    max_price: ulong?;
    seller_id: uint?;
    sort_by: string?;
    page: uint;
}

table GetListings {
    listing_ids: [ulong];
    buyer_id: uint?;
}
