include "matchmaking.fbs";

namespace fb.protocol.matchmaking.mq;

table MatchProposed {
    match_id: ulong;
    match_type: uint;
    confirm_deadline: string;
    teams: [fb.protocol.matchmaking.MatchTeam];
}

table MatchReady {
    match_id: ulong;
    match_type: uint;
    teams: [fb.protocol.matchmaking.MatchTeam];
}

table MatchDissolved {
    match_id: ulong;
    match_type: uint;
    reason: ubyte;
    ticket_outcomes: [fb.protocol.matchmaking.TicketOutcome];
}

table TicketRemoved {
    match_type: uint;
    ticket_id: ulong;
    members: [fb.protocol.matchmaking.TicketMember];
}
