// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DBRESPONSEBOARD_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_
#define FLATBUFFERS_GENERATED_DBRESPONSEBOARD_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "db_generated.h"

namespace fb {
namespace protocol {
namespace db {
namespace response {
namespace origin {

struct Board;
struct BoardBuilder;

struct Board FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoardBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BOARD = 4
  };
  const fb::protocol::db::origin::Board *board() const {
    return GetPointer<const fb::protocol::db::origin::Board *>(VT_BOARD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BOARD) &&
           verifier.VerifyTable(board()) &&
           verifier.EndTable();
  }
};

struct BoardBuilder {
  typedef Board Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_board(::flatbuffers::Offset<fb::protocol::db::origin::Board> board) {
    fbb_.AddOffset(Board::VT_BOARD, board);
  }
  explicit BoardBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Board> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Board>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Board> CreateBoard(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::db::origin::Board> board = 0) {
  BoardBuilder builder_(_fbb);
  builder_.add_board(board);
  return builder_.Finish();
}

inline const fb::protocol::db::response::origin::Board *GetBoard(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::db::response::origin::Board>(buf);
}

inline const fb::protocol::db::response::origin::Board *GetSizePrefixedBoard(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::db::response::origin::Board>(buf);
}

inline bool VerifyBoardBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::db::response::origin::Board>(nullptr);
}

inline bool VerifySizePrefixedBoardBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::db::response::origin::Board>(nullptr);
}

inline void FinishBoardBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::origin::Board> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBoardBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::origin::Board> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace origin
}  // namespace response
}  // namespace db
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_DBRESPONSEBOARD_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_
