// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DBRESPONSELOGIN_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_
#define FLATBUFFERS_GENERATED_DBRESPONSELOGIN_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "db_generated.h"

namespace fb {
namespace protocol {
namespace db {
namespace response {
namespace origin {

struct Login;
struct LoginBuilder;

struct Login FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHARACTER = 4,
    VT_ITEMS = 6,
    VT_SPELLS = 8
  };
  const fb::protocol::db::origin::Character *character() const {
    return GetPointer<const fb::protocol::db::origin::Character *>(VT_CHARACTER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Item>> *items() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Item>> *>(VT_ITEMS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>> *spells() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>> *>(VT_SPELLS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CHARACTER) &&
           verifier.VerifyTable(character()) &&
           VerifyOffset(verifier, VT_ITEMS) &&
           verifier.VerifyVector(items()) &&
           verifier.VerifyVectorOfTables(items()) &&
           VerifyOffset(verifier, VT_SPELLS) &&
           verifier.VerifyVector(spells()) &&
           verifier.VerifyVectorOfTables(spells()) &&
           verifier.EndTable();
  }
};

struct LoginBuilder {
  typedef Login Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_character(::flatbuffers::Offset<fb::protocol::db::origin::Character> character) {
    fbb_.AddOffset(Login::VT_CHARACTER, character);
  }
  void add_items(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Item>>> items) {
    fbb_.AddOffset(Login::VT_ITEMS, items);
  }
  void add_spells(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>>> spells) {
    fbb_.AddOffset(Login::VT_SPELLS, spells);
  }
  explicit LoginBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Login> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Login>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Login> CreateLogin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::db::origin::Character> character = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Item>>> items = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>>> spells = 0) {
  LoginBuilder builder_(_fbb);
  builder_.add_spells(spells);
  builder_.add_items(items);
  builder_.add_character(character);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Login> CreateLoginDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<fb::protocol::db::origin::Character> character = 0,
    const std::vector<::flatbuffers::Offset<fb::protocol::db::origin::Item>> *items = nullptr,
    const std::vector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>> *spells = nullptr) {
  auto items__ = items ? _fbb.CreateVector<::flatbuffers::Offset<fb::protocol::db::origin::Item>>(*items) : 0;
  auto spells__ = spells ? _fbb.CreateVector<::flatbuffers::Offset<fb::protocol::db::origin::Spell>>(*spells) : 0;
  return fb::protocol::db::response::origin::CreateLogin(
      _fbb,
      character,
      items__,
      spells__);
}

inline const fb::protocol::db::response::origin::Login *GetLogin(const void *buf) {
  return ::flatbuffers::GetRoot<fb::protocol::db::response::origin::Login>(buf);
}

inline const fb::protocol::db::response::origin::Login *GetSizePrefixedLogin(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<fb::protocol::db::response::origin::Login>(buf);
}

inline bool VerifyLoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<fb::protocol::db::response::origin::Login>(nullptr);
}

inline bool VerifySizePrefixedLoginBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<fb::protocol::db::response::origin::Login>(nullptr);
}

inline void FinishLoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::origin::Login> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLoginBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<fb::protocol::db::response::origin::Login> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace origin
}  // namespace response
}  // namespace db
}  // namespace protocol
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_DBRESPONSELOGIN_FB_PROTOCOL_DB_RESPONSE_ORIGIN_H_
