#ifndef FB_GAME_HANDLER_H
#define FB_GAME_HANDLER_H

#include <fb/game/handler/protocol/login.h>
#include <fb/game/handler/protocol/direction.h>
#include <fb/game/handler/protocol/exit.h>
#include <fb/game/handler/protocol/update_move.h>
#include <fb/game/handler/protocol/move.h>
#include <fb/game/handler/protocol/attack.h>
#include <fb/game/handler/protocol/loot.h>
#include <fb/game/handler/protocol/emotion.h>
#include <fb/game/handler/protocol/map_update.h>
#include <fb/game/handler/protocol/update_screen.h>
#include <fb/game/handler/protocol/item_active.h>
#include <fb/game/handler/protocol/item_inactive.h>
#include <fb/game/handler/protocol/item_drop.h>
#include <fb/game/handler/protocol/item_drop_money.h>
#include <fb/game/handler/protocol/front_info.h>
#include <fb/game/handler/protocol/friends.h>
#include <fb/game/handler/protocol/self_info.h>
#include <fb/game/handler/protocol/update_option.h>
#include <fb/game/handler/protocol/click.h>
#include <fb/game/handler/protocol/item_info.h>
#include <fb/game/handler/protocol/item_combine.h>
#include <fb/game/handler/protocol/trade.h>
#include <fb/game/handler/protocol/group.h>
#include <fb/game/handler/protocol/user_list.h>
#include <fb/game/handler/protocol/chat.h>
#include <fb/game/handler/protocol/bulletin.h>
#include <fb/game/handler/protocol/swap.h>
#include <fb/game/handler/protocol/dialog.h>
#include <fb/game/handler/protocol/item_throws.h>
#include <fb/game/handler/protocol/spell_cast.h>
#include <fb/game/handler/protocol/door.h>
#include <fb/game/handler/protocol/whisper.h>
#include <fb/game/handler/protocol/map_world.h>
#include <fb/game/handler/protocol/miss.h>
#include <fb/game/handler/protocol/give_item.h>
#include <fb/game/handler/protocol/give_money.h>
#include <fb/game/handler/protocol/post.h>

#include <fb/game/handler/amqp/kick_out.h>
#include <fb/game/handler/amqp/whisper.h>
#include <fb/game/handler/amqp/shutdown.h>
#include <fb/game/handler/amqp/broadcast.h>
#include <fb/game/handler/amqp/create_group.h>
#include <fb/game/handler/amqp/updated_group.h>
#include <fb/game/handler/amqp/destroy_group.h>
#include <fb/game/handler/amqp/create_clan.h>
#include <fb/game/handler/amqp/destroy_clan.h>
#include <fb/game/handler/amqp/updated_clan.h>
#include <fb/game/handler/amqp/broadcast_clan.h>
#include <fb/game/handler/amqp/write_mail.h>
#include <fb/game/handler/amqp/write_system_mail.h>
#include <fb/game/handler/amqp/ban.h>
#include <fb/game/handler/amqp/broadcast_save.h>
#include <fb/game/handler/amqp/storage_pending_personal.h>
#include <fb/game/handler/amqp/storage_pending_fetch.h>

#include <fb/game/handler/npc_interaction/appreciate.h>
#include <fb/game/handler/npc_interaction/buy.h>
#include <fb/game/handler/npc_interaction/buy_list.h>
#include <fb/game/handler/npc_interaction/buy_price.h>
#include <fb/game/handler/npc_interaction/deposit_money.h>
#include <fb/game/handler/npc_interaction/retrieve_item.h>
#include <fb/game/handler/npc_interaction/repair.h>
#include <fb/game/handler/npc_interaction/rename_weapon.h>
#include <fb/game/handler/npc_interaction/sell.h>
#include <fb/game/handler/npc_interaction/sell_list.h>
#include <fb/game/handler/npc_interaction/sell_price.h>
#include <fb/game/handler/npc_interaction/show_deposited_money.h>
#include <fb/game/handler/npc_interaction/store_item.h>
#include <fb/game/handler/npc_interaction/store_item_count.h>
#include <fb/game/handler/npc_interaction/store_item_list.h>
#include <fb/game/handler/npc_interaction/revive.h>
#include <fb/game/handler/npc_interaction/withdraw_money.h>

#include <fb/game/handler/timer/heart_beat.h>
#include <fb/game/handler/timer/update_time.h>
#include <fb/game/handler/timer/announce.h>
#include <fb/game/handler/timer/buff_timer.h>
#include <fb/game/handler/timer/gear_timer.h>
#include <fb/game/handler/timer/mob_action_timer.h>
#include <fb/game/handler/timer/mob_respawn_timer.h>
#include <fb/game/handler/timer/soliloquy_timer.h>
#include <fb/game/handler/timer/save_timer.h>
#include <fb/game/handler/timer/marketplace_restore_timer.h>

#endif // FB_GAME_HANDLER_H