#ifndef __PROTOCOL_GAME_H__
#define __PROTOCOL_GAME_H__

#include <fb/protocol/transfer.h>
#include <fb/game/protocol/bulletin/bulletin.h>
#include <fb/game/protocol/bulletin/bulletin_sections.h>
#include <fb/game/protocol/bulletin/bulletin_articles.h>
#include <fb/game/protocol/bulletin/bulletin_article.h>
#include <fb/game/protocol/bulletin/bulletin_message.h>
#include <fb/game/protocol/bulletin/bulletin_mails.h>
#include <fb/game/protocol/bulletin/bulletin_mail.h>
#include <fb/game/protocol/exit.h>
#include <fb/game/protocol/update_move.h>
#include <fb/game/protocol/attack.h>
#include <fb/game/protocol/loot.h>
#include <fb/game/protocol/emotion.h>
#include <fb/game/protocol/update_screen.h>
#include <fb/game/protocol/front_info.h>
#include <fb/game/protocol/friends.h>
#include <fb/game/protocol/self_info.h>
#include <fb/game/protocol/update_option.h>
#include <fb/game/protocol/click.h>
#include <fb/game/protocol/trade.h>
#include <fb/game/protocol/group.h>
#include <fb/game/protocol/user_list.h>
#include <fb/game/protocol/swap.h>
#include <fb/game/protocol/dialog.h>
#include <fb/game/protocol/door.h>
#include <fb/game/protocol/login.h>
#include <fb/game/protocol/whisper.h>
#include <fb/game/protocol/item/item_active.h>
#include <fb/game/protocol/item/item_inactive.h>
#include <fb/game/protocol/item/item_drop.h>
#include <fb/game/protocol/item/item_drop_money.h>
#include <fb/game/protocol/item/item_combine.h>
#include <fb/game/protocol/item/item_throws.h>
#include <fb/game/protocol/item/item_info.h>
#include <fb/game/protocol/item/item_tip.h>
#include <fb/game/protocol/item/item_update.h>
#include <fb/game/protocol/item/item_update_slot.h>
#include <fb/game/protocol/item/item_remove.h>
#include <fb/game/protocol/item/item_unequip.h>
#include <fb/game/protocol/map/map_update.h>
#include <fb/game/protocol/map/map_world.h>
#include <fb/game/protocol/map/map_bgm.h>
#include <fb/game/protocol/map/map_config.h>
#include <fb/game/protocol/map/map_worlds.h>
#include <fb/game/protocol/spell/spell_cast.h>
#include <fb/game/protocol/spell/spell_buff.h>
#include <fb/game/protocol/spell/spell_unbuff.h>
#include <fb/game/protocol/spell/spell_update.h>
#include <fb/game/protocol/spell/spell_remove.h>
#include <fb/game/protocol/spell/spell_delay.h>
#include <fb/game/protocol/character/update_external.h>
#include <fb/game/protocol/character/id.h>
#include <fb/game/protocol/character/update_internal.h>
#include <fb/game/protocol/character/position.h>
#include <fb/game/protocol/character/internal_info.h>
#include <fb/game/protocol/character/external_info.h>
#include <fb/game/protocol/character/option.h>
#include <fb/game/protocol/dialog/dialog.h>
#include <fb/game/protocol/dialog/dialog_menu.h>
#include <fb/game/protocol/dialog/dialog_list.h>
#include <fb/game/protocol/dialog/dialog_slot.h>
#include <fb/game/protocol/dialog/dialog_item.h>
#include <fb/game/protocol/dialog/dialog_input.h>
#include <fb/game/protocol/dialog/dialog_input_ext.h>
#include <fb/game/protocol/init.h>
#include <fb/game/protocol/message.h>
#include <fb/game/protocol/user_list.h>
#include <fb/game/protocol/time.h>
#include <fb/game/protocol/weather.h>
#include <fb/game/protocol/bright.h>
#include <fb/game/protocol/timer.h>
#include <fb/game/protocol/save.h>
#include <fb/game/protocol/ad.h>
#include <fb/game/protocol/web.h>
#include <fb/game/protocol/give.h>
#include <fb/game/protocol/post.h>
#include <fb/game/protocol/life/action.h>
#include <fb/game/protocol/life/update_hp.h>
#include <fb/game/protocol/life/die.h>
#include <fb/game/protocol/object/direction.h>
#include <fb/game/protocol/object/update.h>
#include <fb/game/protocol/object/hide.h>
#include <fb/game/protocol/object/chat.h>
#include <fb/game/protocol/object/move.h>
#include <fb/game/protocol/object/sound.h>
#include <fb/game/protocol/object/effect.h>
#include <fb/game/protocol/object/miss.h>
#include <fb/game/protocol/trade/trade_dialog.h>
#include <fb/game/protocol/trade/trade_upload.h>
#include <fb/game/protocol/trade/trade_bundle.h>
#include <fb/game/protocol/trade/trade_money.h>
#include <fb/game/protocol/trade/trade_close.h>
#include <fb/game/protocol/trade/trade_lock.h>

#endif