#ifndef __PROTOCOL_GAME_H__
#define __PROTOCOL_GAME_H__

#include <fb/protocol/transfer.h>
#include <fb/game/protocol/bulletin.h>
#include <fb/game/protocol/bulletin/sections.h>
#include <fb/game/protocol/bulletin/articles.h>
#include <fb/game/protocol/bulletin/article.h>
#include <fb/game/protocol/bulletin/message.h>
#include <fb/game/protocol/bulletin/mails.h>
#include <fb/game/protocol/bulletin/mail.h>
#include <fb/game/protocol/exit.h>
#include <fb/game/protocol/update_move.h>
#include <fb/game/protocol/attack.h>
#include <fb/game/protocol/loot.h>
#include <fb/game/protocol/emotion.h>
#include <fb/game/protocol/screen_refresh.h>
#include <fb/game/protocol/front_info.h>
#include <fb/game/protocol/friends.h>
#include <fb/game/protocol/self_info.h>
#include <fb/game/protocol/update_option.h>
#include <fb/game/protocol/click.h>
#include <fb/game/protocol/trade.h>
#include <fb/game/protocol/group.h>
#include <fb/game/protocol/user_list.h>
#include <fb/game/protocol/swap.h>
#include <fb/game/protocol/dialog.h>
#include <fb/game/protocol/door.h>
#include <fb/game/protocol/login.h>
#include <fb/game/protocol/whisper.h>
#include <fb/game/protocol/item/active.h>
#include <fb/game/protocol/item/inactive.h>
#include <fb/game/protocol/item/drop.h>
#include <fb/game/protocol/item/drop_money.h>
#include <fb/game/protocol/item/combine.h>
#include <fb/game/protocol/item/throws.h>
#include <fb/game/protocol/item/info.h>
#include <fb/game/protocol/item/tip.h>
#include <fb/game/protocol/item/update.h>
#include <fb/game/protocol/item/update_slot.h>
#include <fb/game/protocol/item/remove.h>
#include <fb/game/protocol/item/unequip.h>
#include <fb/game/protocol/map/update.h>
#include <fb/game/protocol/map/world.h>
#include <fb/game/protocol/audio.h>
#include <fb/game/protocol/map/bgm.h>
#include <fb/game/protocol/map/config.h>
#include <fb/game/protocol/map/worlds.h>
#include <fb/game/protocol/spell/cast.h>
#include <fb/game/protocol/spell/buff.h>
#include <fb/game/protocol/spell/unbuff.h>
#include <fb/game/protocol/spell/update.h>
#include <fb/game/protocol/spell/remove.h>
#include <fb/game/protocol/spell/delay.h>
#include <fb/game/protocol/character/show.h>
#include <fb/game/protocol/character/update_external.h>
#include <fb/game/protocol/character/id.h>
#include <fb/game/protocol/character/update_internal.h>
#include <fb/game/protocol/character/position.h>
#include <fb/game/protocol/character/internal_info.h>
#include <fb/game/protocol/character/external_info.h>
#include <fb/game/protocol/character/option.h>
#include <fb/game/protocol/dialog/menu.h>
#include <fb/game/protocol/dialog/list.h>
#include <fb/game/protocol/dialog/slot.h>
#include <fb/game/protocol/dialog/item.h>
#include <fb/game/protocol/dialog/input.h>
#include <fb/game/protocol/dialog/input_ext.h>
#include <fb/game/protocol/dialog/dialog_pursuit.h>
#include <fb/game/protocol/dialog/dialog_spell.h>
#include <fb/game/protocol/dialog/dialog_dual_field.h>
#include <fb/game/protocol/dialog/dialog_email.h>
#include <fb/game/protocol/dialog/dialog_0x30_10.h>
#include <fb/game/protocol/init.h>
#include <fb/game/protocol/message.h>
#include <fb/game/protocol/user_list.h>
#include <fb/game/protocol/time.h>
#include <fb/game/protocol/weather.h>
#include <fb/game/protocol/bright.h>
#include <fb/game/protocol/timer.h>
#include <fb/game/protocol/save.h>
#include <fb/game/protocol/ad.h>
#include <fb/game/protocol/web.h>
#include <fb/game/protocol/give.h>
#include <fb/game/protocol/post.h>
#include <fb/game/protocol/life/action.h>
#include <fb/game/protocol/life/update_hp.h>
#include <fb/game/protocol/life/die.h>
#include <fb/game/protocol/object/direction.h>
#include <fb/game/protocol/object/update.h>
#include <fb/game/protocol/object/hide.h>
#include <fb/game/protocol/object/chat.h>
#include <fb/game/protocol/object/move.h>
#include <fb/game/protocol/object/move_confirm.h>
#include <fb/game/protocol/object/move_blocked.h>
#include <fb/game/protocol/object/sound.h>
#include <fb/game/protocol/object/effect.h>
#include <fb/game/protocol/object/miss.h>
#include <fb/game/protocol/trade/dialog.h>
#include <fb/game/protocol/trade/upload.h>
#include <fb/game/protocol/trade/bundle.h>
#include <fb/game/protocol/trade/money.h>
#include <fb/game/protocol/trade/close.h>
#include <fb/game/protocol/trade/lock.h>
#include <fb/game/protocol/collection.h>
#include <fb/game/protocol/unknown_4f.h>
#include <fb/game/protocol/unknown_54.h>
#include <fb/game/protocol/notice.h>
#include <fb/game/protocol/browser.h>
#include <fb/game/protocol/group_portrait.h>
#include <fb/game/protocol/web_map.h>
#include <fb/game/protocol/update_cc.h>
#include <fb/game/protocol/object/move_confirm_noscroll.h>
#include <fb/game/protocol/ui_screen.h>
#include <fb/game/protocol/item_throw_confirm.h>
#include <fb/game/protocol/freeze.h>
#include <fb/game/protocol/friends_sync.h>
#include <fb/game/protocol/c2s_relay.h>
#include <fb/game/protocol/user_info.h>
#include <fb/game/protocol/user_info_submit.h>
#include <fb/game/protocol/popup_message.h>
#include <fb/game/protocol/popup_input_submit.h>
#include <fb/game/protocol/holyday_screen.h>
#include <fb/game/protocol/ping.h>
#include <fb/game/protocol/pong.h>
#include <fb/game/protocol/screen_refresh_complete.h>

#endif
