// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetClan : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GetClan GetRootAsGetClan(ByteBuffer _bb) { return GetRootAsGetClan(_bb, new GetClan()); }
  public static GetClan GetRootAsGetClan(ByteBuffer _bb, GetClan obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyGetClan(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, GetClanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetClan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.protocol._internal.raw.Clan? Clan { get { int o = __p.__offset(4); return o != 0 ? (fb.protocol._internal.raw.Clan?)(new fb.protocol._internal.raw.Clan()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public fb.protocol._internal.raw.ClanMember? Members(int j) { int o = __p.__offset(6); return o != 0 ? (fb.protocol._internal.raw.ClanMember?)(new fb.protocol._internal.raw.ClanMember()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MembersLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public uint Error { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.response.raw.GetClan> CreateGetClan(FlatBufferBuilder builder,
      Offset<fb.protocol._internal.raw.Clan> clanOffset = default(Offset<fb.protocol._internal.raw.Clan>),
      VectorOffset membersOffset = default(VectorOffset),
      uint error = 0) {
    builder.StartTable(3);
    GetClan.AddError(builder, error);
    GetClan.AddMembers(builder, membersOffset);
    GetClan.AddClan(builder, clanOffset);
    return GetClan.EndGetClan(builder);
  }

  public static void StartGetClan(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddClan(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.Clan> clanOffset) { builder.AddOffset(0, clanOffset.Value, 0); }
  public static void AddMembers(FlatBufferBuilder builder, VectorOffset membersOffset) { builder.AddOffset(1, membersOffset.Value, 0); }
  public static VectorOffset CreateMembersVector(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.ClanMember>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMembersVectorBlock(FlatBufferBuilder builder, Offset<fb.protocol._internal.raw.ClanMember>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMembersVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<fb.protocol._internal.raw.ClanMember>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMembersVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<fb.protocol._internal.raw.ClanMember>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMembersVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(2, error, 0); }
  public static Offset<fb.protocol._internal.response.raw.GetClan> EndGetClan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.GetClan>(o);
  }
  public static void FinishGetClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.GetClan> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedGetClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.GetClan> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class GetClanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Clan*/, fb.protocol._internal.raw.ClanVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Members*/, fb.protocol._internal.raw.ClanMemberVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
