// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct JoinClan : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static JoinClan GetRootAsJoinClan(ByteBuffer _bb) { return GetRootAsJoinClan(_bb, new JoinClan()); }
  public static JoinClan GetRootAsJoinClan(ByteBuffer _bb, JoinClan obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyJoinClan(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, JoinClanVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public JoinClan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Clan { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Uid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Uname { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetUnameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetUnameArray() { return __p.__vector_as_array<byte>(8); }
  public uint Error { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol._internal.response.raw.JoinClan> CreateJoinClan(FlatBufferBuilder builder,
      uint clan = 0,
      uint uid = 0,
      StringOffset unameOffset = default(StringOffset),
      uint error = 0) {
    builder.StartTable(4);
    JoinClan.AddError(builder, error);
    JoinClan.AddUname(builder, unameOffset);
    JoinClan.AddUid(builder, uid);
    JoinClan.AddClan(builder, clan);
    return JoinClan.EndJoinClan(builder);
  }

  public static void StartJoinClan(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddClan(FlatBufferBuilder builder, uint clan) { builder.AddUint(0, clan, 0); }
  public static void AddUid(FlatBufferBuilder builder, uint uid) { builder.AddUint(1, uid, 0); }
  public static void AddUname(FlatBufferBuilder builder, StringOffset unameOffset) { builder.AddOffset(2, unameOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, uint error) { builder.AddUint(3, error, 0); }
  public static Offset<fb.protocol._internal.response.raw.JoinClan> EndJoinClan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.JoinClan>(o);
  }
  public static void FinishJoinClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.JoinClan> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedJoinClanBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.JoinClan> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class JoinClanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Clan*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Uid*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Uname*/, false)
      && verifier.VerifyField(tablePos, 10 /*Error*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
