// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol._internal.response.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Pong : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Pong GetRootAsPong(ByteBuffer _bb) { return GetRootAsPong(_bb, new Pong()); }
  public static Pong GetRootAsPong(ByteBuffer _bb, Pong obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPong(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PongVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Pong __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartPong(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<fb.protocol._internal.response.raw.Pong> EndPong(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol._internal.response.raw.Pong>(o);
  }
  public static void FinishPongBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.Pong> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPongBuffer(FlatBufferBuilder builder, Offset<fb.protocol._internal.response.raw.Pong> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PongVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
