using Marketplace.Model;

namespace Marketplace.Services;

/// <summary>
/// Interface for marketplace service functionality.
/// Provides abstraction for single-database and multi-database (sharded) implementations.
/// </summary>
public interface IMarketplaceService
{
    /// <summary>
    /// Creates a new marketplace listing using a listing ID generated by game server.
    /// </summary>
    /// <param name="listingId">The listing ID (UUID string generated by game server).</param>
    /// <returns>MarketplaceListing if successful; throws LogicException if listing ID already exists.</returns>
    /// <exception cref="Http.LogicException">Thrown when listing ID already exists.</exception>
    Task<MarketplaceListing> ListItemAsync(
        uint characterId,
        string listingId,
        uint itemModel,
        ushort remainingCount,
        uint? itemDurability,
        string itemCustomName,
        uint price,
        TimeSpan expireTime);

    /// <summary>
    /// Cancels a marketplace listing.
    /// </summary>
    /// <exception cref="Http.LogicException">Thrown when listing is not found, user is not the owner, or listing is already cancelled/sold.</exception>
    Task CancelListingAsync(uint characterId, string listingId);

    /// <summary>
    /// Purchases items from a marketplace listing.
    /// Supports partial purchases and uses database transaction with row locking to prevent concurrent purchases.
    /// </summary>
    /// <param name="buyerId">The unique identifier of the buyer.</param>
    /// <param name="listingId">The unique identifier of the listing.</param>
    /// <param name="purchaseCount">The number of items to purchase.</param>
    /// <param name="purchaseId">The purchase ID (UUID string generated by game server).</param>
    /// <returns>PurchaseItemResult containing listing, actualPurchaseCount, and refundAmount.</returns>
    /// <exception cref="Http.LogicException">Thrown when purchase ID already exists, listing not found, or insufficient stock.</exception>
    Task<PurchaseItemResult> PurchaseItemAsync(
        uint buyerId,
        string listingId,
        ushort purchaseCount,
        string purchaseId);

    /// <summary>
    /// Searches marketplace listings.
    /// </summary>
    /// <returns>MarketplaceSearchResult.</returns>
    Task<MarketplaceSearchResult> SearchItemsAsync(MarketplaceSearchOption option);

    /// <summary>
    /// Gets a listing by ID.
    /// </summary>
    /// <returns>MarketplaceListing if found; null if not found.</returns>
    Task<MarketplaceListing> GetListingByIdAsync(string listingId);

    /// <summary>
    /// Gets multiple listings by their IDs.
    /// Optionally includes purchase information for a specific buyer.
    /// </summary>
    /// <param name="listingIds">List of listing IDs to retrieve.</param>
    /// <param name="buyerId">Optional buyer ID to include purchase information for.</param>
    /// <returns>List of ListingWithPurchase objects found.</returns>
    Task<List<ListingWithPurchase>> GetListingsByIdsAsync(
        List<string> listingIds,
        uint? buyerId = null);

    /// <summary>
    /// Gets multiple purchase records by their IDs.
    /// </summary>
    /// <param name="purchaseIds">List of purchase IDs to retrieve.</param>
    /// <returns>Dictionary mapping purchase IDs to purchase records.</returns>
    Task<Dictionary<string, MarketplacePurchase>> GetPurchasesByIdsAsync(List<string> purchaseIds);
}

