using Fb.Model;
using Fb.Model.EnumValue;
using Http;
using Http.Reepository;
using Http.Service;
using Marketplace.Extension;
using Marketplace.Model;

namespace Marketplace.Services;

/// <summary>
/// Result class for PurchaseItemAsync method.
/// </summary>
public class PurchaseItemResult
{
    public MarketplaceListing Listing { get; set; }
    public ushort ActualPurchaseCount { get; set; }
    public uint RefundAmount { get; set; }
}

/// <summary>
/// Result class for GetListingsByIdsAsync method.
/// </summary>
public class ListingWithPurchase
{
    public MarketplaceListing Listing { get; set; }
    public MarketplacePurchase Purchase { get; set; }
}

/// <summary>
/// Provides marketplace service functionality for single-database implementation.
/// Handles marketplace listings, purchases, searches, and transaction management.
/// </summary>
public class MarketplaceService : IMarketplaceService
{
    private readonly MarketplaceRepository _repository;
    private readonly MarketplacePurchaseRepository _purchaseRepository;
    private readonly IConfiguration _configuration;
    private readonly StorageService _storageService;
    private readonly DbContext _dbContext;
    private readonly LogService _logService;
    private readonly uint _minFee;

    public MarketplaceService(
        MarketplaceRepository repository,
        MarketplacePurchaseRepository purchaseRepository,
        IConfiguration configuration,
        StorageService storageService,
        DbContext dbContext,
        LogService logService)
    {
        _repository = repository;
        _purchaseRepository = purchaseRepository;
        _configuration = configuration;
        _storageService = storageService;
        _dbContext = dbContext;
        _logService = logService;
        _minFee = _configuration.GetValue<uint>("Marketplace:MinFee", 100);
    }

    /// <summary>
    /// Creates a new marketplace listing using a listing ID generated by game server.
    /// </summary>
    /// <param name="listingId">The listing ID (UUID string generated by game server).</param>
    /// <returns>MarketplaceListing if successful; throws LogicException if listing ID already exists.</returns>
    /// <exception cref="LogicException">Thrown when listing ID already exists.</exception>
    public async Task<MarketplaceListing> ListItemAsync(
        uint characterId,
        string listingId,
        uint itemModel,
        ushort remainingCount,
        uint? itemDurability,
        string itemCustomName,
        uint price,
        ushort expireHours)
    {
        // Check if listing ID already exists
        if (await _repository.CheckListingIdExistsAsync(listingId))
        {
            _logService?.Write("marketplace_list_failed", new
            {
                character_id = characterId,
                listing_id = listingId,
                error = "listing_id_already_exists"
            });
            throw new LogicException(ErrorCode.MarketplaceIdAlreadyExists);
        }

        // Log before creating listing
        _logService?.Write("marketplace_list", new
        {
            character_id = characterId,
            listing_id = listingId,
            item_model = itemModel,
            remaining_count = remainingCount,
            price = price,
            expire_hours = expireHours
        });

        // Create listing with listing_id as the primary key
        await _repository.CreateListingAsync(
            listingId,
            characterId,
            itemModel,
            remainingCount,
            itemDurability,
            itemCustomName,
            price,
            DateTime.UtcNow.AddHours(expireHours));

        // Log successful listing creation
        _logService?.Write("marketplace_list_success", new
        {
            character_id = characterId,
            listing_id = listingId
        });

        // Return created listing
        return await _repository.GetListingByIdAsync(listingId);
    }

    /// <summary>
    /// Cancels a marketplace listing.
    /// </summary>
    /// <exception cref="LogicException">Thrown when listing is not found, user is not the owner, or listing is already cancelled/sold.</exception>
    public async Task CancelListingAsync(uint characterId, string listingId)
    {
        // Log before cancel
        _logService?.Write("marketplace_cancel", new
        {
            character_id = characterId,
            listing_id = listingId
        });

        var listing = await _repository.GetListingByIdAsync(listingId);
        if (listing == null)
        {
            _logService?.Write("marketplace_cancel_failed", new
            {
                character_id = characterId,
                listing_id = listingId,
                error = "listing_not_found"
            });
            throw new LogicException(ErrorCode.MarketplaceListingNotFound);
        }

        if (listing.SellerId != characterId)
        {
            _logService?.Write("marketplace_cancel_failed", new
            {
                character_id = characterId,
                listing_id = listingId,
                error = "not_owner"
            });
            throw new LogicException(ErrorCode.MarketplaceNotListingOwner);
        }

        if (listing.Status != 0) // Not Active
        {
            // Check if already cancelled or sold
            if (listing.Status == 2) // Cancelled
            {
                _logService?.Write("marketplace_cancel_failed", new
                {
                    character_id = characterId,
                    listing_id = listingId,
                    error = "already_cancelled"
                });
                throw new LogicException(ErrorCode.MarketplaceListingAlreadyCancelled);
            }
            if (listing.Status == 1) // Sold
            {
                _logService?.Write("marketplace_cancel_failed", new
                {
                    character_id = characterId,
                    listing_id = listingId,
                    error = "already_sold"
                });
                throw new LogicException(ErrorCode.MarketplaceListingAlreadySold);
            }
            _logService?.Write("marketplace_cancel_failed", new
            {
                character_id = characterId,
                listing_id = listingId,
                error = "invalid_status"
            });
            throw new LogicException(ErrorCode.MarketplaceListingNotFound);
        }

        await _repository.UpdateListingStatusAsync(listing.Id, 2); // Cancelled

        // Return remaining items to seller via storage_box
        var attachments = new List<Fb.Model.Dsl>
        {
            new Fb.Model.Dsl.Item
            {
                Id = listing.ItemModel,
                Count = listing.RemainingCount,
                Durability = listing.ItemDurability,
                CustomName = listing.ItemCustomName,
                Percent = 100.0
            }.ToDSL()
        };

        await _storageService.CreatePendingAsync(
            Fb.Model.ConstValue.String.MessageMarketplaceListingCancelledTitle,
            Fb.Model.ConstValue.String.MessageMarketplaceListingCancelledMessage,
            listing.SellerId,
            null, // Unlimited expiry for marketplace items
            attachments);

        // Log successful cancellation
        _logService?.Write("marketplace_cancel_success", new
        {
            character_id = characterId,
            listing_id = listingId
        });
    }

    /// <summary>
    /// Purchases items from a marketplace listing.
    /// Supports partial purchases and uses database transaction with row locking to prevent concurrent purchases.
    /// </summary>
    /// <param name="buyerId">The unique identifier of the buyer.</param>
    /// <param name="listingId">The unique identifier of the listing.</param>
    /// <param name="purchaseCount">The number of items to purchase.</param>
    /// <param name="purchaseId">The purchase ID (UUID string generated by game server).</param>
    /// <returns>PurchaseItemResult containing listing, actualPurchaseCount, and refundAmount.</returns>
    /// <exception cref="LogicException">Thrown when purchase ID already exists, listing not found, or insufficient stock.</exception>
    public async Task<PurchaseItemResult> PurchaseItemAsync(
        uint buyerId,
        string listingId,
        ushort purchaseCount,
        string purchaseId)
    {
        // Check if purchase ID already exists
        if (await _purchaseRepository.CheckPurchaseIdExistsAsync(purchaseId))
        {
            _logService?.Write("marketplace_purchase_failed", new
            {
                buyer_id = buyerId,
                listing_id = listingId,
                purchase_id = purchaseId,
                error = "purchase_id_already_exists"
            });
            throw new LogicException(ErrorCode.MarketplaceIdAlreadyExists);
        }

        // Log before purchase
        _logService?.Write("marketplace_purchase", new
        {
            buyer_id = buyerId,
            listing_id = listingId,
            purchase_id = purchaseId,
            purchase_count = purchaseCount
        });

        // Use transaction to ensure atomicity
        await using var conn = _dbContext.Connection(-1);
        await conn.OpenAsync();
        await using var transaction = await conn.BeginTransactionAsync();

        try
        {
            // Load listing with row lock to prevent double-purchase
            var listing = await _repository.GetListingByIdForUpdateAsync(listingId, transaction);
            if (listing == null)
            {
                await transaction.RollbackAsync();
                _logService?.Write("marketplace_purchase_failed", new
                {
                    buyer_id = buyerId,
                    listing_id = listingId,
                    purchase_id = purchaseId,
                    error = "listing_not_found_or_inactive"
                });
                throw new LogicException(ErrorCode.MarketplaceListingNotFound);
            }

            // Determine actual purchase count (may be less than requested if insufficient stock)
            var actualPurchaseCount = (ushort)Math.Min(purchaseCount, listing.RemainingCount);
            if (actualPurchaseCount == 0)
            {
                await transaction.RollbackAsync();
                _logService?.Write("marketplace_purchase_failed", new
                {
                    buyer_id = buyerId,
                    listing_id = listingId,
                    purchase_id = purchaseId,
                    error = "insufficient_stock"
                });
                throw new LogicException(ErrorCode.MarketplaceInsufficientStock);
            }

            // Calculate prices
            var expectedPrice = listing.Price * purchaseCount;
            var actualPrice = listing.Price * actualPurchaseCount;
            var refundAmount = expectedPrice - actualPrice;

            // Update listing (decrement remaining_count, update status/sold_date if needed)
            var (updateSuccess, newRemainingCount, isSold) = await _repository.UpdateListingAsync(
                listingId,
                actualPurchaseCount,
                transaction);

            if (!updateSuccess)
            {
                // Another transaction already purchased or insufficient stock
                await transaction.RollbackAsync();
                _logService?.Write("marketplace_purchase_failed", new
                {
                    buyer_id = buyerId,
                    listing_id = listingId,
                    purchase_id = purchaseId,
                    error = "concurrent_purchase_conflict_or_insufficient_stock"
                });
                throw new LogicException(ErrorCode.MarketplaceInsufficientStock);
            }

            // Create purchase record
            await _purchaseRepository.CreatePurchaseAsync(
                purchaseId,
                listingId,
                buyerId,
                actualPurchaseCount,
                actualPrice,
                transaction);

            // Get item name for sale message
            var itemName = "unknown item name";
            if (Table.Item.TryGetValue(listing.ItemModel, out var model))
            {
                var itemModel = Table.Item[listing.ItemModel];
                itemName = itemModel.Name;
            }

            // Send seller revenue via storage_box (full price, no fees deducted)
            await _storageService.CreatePendingAsync(
                Fb.Model.ConstValue.String.MessageMarketplaceSaleTitle,
                string.Format(Fb.Model.ConstValue.String.MessageMarketplaceSaleMessage.ToCSharpFormat(), itemName, actualPurchaseCount, actualPrice),
                listing.SellerId,
                null, // Unlimited expiry for marketplace items
                [
                    new Fb.Model.Dsl.Money { Value = actualPrice }.ToDSL()
                ]);

            // Prepare buyer attachments (item + refund if any) - all in one storage box
            var buyerAttachments = new List<Fb.Model.Dsl>
            {
                new Fb.Model.Dsl.Item
                {
                    Id = listing.ItemModel,
                    Count = actualPurchaseCount,
                    Durability = listing.ItemDurability,
                    CustomName = listing.ItemCustomName,
                    Percent = 100.0
                }.ToDSL()
            };

            // Add refund amount if there's a discrepancy
            if (refundAmount > 0)
            {
                buyerAttachments.Add(new Fb.Model.Dsl.Money { Value = refundAmount }.ToDSL());
            }

            // Get item name for purchase message (reuse from sale message)
            // Send purchased item and refund (if any) to buyer via storage_box
            // Use different message if refund is included
            string buyerTitle;
            string buyerMessage;
            if (refundAmount > 0)
            {
                buyerTitle = Fb.Model.ConstValue.String.MessageMarketplacePurchaseRefundTitle;
                buyerMessage = string.Format(Fb.Model.ConstValue.String.MessageMarketplacePurchaseRefundMessage.ToCSharpFormat(), itemName, actualPurchaseCount, actualPrice, refundAmount);
            }
            else
            {
                buyerTitle = Fb.Model.ConstValue.String.MessageMarketplacePurchaseTitle;
                buyerMessage = string.Format(Fb.Model.ConstValue.String.MessageMarketplacePurchaseMessage.ToCSharpFormat(), itemName, actualPurchaseCount, actualPrice);
            }

            await _storageService.CreatePendingAsync(
                buyerTitle,
                buyerMessage,
                buyerId,
                null, // Unlimited expiry for marketplace items
                buyerAttachments);

            // Commit transaction
            await transaction.CommitAsync();

            // Log successful purchase
            _logService?.Write("marketplace_purchase_success", new
            {
                buyer_id = buyerId,
                listing_id = listingId,
                purchase_id = purchaseId,
                seller_id = listing.SellerId,
                expected_count = purchaseCount,
                actual_count = actualPurchaseCount,
                expected_price = expectedPrice,
                actual_price = actualPrice,
                refund_amount = refundAmount
            });

            // Return listing with purchase information
            return new PurchaseItemResult
            {
                Listing = listing,
                ActualPurchaseCount = actualPurchaseCount,
                RefundAmount = refundAmount
            };
        }
        catch (Exception ex)
        {
            await transaction.RollbackAsync();
            _logService?.Write("marketplace_purchase_failed", new
            {
                buyer_id = buyerId,
                listing_id = listingId,
                purchase_id = purchaseId,
                error = ex.Message
            });
            throw;
        }
    }

    /// <summary>
    /// Searches marketplace listings.
    /// </summary>
    /// <returns>MarketplaceSearchResult.</returns>
    /// <exception cref="LogicException">Thrown when page is less than 1.</exception>
    public async Task<MarketplaceSearchResult> SearchItemsAsync(MarketplaceSearchOption option)
    {
        // Validate page number
        if (option.Page < 1)
        {
            throw new LogicException(ErrorCode.MarketplaceInvalidPageNumber);
        }

        // Convert item name to item model IDs
        List<uint> itemModelIds = null;
        if (!string.IsNullOrEmpty(option.ItemName))
        {
            itemModelIds = Table.Item.NameToItemModelIds(option.ItemName);
        }

        // Get page size from configuration (default: 20)
        var pageSize = _configuration.GetValue<int>("Marketplace:PageSize", 20);

        // Search listings
        var listings = await _repository.SearchListingsAsync(
            itemModelIds,
            option.MinPrice,
            option.MaxPrice,
            option.SellerId,
            string.IsNullOrEmpty(option.SortBy) ? "name_price_asc" : option.SortBy,
            (int)option.Page,
            pageSize);

        var totalCount = await _repository.CountListingsAsync(
            itemModelIds,
            option.MinPrice,
            option.MaxPrice,
            option.SellerId);

        return new MarketplaceSearchResult
        {
            Listings = listings,
            TotalCount = totalCount
        };
    }

    /// <summary>
    /// Gets a listing by ID.
    /// </summary>
    /// <returns>MarketplaceListing if found; null if not found.</returns>
    public async Task<MarketplaceListing> GetListingByIdAsync(string listingId)
    {
        return await _repository.GetListingByIdAsync(listingId);
    }

    /// <summary>
    /// Gets multiple listings by their IDs.
    /// Optionally includes purchase information for a specific buyer.
    /// </summary>
    /// <param name="listingIds">List of listing IDs to retrieve.</param>
    /// <param name="buyerId">Optional buyer ID to include purchase information for.</param>
    /// <returns>List of ListingWithPurchase objects found.</returns>
    public async Task<List<ListingWithPurchase>> GetListingsByIdsAsync(
        List<string> listingIds,
        uint? buyerId = null)
    {
        var listings = await _repository.GetListingsByIdsAsync(listingIds);

        if (!buyerId.HasValue || listings.Count == 0)
        {
            return listings.Select(l => new ListingWithPurchase
            {
                Listing = l,
                Purchase = null
            }).ToList();
        }

        // Get purchase records for the buyer
        var purchases = await _repository.GetPurchasesByListingIdsAndBuyerAsync(listingIds, buyerId.Value);

        return listings.Select(l =>
        {
            purchases.TryGetValue(l.Id, out var purchase);
            return new ListingWithPurchase
            {
                Listing = l,
                Purchase = purchase
            };
        }).ToList();
    }

    /// <summary>
    /// Gets multiple purchase records by their IDs.
    /// </summary>
    /// <param name="purchaseIds">List of purchase IDs to retrieve.</param>
    /// <returns>Dictionary mapping purchase IDs to purchase records.</returns>
    public async Task<Dictionary<string, MarketplacePurchase>> GetPurchasesByIdsAsync(List<string> purchaseIds)
    {
        return await _purchaseRepository.GetPurchasesByIdsAsync(purchaseIds);
    }

}

