-- Integration test registry
-- Phase A: parallel (default). Phase B: serial after Phase A drains.

register_test("movement_test")
register_test("attack_test")
register_test("skill_test")
register_test("bulletin_test")
register_test("trade_test")
register_test("communication_test")
register_test("drop_loot_test")
register_test("item_test")
register_test("item_give_test")
register_test("emotion_test")
register_test("front_info_test")
register_test("instance_map_test", { extra_slot = true })
register_test("chat_interaction_test")
register_test("user_list_test")
register_test("swap_test")
register_test("throw_test")
register_test("group_test")
register_test("matchmaking_test")
register_test("clan_test")
register_test("marriage_test", { serial = true })
register_test("marketplace_test")
register_test("storage_box_test")
register_test("worldmap_test")
register_test("door_test")
register_test("rabbit_quest_test")
register_test("mob_parts_test")
register_test("resist_test")
