using Dapper;
using Http.Extension;
using Http.Reepository;
using Http.Service;
using Marketplace.Model;

namespace Marketplace.Reepository
{
    /// <summary>
    /// Provides repository functionality for marketplace purchase records.
    /// Handles database operations for purchase history tracking.
    /// </summary>
    public class MarketplacePurchaseRepository : IRepository
    {
        private readonly DbContext _dbContext;

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketplacePurchaseRepository"/> class.
        /// </summary>
        /// <param name="dbContext">The database context for connection management.</param>
        public MarketplacePurchaseRepository(DbContext dbContext)
        {
            _dbContext = dbContext;
        }

        /// <summary>
        /// Creates a new marketplace purchase record.
        /// </summary>
        /// <param name="purchaseId">The unique identifier of the purchase (UUID string generated by game server).</param>
        /// <param name="listingId">The unique identifier of the listing that was purchased.</param>
        /// <param name="buyerId">The unique identifier of the buyer.</param>
        /// <param name="purchaseCount">The actual number of items purchased.</param>
        /// <param name="purchasePrice">The total price paid (purchase_count * unit_price).</param>
        /// <param name="transaction">Optional database transaction.</param>
        /// <returns>The unique identifier of the created purchase (UUID string).</returns>
        public async Task<string> CreatePurchaseAsync(
            string purchaseId,
            string listingId,
            uint buyerId,
            ushort purchaseCount,
            uint purchasePrice,
            System.Data.IDbTransaction transaction = null)
        {
            var sql = $"""
                INSERT INTO `marketplace_purchase` (
                    `id`,
                    `listing_id`,
                    `buyer_id`,
                    `purchase_count`,
                    `purchase_price`,
                    `created_date`)
                VALUES (
                    {purchaseId.Escape()},
                    {listingId.Escape()},
                    {buyerId.Escape()},
                    {purchaseCount.Escape()},
                    {purchasePrice.Escape()},
                    NOW())
                """;

            if (transaction != null)
            {
                await transaction.Connection.ExecuteAsync(sql, null, transaction);
            }
            else
            {
                await using var conn = _dbContext.Connection(-1);
                await conn.ExecuteAsync(sql);
            }

            return purchaseId;
        }

        /// <summary>
        /// Retrieves multiple marketplace purchase records by their unique identifiers.
        /// </summary>
        /// <param name="purchaseIds">List of unique identifiers of the purchases (UUID strings).</param>
        /// <returns>Dictionary mapping purchase IDs to purchase records; empty dictionary if none found.</returns>
        public async Task<Dictionary<string, MarketplacePurchase>> GetPurchasesByIdsAsync(List<string> purchaseIds)
        {
            if (purchaseIds == null || purchaseIds.Count == 0)
            {
                return new Dictionary<string, MarketplacePurchase>();
            }

            await using var conn = _dbContext.Connection(-1);
            var parameters = new DynamicParameters();
            parameters.Add("PurchaseIds", purchaseIds);

            var sql = @"
                SELECT * FROM `marketplace_purchase` 
                WHERE `id` IN @PurchaseIds";

            var purchases = await conn.QueryAsync<MarketplacePurchase>(sql, parameters);
            return purchases.ToDictionary(p => p.Id, p => p);
        }

        /// <summary>
        /// Retrieves purchase records for a specific listing.
        /// </summary>
        /// <param name="listingId">The unique identifier of the listing.</param>
        /// <returns>List of purchase records for the listing; empty list if none found.</returns>
        public async Task<List<MarketplacePurchase>> GetPurchasesByListingIdAsync(string listingId)
        {
            await using var conn = _dbContext.Connection(-1);
            var sql = $@"
                SELECT * FROM `marketplace_purchase` 
                WHERE `listing_id` = {listingId.Escape()}
                ORDER BY `created_date` DESC";

            return (await conn.QueryAsync<MarketplacePurchase>(sql)).ToList();
        }

        /// <summary>
        /// Checks if a purchase ID already exists in the database.
        /// Used for ID duplication validation.
        /// </summary>
        /// <param name="purchaseId">The unique identifier of the purchase (UUID string).</param>
        /// <returns>True if the purchase ID exists; otherwise, false.</returns>
        public async Task<bool> CheckPurchaseIdExistsAsync(string purchaseId)
        {
            await using var conn = _dbContext.Connection(-1);
            var sql = $@"
                SELECT COUNT(*) FROM `marketplace_purchase` 
                WHERE `id` = {purchaseId.Escape()}";

            var count = await conn.QuerySingleAsync<int>(sql);
            return count > 0;
        }

        /// <summary>
        /// Saves any pending changes to the underlying data store.
        /// This implementation returns a completed task as purchase operations are immediately persisted.
        /// </summary>
        /// <returns>A completed task representing the save operation.</returns>
        public Task SaveChangesAsync()
        {
            return Task.CompletedTask;
        }
    }
}
