// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.marketplace.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AllocateListingId : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AllocateListingId GetRootAsAllocateListingId(ByteBuffer _bb) { return GetRootAsAllocateListingId(_bb, new AllocateListingId()); }
  public static AllocateListingId GetRootAsAllocateListingId(ByteBuffer _bb, AllocateListingId obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyAllocateListingId(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, AllocateListingIdVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AllocateListingId __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<fb.protocol.marketplace.request.raw.AllocateListingId> CreateAllocateListingId(FlatBufferBuilder builder,
      uint character_id = 0) {
    builder.StartTable(1);
    AllocateListingId.AddCharacterId(builder, character_id);
    return AllocateListingId.EndAllocateListingId(builder);
  }

  public static void StartAllocateListingId(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCharacterId(FlatBufferBuilder builder, uint characterId) { builder.AddUint(0, characterId, 0); }
  public static Offset<fb.protocol.marketplace.request.raw.AllocateListingId> EndAllocateListingId(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.marketplace.request.raw.AllocateListingId>(o);
  }
  public static void FinishAllocateListingIdBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.request.raw.AllocateListingId> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAllocateListingIdBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.request.raw.AllocateListingId> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class AllocateListingIdVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CharacterId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
