// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb.protocol.marketplace.request.raw
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MarketplaceCompletePendingTransaction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MarketplaceCompletePendingTransaction GetRootAsMarketplaceCompletePendingTransaction(ByteBuffer _bb) { return GetRootAsMarketplaceCompletePendingTransaction(_bb, new MarketplaceCompletePendingTransaction()); }
  public static MarketplaceCompletePendingTransaction GetRootAsMarketplaceCompletePendingTransaction(ByteBuffer _bb, MarketplaceCompletePendingTransaction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMarketplaceCompletePendingTransaction(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MarketplaceCompletePendingTransactionVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MarketplaceCompletePendingTransaction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong TransactionId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<fb.protocol.marketplace.request.raw.MarketplaceCompletePendingTransaction> CreateMarketplaceCompletePendingTransaction(FlatBufferBuilder builder,
      ulong transaction_id = 0) {
    builder.StartTable(1);
    MarketplaceCompletePendingTransaction.AddTransactionId(builder, transaction_id);
    return MarketplaceCompletePendingTransaction.EndMarketplaceCompletePendingTransaction(builder);
  }

  public static void StartMarketplaceCompletePendingTransaction(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTransactionId(FlatBufferBuilder builder, ulong transactionId) { builder.AddUlong(0, transactionId, 0); }
  public static Offset<fb.protocol.marketplace.request.raw.MarketplaceCompletePendingTransaction> EndMarketplaceCompletePendingTransaction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.protocol.marketplace.request.raw.MarketplaceCompletePendingTransaction>(o);
  }
  public static void FinishMarketplaceCompletePendingTransactionBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.request.raw.MarketplaceCompletePendingTransaction> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMarketplaceCompletePendingTransactionBuffer(FlatBufferBuilder builder, Offset<fb.protocol.marketplace.request.raw.MarketplaceCompletePendingTransaction> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MarketplaceCompletePendingTransactionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TransactionId*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
