-- @transaction off
SET FOREIGN_KEY_CHECKS=0;
SET NAMES utf8mb4;

CREATE TABLE `marketplace_listing` (
  `id` VARCHAR(36) NOT NULL,
  `world` INT UNSIGNED NOT NULL COMMENT 'World identifier (e.g., 1, 2)',
  `seller_id` INT UNSIGNED NOT NULL,
  `item_model` INT UNSIGNED NOT NULL,
  `remaining_count` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Remaining item count available for purchase',
  `item_durability` INT UNSIGNED DEFAULT NULL,
  `item_custom_name` VARCHAR(32) DEFAULT NULL,
  `price` INT UNSIGNED NOT NULL COMMENT 'Per unit price set by seller',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=Active, 1=Sold, 2=Cancelled, 3=Expired',
  `expire_date` DATETIME NOT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sold_date` DATETIME DEFAULT NULL COMMENT 'Set when remaining_count becomes 0',
  PRIMARY KEY (`id`),
  KEY `idx_seller` (`seller_id`, `status`),
  KEY `idx_item_model` (`item_model`, `status`),
  KEY `idx_status_expire` (`status`, `expire_date`),
  KEY `idx_created` (`created_date`),
  KEY `idx_world` (`world`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `marketplace_listing_archive` (
  `id` VARCHAR(36) NOT NULL,
  `world` INT UNSIGNED NOT NULL COMMENT 'World identifier (e.g., 1, 2)',
  `seller_id` INT UNSIGNED NOT NULL,
  `item_model` INT UNSIGNED NOT NULL,
  `remaining_count` SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Remaining item count available for purchase',
  `item_durability` INT UNSIGNED DEFAULT NULL,
  `item_custom_name` VARCHAR(32) DEFAULT NULL,
  `price` INT UNSIGNED NOT NULL COMMENT 'Per unit price set by seller',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0=Active, 1=Sold, 2=Cancelled, 3=Expired',
  `expire_date` DATETIME NOT NULL,
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `sold_date` DATETIME DEFAULT NULL COMMENT 'Set when remaining_count becomes 0',
  `archived_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when listing was archived',
  PRIMARY KEY (`id`),
  KEY `idx_seller` (`seller_id`, `status`),
  KEY `idx_item_model` (`item_model`, `status`),
  KEY `idx_status_expire` (`status`, `expire_date`),
  KEY `idx_archived` (`archived_date`),
  KEY `idx_world` (`world`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `marketplace_purchase` (
  `id` VARCHAR(36) NOT NULL COMMENT 'Purchase ID (UUID generated by game server)',
  `world` INT UNSIGNED NOT NULL COMMENT 'World identifier (e.g., 1, 2)',
  `listing_id` VARCHAR(36) NOT NULL,
  `buyer_id` INT UNSIGNED NOT NULL,
  `purchase_count` SMALLINT UNSIGNED NOT NULL COMMENT 'Actual number of items purchased',
  `purchase_price` INT UNSIGNED NOT NULL COMMENT 'Total price paid (purchase_count * unit_price)',
  `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_id` (`id`),
  KEY `idx_listing` (`listing_id`),
  KEY `idx_buyer` (`buyer_id`),
  KEY `idx_created` (`created_date`),
  KEY `idx_world` (`world`),
  CONSTRAINT `fk_purchase_listing` FOREIGN KEY (`listing_id`) REFERENCES `marketplace_listing` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `marketplace_statistics` (
  `item_model` INT UNSIGNED NOT NULL,
  `total_sold` INT UNSIGNED NOT NULL DEFAULT 0,
  `total_volume` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `avg_price` INT UNSIGNED NOT NULL DEFAULT 0,
  `min_price` INT UNSIGNED NOT NULL DEFAULT 0,
  `max_price` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`item_model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;
