-- Widen authoritative character and marketplace pending amounts to 64-bit.
ALTER TABLE `user`
  MODIFY COLUMN `exp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN `money` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN `deposited_money` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN `hp` BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN `base_hp` BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN `additional_hp` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN `mp` BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN `base_mp` BIGINT UNSIGNED NOT NULL,
  MODIFY COLUMN `additional_mp` BIGINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `marketplace_pending`
  MODIFY COLUMN `expected_total_price` BIGINT UNSIGNED NOT NULL DEFAULT 0;
