name: build fb - Linux

on:
  push:
    branches:
      - release/**

env:
  REGISTRY: ghcr.io

jobs:
  build-linux:
    runs-on: [self-hosted, linux, build, epyc]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/build
          flavor: |
            latest=true

      - name: Build based builder image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build
          cache-to: type=gha,scope=build,mode=max
          file: server/fb/Dockerfile

  internal:
    runs-on: [self-hosted, linux, build]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/internal
          flavor: |
            latest=true

      - name: Build internal server
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=internal
          cache-to: type=gha,scope=internal,mode=max
          file: server/http/Dockerfile
          build-args: |
            SERVICE=internal

  write-back:
    runs-on: [self-hosted, linux, build]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/write-back
          flavor: |
            latest=true

      - name: Build write-back app
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=write-back
          cache-to: type=gha,scope=write-back,mode=max
          file: server/http/Dockerfile
          build-args: |
            SERVICE=write-back

  gateway:
    runs-on: [self-hosted, linux, build]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/gateway
          flavor: |
            latest=true

      - name: Build gateway server
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=gateway
          cache-to: type=gha,scope=gateway,mode=max
          file: server/gateway/Dockerfile

  login:
    runs-on: [self-hosted, linux, build]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/login
          flavor: |
            latest=true

      - name: Build login server
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=login
          cache-to: type=gha,scope=login,mode=max
          file: server/login/Dockerfile

  game:
    runs-on: [self-hosted, linux, build, epyc]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/game
          flavor: |
            latest=true

      - name: Build game server
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=game
          cache-to: type=gha,scope=game,mode=max
          file: server/game/Dockerfile

  bot:
    runs-on: [self-hosted, linux, build, epyc]
    permissions:
      contents: read
      packages: write
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
         version: latest

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/bot
          flavor: |
            latest=true

      - name: Build bot spawner
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=bot
          cache-to: type=gha,scope=bot,mode=max
          file: server/bot/Dockerfile

  deploy:
    runs-on: [self-hosted, linux, build]
    permissions:
      contents: read
      packages: write
    needs: [internal, write-back, bot, gateway, login, game]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: infra/pulumi

      - name: Installing dependencies
        run: npm install
        working-directory: infra/pulumi

      - name: Shutdown server
        uses: pulumi/actions@v6
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          work-dir: infra/pulumi
          command: destroy
          stack-name: dev

      - name: Deploy server
        uses: pulumi/actions@v6
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          work-dir: infra/pulumi
          command: up
          stack-name: dev
          refresh: true
          config-map: "{host: {value: '${{ secrets.REMOTE_IP }}', secret: true}}"

  build-windows:
    runs-on: [self-hosted, windows, build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: false

      - name: Update modules
        run: .\update-modules.bat
        working-directory: tools

      - name: Create build directory
        run: if (-Not (Test-Path build)) { mkdir build }

      - name: Configure CMake
        run: cmake ..
        working-directory: build

      - name: Build c++
        run: |
          cmake --build . --config Debug
          mv -Force server\gateway\Debug\gateway.exe gateway.exe
          mv -Force server\login\Debug\login.exe login.exe
          mv -Force server\game\Debug\game.exe game.exe
        working-directory: build

      - name: Build internal
        run: dotnet publish server/internal/internal.csproj -c Release -o build/internal

      - name: Build write-back
        run: dotnet publish server/write-back/write-back.csproj -c Release -o build/write-back

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            build/gateway.exe
            build/login.exe
            build/game.exe
            build/internal
            build/write-back
          retention-days: 7

      - name: Zip the downloaded artifact
        shell: powershell
        run: |
          Compress-Archive -Path dist_zip\* -DestinationPath dist.zip -Force

      - name: Upload zip to NAS
        shell: powershell
        run: |
          curl.exe -T dist.zip -u "$env:NAS_ID`:$env:NAS_PW" http://cshyeon.com:8080/upload/fb/dist.zip
        env:
          NAS_ID: ${{ secrets.NAS_ID }}
          NAS_PW: ${{ secrets.NAS_PW }}